import type { EngineSoundCopy } from './types';

// German — search-term research: drivers search "Motorgeräusche",
// "Motor klackert / tickert" (ticking, Hydrostößel), "Motorklopfen" /
// "Motor klopft" (knock, Pleuellager) and "Motor rasselt / klappert" (rattling).
export const de: EngineSoundCopy = {
  lang: 'de',
  locale: 'de_DE',
  dir: 'ltr',
  homeHref: '/startseite',
  homeLabel: 'Startseite',
  hubHref: '/werkzeuge',
  hubLabel: 'Werkzeuge',
  backLabel: 'Zurück zu den Werkzeugen',
  slug: 'motorgeraeusch-analyse',
  metaTitle: 'Motorgeräusch-Analyse — Kostenlose KI-Diagnose per Audio | Naira Autos',
  metaDescription: 'Motorgeräusch aufnehmen oder hochladen und sofort eine KI-Diagnose der wahrscheinlichen Ursache erhalten: Klackern, Klopfen, Rasseln und mehr. Kostenlos, ohne Anmeldung.',
  keywords: ['Motorgeräusche', 'Motorgeräusch Ursachen', 'Motor klackert', 'Motor klopft', 'Motor rasselt', 'Motorklopfen', 'Motorgeräusch Diagnose', 'Motorgeräusch Analyse', 'Auto macht komische Geräusche'],
  ogDescription: 'Motorgeräusch aufnehmen oder hochladen und sofort eine KI-Diagnose der wahrscheinlichen Ursache erhalten.',
  toolName: 'Motorgeräusch-Analyse',
  schemaDescription: 'Kostenloses KI-Tool, das Fahrzeugprobleme anhand einer Aufnahme des Motorgeräuschs diagnostiziert.',
  badge: 'Kostenloses Tool',
  verified: 'Zuletzt geprüft: September 2026',
  h1a: 'Motorgeräusch-',
  h1b: 'Analyse',
  intro: 'Nimm das Geräusch deines Autos auf oder lade es hoch und erhalte sofort eine KI-Diagnose: wahrscheinliche Ursachen, wie dringend es ist und was die Reparatur kosten könnte.',
  pickerEyebrow: 'Welches Geräusch hörst du?',
  pickerTitle: 'Wähle das passendste',
  pickerCta: 'Dieses Geräusch diagnostizieren →',
  pickerNote: 'Du weißt nicht, welches passt? Der Rekorder oben analysiert jedes Motorgeräusch – du musst vorher keine Kategorie wählen.',
  sections: [
    {
      h2: 'Was ist eine Motorgeräusch-Analyse?',
      paras: [
        'Ein erfahrener Kfz-Mechaniker hört oft schon am Motorgeräusch, was dem Auto fehlt – noch bevor die Motorhaube offen ist. Dieses Tool macht dasselbe mit KI: Du nimmst das Geräusch deines Autos auf oder lädst einen Clip hoch, und die KI bestimmt die wahrscheinlichste Ursache – wie ein Mechaniker, der nach Gehör diagnostiziert.',
        'Es funktioniert bei jedem ungewöhnlichen Motorgeräusch, nicht nur bei den drei oben: Pfeifen, Quietschen, Schleifen, Brummen oder Klicken. Wenn du es aufnehmen kannst, kann die KI eine Diagnose versuchen. Eine kurze Beschreibung (z. B. „nur beim Kaltstart“) sowie Marke und Modell machen das Ergebnis genauer.',
      ],
    },
    {
      h2: 'Warum Motorgeräusche ernst zu nehmen sind',
      paras: [
        'Ein neues Motorgeräusch kommt selten aus dem Nichts. Ein Klackern, Klopfen oder Rasseln bedeutet fast immer, dass sich etwas verändert hat: ein Bauteil verschleißt, der Ölstand ist zu niedrig oder etwas hat sich gelockert. Manche Geräusche sind harmlos, andere kündigen Schäden an, die schnell schlimmer werden – etwa Pleuellagerschaden.',
        'Das Geräusch aufzunehmen und eine erste Einschätzung zu bekommen, kostet nichts und dauert unter einer Minute. Das ist oft deutlich günstiger, als zu warten, bis aus einem kleinen Problem ein teurer Schaden wird.',
      ],
    },
    {
      h2: 'Der Unterschied zur Suche im Forum',
      paras: [
        'Wer ein Symptom im Internet sucht, bekommt meist eine lange, allgemeine Liste von allem, was das Geräusch theoretisch auslösen kann – gut zum Informieren, aber wenig hilfreich, um herauszufinden, was bei deinem Auto los ist. Hier beginnt die Analyse mit deiner eigenen Aufnahme und deinen Angaben und zeigt dir die wahrscheinlichsten Ursachen und die Dringlichkeit.',
        'Eine Prüfung in der Werkstatt ersetzt das nicht. Sieh es als schnellen, kostenlosen ersten Schritt: Du erfährst, ob du weiterfahren kannst und was du prüfen oder in der Werkstatt ansprechen solltest, bevor du Geld für eine Vermutung ausgibst.',
      ],
    },
  ],
  tipsTitle: 'Tipps für eine auswertbare Aufnahme',
  tips: [
    'Gehe so nah wie sicher möglich an die Geräuschquelle: in den Motorraum bei Motorgeräuschen, an ein Rad bei Verdacht auf Bremse oder Fahrwerk.',
    'Schalte das Radio aus und schließe die Fenster, damit Wind und Verkehr das Geräusch nicht überdecken.',
    'Nimm das Geräusch auf, wenn es am deutlichsten ist: beim Kaltstart für Hydrostößel-Klackern, beim Beschleunigen für Klopfen, über eine Bodenwelle für Rasseln.',
    'Notiere, wann es auftritt (nur kalt, nur beim Lenken, nur unter Last): Das Beschreibungsfeld hilft der KI, die Diagnose einzugrenzen.',
  ],
  exampleTitle: 'Beispiel: Ein Klackern beim Kaltstart, das harmlos war',
  exampleText: 'Der VW Golf von Jonas klackerte jeden Morgen nach dem Kaltstart und wurde nach ein bis zwei Minuten leiser, sobald der Motor warm war. Aus Sorge um die Lager nahm er 15 Sekunden auf und ließ sie analysieren. Das Klangmuster passte zu Hydrostößeln bei noch kaltem Öl, nicht zu einem Pleuellagerproblem. Er prüfte den Ölstand: zu niedrig. Nach dem Ölwechsel war das Klackern weg.',
  reviewedBefore: 'Geprüft von',
  reviewedAfter: ', Kfz-Mechaniker. Geräuschkategorien auf Werkstattpraxis abgestimmt.',
  faqTitle: 'FAQ zur Motorgeräusch-Analyse',
  faqs: [
    { q: 'Was ist eine Motorgeräusch-Analyse?', a: 'Ein Tool, das die Aufnahme deines Motorgeräuschs auswertet und per KI die wahrscheinliche Ursache bestimmt – wie ein Mechaniker, der nach Gehör diagnostiziert, bevor er die Motorhaube öffnet.' },
    { q: 'Welche Motorgeräusche kann es diagnostizieren?', a: 'Klackern, Klopfen, Rasseln, Quietschen, Schleifen, Pfeifen, Brummen und die meisten ungewöhnlichen Geräusche. Wenn du es aufnehmen kannst, kann die KI eine Diagnose versuchen.' },
    { q: 'Wie lang muss die Aufnahme sein?', a: 'Die kostenlose Version analysiert die ersten 30 Sekunden jedes Clips – das reicht normalerweise für eine klare Diagnose.' },
    { q: 'Ist die Diagnose immer richtig?', a: 'Nein. Sie ist ein guter Ausgangspunkt, keine endgültige Antwort, und kann Dinge übersehen, die eine Prüfung vor Ort finden würde. Bei Geräuschen an Bremse, Lenkung oder Kraftstoffsystem: nicht weiterfahren und eine Werkstatt aufsuchen.' },
    { q: 'Ist das Tool kostenlos?', a: 'Ja, kostenlos und ohne Anmeldung. Längere Aufnahmen über 30 Sekunden sind später als Bezahloption geplant.' },
  ],
  relatedTitle: 'Weitere kostenlose Tools',
  relatedLabels: { mechanic: 'Virtueller Mechaniker', value: 'Was ist mein Auto wert?', vin: 'FIN-Prüfung' },
  subs: [
    {
      key: 'ticking',
      slug: 'motor-klackert',
      navLabel: 'Motor klackert',
      cardDesc: 'Ein leichtes, schnelles Ticken oder Klackern – oft Hydrostößel, Einspritzdüsen oder Ventiltrieb.',
      metaTitle: 'Motor klackert oder tickert — Kostenlose KI-Diagnose | Naira Autos',
      metaDescription: 'Motor klackert oder tickert? Geräusch aufnehmen und eine KI-Diagnose erhalten: Hydrostößel, Ölmangel, Einspritzdüsen und mehr. Kostenlos, ohne Anmeldung.',
      keywords: ['Motor klackert', 'Motor tickert', 'Motor klackert beim Kaltstart', 'Hydrostößel klackern', 'Klackern beim Starten', 'Motor tickt im Leerlauf', 'Dieselmotor klackert'],
      h1a: 'Analyse:',
      h1b: 'Motor klackert',
      intro: 'Ein leichtes, gleichmäßiges Klackern hat oft eine einfache Ursache. Nimm es auf und finde heraus, ob es am Öl liegt oder etwas Ernstes ist.',
      schemaDescription: 'Kostenloses KI-Tool, das klackernde oder tickernde Motorgeräusche anhand einer Audioaufnahme diagnostiziert.',
      sections: [
        {
          h2: 'Warum klackert der Motor?',
          paras: [
            'Klackern ist ein leichtes, schnelles metallisches Geräusch im Takt des Motors. Häufige Ursachen sind hydraulische Ventilstößel oder Ventilspiel, zu niedriger oder verbrauchter Ölstand, klackernde Einspritzdüsen (bis zu einem gewissen Grad normal) und seltener eine verschlissene Steuerkette oder ein Kettenspanner.',
            'Der Zeitpunkt ist ein wichtiger Hinweis: Klackern, das nach dem Warmlaufen verschwindet, ist meist weniger kritisch als eines, das bleibt oder mit der Drehzahl zunimmt.',
          ],
        },
        {
          h2: 'Klackern nur beim Kaltstart: Ist das schlimm?',
          paras: [
            'Viele Motoren klackern nach dem Kaltstart kurz, weil das Öl ein paar Sekunden braucht, bis es die Hydrostößel erreicht. Verschwindet das Geräusch nach ein bis zwei Minuten und der Ölstand stimmt, ist es normalerweise kein Grund zur Sorge – beobachten solltest du es trotzdem.',
            'Bleibt es bei warmem Motor, wird es mit der Zeit schlimmer oder kommen Leistungsverlust oder die Öldruckleuchte dazu, warte nicht: Ölstand sofort prüfen und das Auto untersuchen lassen.',
          ],
        },
        {
          h2: 'Was du vor dem Werkstattbesuch prüfen kannst',
          paras: [
            'Prüfe den Ölstand bei kaltem Motor auf ebenem Untergrund und achte darauf, ob das Öl sehr dunkel oder dickflüssig ist. Beobachte, ob das Geräusch mit der Drehzahl mitgeht: Wird es mit dem Motor schneller, kommt es aus dem oberen Motorbereich; folgt es der Fahrgeschwindigkeit, liegt die Ursache woanders.',
          ],
        },
      ],
      exampleTitle: 'Beispiel: Klackern, das mit Öl behoben war',
      exampleText: 'Lena bemerkte an ihrem Opel Corsa ein dauerhaftes Klackern, nachdem sie monatelang nicht auf den Ölstand geachtet hatte. Sie nahm das Geräusch auf; das Tool deutete auf unzureichende Schmierung im oberen Motorbereich und riet, zuerst den Ölstand zu prüfen. Er lag knapp am Minimum. Nach Ölwechsel mit neuem Filter war das Geräusch verschwunden.',
      reviewedAfter: ', Kfz-Mechaniker. Ursachen für Klackern auf Werkstattpraxis abgestimmt.',
      faqTitle: 'FAQ: Motor klackert',
      faqs: [
        { q: 'Warum klackert mein Motor?', a: 'Am häufigsten durch Ölmangel oder verbrauchtes Öl, das Hydrostößel und Ventiltrieb beeinträchtigt; auch Einspritzdüsen, die Steuerkette oder ein lockeres Bauteil kommen infrage.' },
        { q: 'Ist Klackern beim Kaltstart normal?', a: 'Ein kurzes Klackern, das nach dem Warmlaufen verschwindet, ist bei vielen Motoren üblich. Dauert es länger oder kommt es wieder, prüfe das Öl.' },
        { q: 'Kann ich mit dem Geräusch weiterfahren?', a: 'Wenn der Ölstand stimmt und das Geräusch leicht ist, meist kurzzeitig ja – lass es aber bald prüfen. Bei Öldruckleuchte oder Leistungsverlust: anhalten.' },
        { q: 'Was sind Hydrostößel?', a: 'Bauteile, die die Bewegung der Nockenwelle auf die Ventile übertragen und das Ventilspiel ausgleichen. Bei schlechter Schmierung oder Verschleiß erzeugen sie ein typisches Klackern.' },
      ],
    },
    {
      key: 'knocking',
      slug: 'motor-klopft',
      navLabel: 'Motor klopft',
      cardDesc: 'Ein tieferes, schwereres Klopfen – kann am Kraftstoff liegen oder an einem ernsten Lagerschaden.',
      metaTitle: 'Motor klopft (Motorklopfen) — Kostenlose KI-Diagnose | Naira Autos',
      metaDescription: 'Motor klopft? Geräusch aufnehmen und eine KI-Diagnose erhalten: Pleuellagerschaden, klopfende Verbrennung, Einspritzdüsen und mehr. Kostenlos, ohne Anmeldung.',
      keywords: ['Motor klopft', 'Motorklopfen', 'Motor klopft beim Beschleunigen', 'Pleuellager klopft', 'klopfende Verbrennung', 'Dieselmotor nagelt', 'Motor klopft Ursachen'],
      h1a: 'Analyse:',
      h1b: 'Motor klopft',
      intro: 'Ein tiefes, schweres Klopfen solltest du ernst nehmen. Nimm es auf und finde heraus, ob es am Kraftstoff liegt oder etwas Mechanisches dahintersteckt.',
      schemaDescription: 'Kostenloses KI-Tool, das Motorklopfen anhand einer Audioaufnahme diagnostiziert.',
      sections: [
        {
          h2: 'Warum klopft der Motor?',
          paras: [
            'Klopfen ist eine Stufe ernster als Klackern: tiefer, schwerer und meist lauter unter Last oder bei höherer Drehzahl. Hauptursachen sind klopfende Verbrennung (Kraftstoff entzündet sich ungleichmäßig – z. B. durch zu niedrige Oktanzahl oder Ölkohle), verschlissene Pleuel- oder Hauptlager, eine defekte Dieseleinspritzdüse oder ein loses Anbauteil wie die Lichtmaschinenscheibe.',
            'Der Zeitpunkt ist entscheidend: Klopfen direkt nach dem Tanken deutet auf den Kraftstoff, Klopfen, das über Wochen schleichend lauter wird – unabhängig vom Kraftstoff –, eher auf Lagerverschleiß.',
          ],
        },
        {
          h2: 'Pleuellagerklopfen: das, was du ernst nehmen musst',
          paras: [
            'Pleuellagerklopfen ist ein tiefes, rhythmisches Klopfen durch zu großes Spiel im verschlissenen Pleuellager. Es wird mit steigender Drehzahl lauter und ist unter Last oft deutlicher als im Leerlauf. Anders als kraftstoffbedingtes Klopfen bessert es sich nicht durch anderen Sprit, und Weiterfahren kann in einem Motorschaden enden.',
          ],
        },
        {
          h2: 'Kann schlechter Kraftstoff Motorklopfen verursachen?',
          paras: [
            'Ja. Kraftstoff mit niedrigerer Oktanzahl, als der Motor verlangt, kann klopfende Verbrennung auslösen, die beim Beschleunigen wie metallisches Klingeln klingt. Sie ist meist leichter als mechanisches Klopfen und verschwindet oft mit besserem Sprit oder einer Reinigung des Einspritzsystems.',
          ],
        },
        {
          h2: 'Klopfen beim Dieselmotor',
          paras: [
            'Dieselmotoren sind bauartbedingt lauter als Benziner („Nageln“), ein neues Klopfen fällt daher schwerer auf – verdient aber Aufmerksamkeit, sobald du es bemerkst. Ist es neu oder wird es stärker, sind Einspritzdüsen eine häufige Ursache. Nimm es auf und vergleiche es mit dem gewohnten Klang deines Motors.',
          ],
        },
      ],
      exampleTitle: 'Beispiel: Es war der Kraftstoff, nicht das Pleuellager',
      exampleText: 'Der Ford Focus von Markus begann beim Beschleunigen zu klopfen – direkt nach dem Tanken an einer Tankstelle, die er sonst nie nutzt. Bei dem Kilometerstand befürchtete er einen Lagerschaden und nahm das Geräusch auf, bevor er Geld für eine Diagnose ausgab. Das Muster passte zu klopfender Verbrennung durch den Kraftstoff; nach dem Volltanken mit höherer Oktanzahl war das Klopfen weg.',
      reviewedAfter: ', Kfz-Mechaniker. Klopfarten und Ursachen auf Werkstattpraxis abgestimmt.',
      faqTitle: 'FAQ: Motor klopft',
      faqs: [
        { q: 'Warum klopft mein Motor beim Beschleunigen?', a: 'Klopfende Verbrennung durch Kraftstoff mit zu niedriger Oktanzahl, verschlissene Pleuellager, eine defekte Dieseleinspritzdüse oder ein loses Anbauteil. Wann es auftritt, ist ein wichtiger Hinweis.' },
        { q: 'Ist Motorklopfen immer ernst?', a: 'Nicht immer, aber es verlangt mehr Vorsicht als Klackern. Kraftstoffbedingtes Klopfen ist oft beherrschbar; Pleuellagerklopfen ist ein echtes mechanisches Problem, das schlimmer wird.' },
        { q: 'Was ist Pleuellagerklopfen?', a: 'Ein tiefes, rhythmisches Klopfen durch Spiel im verschlissenen Pleuellager. Es steigt mit der Drehzahl, bessert sich nicht mit anderem Kraftstoff und schädigt den Motor, je länger du fährst.' },
        { q: 'Warum klopft mein Dieselmotor?', a: 'Diesel sind bauartbedingt lauter, aber ein neues oder zunehmendes Klopfen deutet oft auf die Einspritzdüsen.' },
        { q: 'Kann schlechter Kraftstoff Klopfen verursachen?', a: 'Ja, Kraftstoff mit niedriger Oktanzahl kann beim Beschleunigen klopfende Verbrennung auslösen. Sie klingt meist leichter und metallischer als mechanisches Klopfen und bessert sich mit besserem Sprit.' },
      ],
    },
    {
      key: 'rattling',
      slug: 'motor-rasselt',
      navLabel: 'Motor rasselt',
      cardDesc: 'Ein loses, metallisches Rasseln – oft Motorlager, Hitzeschutzblech oder Steuerkette.',
      metaTitle: 'Motor rasselt oder klappert — Kostenlose KI-Diagnose | Naira Autos',
      metaDescription: 'Rasseln oder Klappern aus dem Motorraum? Geräusch aufnehmen und eine KI-Diagnose erhalten: Hitzeschutzblech, Motorlager, Steuerkette und mehr. Kostenlos.',
      keywords: ['Motor rasselt', 'Motor klappert', 'Rasseln beim Kaltstart', 'Steuerkette rasselt', 'Auto rasselt im Leerlauf', 'Hitzeschutzblech klappert', 'Auspuff klappert'],
      h1a: 'Analyse:',
      h1b: 'Motor rasselt',
      intro: 'Ein metallisches Rasseln kann eine lockere Schraube sein – oder die Steuerkette. Nimm es auf und finde heraus, was dahintersteckt.',
      schemaDescription: 'Kostenloses KI-Tool, das Rasseln oder Klappern des Motors anhand einer Audioaufnahme diagnostiziert.',
      sections: [
        {
          h2: 'Warum rasselt der Motor?',
          paras: [
            'Rasseln ist ein loses, metallisches Geräusch, als würden Teile gegeneinander schlagen. Häufige Ursachen sind ein loses Hitzeschutzblech an der Abgasanlage, verschlissene Motor- oder Auspuffaufhängungen, lockere Schrauben oder Halter und – in ernsteren Fällen – die Steuerkette oder ihr Spanner.',
            'Entscheidend ist, wann das Geräusch auftritt: im Leerlauf, beim Beschleunigen, kalt oder nur über Bodenwellen. Das hilft, ein harmloses loses Teil von einem Steuerkettenproblem zu unterscheiden.',
          ],
        },
        {
          h2: 'Rasseln beim Kaltstart: Wann ist es bedenklich?',
          paras: [
            'Ein kurzes Rasseln beim Kaltstart, das nur wenige Sekunden dauert, kann von der Steuerkette oder einem Spanner kommen, dem Öldruck fehlt. Tritt es jedes Mal auf oder wird es schlimmer, ignoriere es nicht: Eine geschädigte Steuerkette kann in einem sehr teuren Schaden enden.',
          ],
        },
        {
          h2: 'Was du selbst prüfen kannst',
          paras: [
            'Prüfe bei abgestelltem, kaltem Motor, ob Hitzeschutzbleche und Halter der Abgasanlage fest sitzen, und suche nach lockeren Schrauben im Motorraum. Ändert sich das Geräusch mit der Drehzahl oder tritt es nur über Bodenwellen auf, notiere das im Beschreibungsfeld – ein wertvoller Hinweis.',
          ],
        },
      ],
      exampleTitle: 'Beispiel: Ein loses Hitzeschutzblech',
      exampleText: 'Der Audi A3 von Sabine rasselte bei bestimmten Drehzahlen, und sie fürchtete einen Steuerkettenschaden. Sie nahm das Geräusch auf, und das Tool ordnete es einem losen Teil unter dem Auto zu, nicht dem Motor. Die Werkstatt fand ein Hitzeschutzblech am Auspuff mit gelockerter Schraube und zog sie in Minuten fest.',
      reviewedAfter: ', Kfz-Mechaniker. Ursachen für Rasseln auf Werkstattpraxis abgestimmt.',
      faqTitle: 'FAQ: Motor rasselt',
      faqs: [
        { q: 'Warum rasselt mein Auto im Motorraum?', a: 'Meist ein loses Hitzeschutzblech oder ein lockerer Halter; auch verschlissene Aufhängungen oder seltener die Steuerkette kommen infrage.' },
        { q: 'Ist Rasseln beim Kaltstart schlimm?', a: 'Kommt drauf an. Dauert es nur wenige Sekunden und kommt nicht wieder, ist es meist harmlos; ist es dauerhaft oder wird schlimmer, kann es die Steuerkette sein und sollte geprüft werden.' },
        { q: 'Wie unterscheide ich Auspuff- von Motorrasseln?', a: 'Auspuffrasseln ändert sich oft mit der Drehzahl und ist unter dem Auto zu hören; Motorrasseln kommt aus dem Motorraum.' },
        { q: 'Kann ich weiterfahren?', a: 'Bei einem losen Teil und leichtem Geräusch meist kurzzeitig ja. Bei Verdacht auf die Steuerkette lieber nicht fahren und eine Werkstatt aufsuchen.' },
      ],
    },
  ],
  ui: {
    record: 'Geräusch aufnehmen',
    upload: 'Clip hochladen',
    stop: 'Stopp',
    descPlaceholder: 'Optional: Wann tritt es auf? (z. B. nur beim Kaltstart, nur beim Lenken)',
    brand: 'Marke (optional)',
    model: 'Modell',
    year: 'Baujahr',
    analyse: 'Dieses Geräusch analysieren',
    analysing: 'Geräusch wird analysiert...',
    listening: 'Deine Aufnahme wird angehört...',
    another: 'Weiteres Geräusch analysieren',
    noticeTrimmed: 'Dieser Clip ist {duration} s lang; in der kostenlosen Version analysieren wir nur die ersten {cap} s. Längere Clips kommen als Bezahloption.',
    noticeLong: 'Dieser Clip ist {duration} s lang. Wir empfehlen, ihn vor dem Hochladen auf {cap} s oder weniger zu kürzen.',
    noticeCapped: 'Die Aufnahme wurde in der kostenlosen Version auf {cap} s begrenzt – das reicht meist für eine klare Probe. Längere Clips kommen als Bezahloption.',
    footnote: 'Die kostenlose Version analysiert die ersten {cap} Sekunden jedes Clips. Die KI-Diagnose ist nicht immer zu 100 % richtig – sieh sie als Ausgangspunkt, nicht als endgültige Antwort. Bei Bremse, Lenkung oder Kraftstoffsystem: nicht weiterfahren und eine Werkstatt aufsuchen.',
    disclaimer: 'KI-generierte Diagnose auf Basis der ersten {cap} Sekunden Audio. Sie ist nicht immer zu 100 % richtig und kann Dinge übersehen, die eine Prüfung vor Ort finden würde. Sieh sie als Ausgangspunkt, nicht als endgültige Antwort. Bei Bremse, Lenkung oder Kraftstoffsystem: nicht weiterfahren und eine qualifizierte Werkstatt aufsuchen.',
    urgency: { safe: 'Fahrbereit', monitor: 'Genau beobachten', urgent: 'Bald zur Werkstatt', stop_driving: 'Sofort anhalten' },
    prob: { high: 'Hoch', medium: 'Mittel', low: 'Niedrig' },
    priority: { immediate: 'Sofort', soon: 'Bald', when_convenient: 'Bei Gelegenheit' },
    diy: 'Selbst',
    possibleCauses: 'Mögliche Ursachen',
    mostLikelyCause: 'Wahrscheinlichste Ursache',
    whatToDo: 'Was zu tun ist',
    betterDiagnosis: 'Für eine bessere Diagnose zusätzlich versuchen',
    partsToInspect: 'Zu prüfende Bauteile',
    costEstimate: 'Geschätzte Reparaturkosten',
    confidence: 'Sicherheit',
    costFrom: 'Ab {amount}',
    costUpTo: 'Bis zu {amount}',
    errors: {
      generic: 'Analyse fehlgeschlagen. Bitte erneut versuchen.',
      maxFile: 'Maximale Dateigröße: 20 MB.',
      mic: 'Mikrofonzugriff verweigert. Bitte Zugriff erlauben und erneut versuchen.',
      no_audio: 'Bitte eine Aufnahme des Geräuschs bereitstellen.',
      too_large: 'Die Audiodatei ist zu groß. Bitte Clips unter 8 MB (ca. 30 Sekunden) verwenden.',
      unavailable: 'Der KI-Dienst ist vorübergehend nicht verfügbar. Bitte gleich noch einmal versuchen.',
      parse: 'Die KI-Antwort konnte nicht verarbeitet werden. Bitte erneut versuchen.',
      server: 'Etwas ist schiefgelaufen. Bitte erneut versuchen.',
    },
  },
};
