import type { EngineSoundUi } from './types';

export const EN_UI: EngineSoundUi = {
  record: 'Record sound',
  upload: 'Upload clip',
  stop: 'Stop',
  descPlaceholder: 'Optional: when does it happen? (e.g. only on cold start, only when turning)',
  brand: 'Brand (optional)',
  model: 'Model',
  year: 'Year',
  analyse: 'Analyse this sound',
  analysing: 'Analysing sound...',
  listening: 'Listening to your recording...',
  another: 'Analyse another sound',
  noticeTrimmed: "This clip is {duration}s long — on the free tier we'll only analyse the first {cap}s. Longer clips are coming as a paid option.",
  noticeLong: 'This clip is {duration}s long. We recommend trimming it to {cap}s or less before uploading.',
  noticeCapped: "Recording capped at {cap}s on the free tier — that's usually enough for a clear sound sample. Longer clips are coming as a paid option.",
  footnote: "Free tier analyses the first {cap} seconds of any clip. AI diagnosis isn't always 100% accurate — treat it as a starting point, not a final answer. For brakes, steering, or fuel issues, stop driving and see a mechanic regardless of what this says.",
  disclaimer: "AI-generated diagnosis based on the first {cap} seconds of audio — it isn't always 100% accurate and can miss things a hands-on inspection would catch. Use it as a starting point, not a final answer. For brakes, steering, or fuel issues, stop driving and see a qualified mechanic regardless of what this says.",
  urgency: { safe: 'Safe to Drive', monitor: 'Monitor Closely', urgent: 'See a Mechanic Soon', stop_driving: 'Stop Driving Immediately' },
  prob: { high: 'High', medium: 'Medium', low: 'Low' },
  priority: { immediate: 'Do Now', soon: 'Do Soon', when_convenient: 'When Free' },
  diy: 'DIY',
  possibleCauses: 'Possible causes',
  mostLikelyCause: 'Most likely cause',
  whatToDo: 'What to do',
  betterDiagnosis: 'For a better diagnosis, also try',
  partsToInspect: 'Parts to inspect',
  costEstimate: 'Repair cost estimate',
  confidence: 'Confidence',
  costFrom: 'From {amount}',
  costUpTo: 'Up to {amount}',
  errors: {
    generic: 'Failed to analyse. Please try again.',
    maxFile: 'Max file size 20MB.',
    mic: 'Microphone access denied. Please allow microphone access and try again.',
    no_audio: 'Please provide an audio recording of the sound.',
    too_large: 'Audio file is too large. Please keep clips under 8MB (roughly 30 seconds).',
    unavailable: 'AI service is temporarily unavailable. Please try again in a moment.',
    parse: 'Failed to parse AI response. Please try again.',
    server: 'Something went wrong. Please try again.',
  },
};
