import type { EngineSoundCopy } from './types';

// Spanish — search-term research: people search "ruido del motor",
// "golpeteo del motor" (knocking), "traqueteo" (rattling) and
// "tic-tic / chasquido / taqués" (ticking); "qué significa el ruido del motor"
// and "cómo suena un motor averiado" are the common question forms.
export const es: EngineSoundCopy = {
  lang: 'es',
  locale: 'es_ES',
  dir: 'ltr',
  homeHref: '/inicio',
  homeLabel: 'Inicio',
  hubHref: '/herramientas',
  hubLabel: 'Herramientas',
  backLabel: 'Volver a herramientas',
  slug: 'analizador-de-ruidos-del-motor',
  metaTitle: 'Analizador de Ruidos del Motor — Diagnóstico Gratis con IA | Naira Autos',
  metaDescription: 'Graba o sube el ruido de tu motor y obtén al instante un diagnóstico con IA de la causa probable: tic-tic, golpeteo, traqueteo y más. Gratis y sin registro.',
  keywords: ['ruido del motor', 'ruidos del motor y sus causas', 'qué significa el ruido del motor', 'cómo suena un motor averiado', 'golpeteo del motor', 'traqueteo del motor', 'ruido tic-tic del motor', 'analizador de ruidos del motor', 'diagnóstico de ruido del motor con IA'],
  ogDescription: 'Graba o sube el ruido de tu motor y obtén al instante un diagnóstico con IA de la causa probable.',
  toolName: 'Analizador de Ruidos del Motor',
  schemaDescription: 'Herramienta gratuita con IA que diagnostica averías del coche a partir de una grabación del ruido del motor.',
  badge: 'Herramienta gratis',
  verified: 'Última revisión: septiembre de 2026',
  h1a: 'Analizador de',
  h1b: 'Ruidos del Motor',
  intro: 'Graba o sube el ruido que hace tu coche y recibe al instante un diagnóstico con IA: causas probables, qué tan urgente es y cuánto podría costar la reparación.',
  pickerEyebrow: '¿Qué ruido estás escuchando?',
  pickerTitle: 'Elige el más parecido',
  pickerCta: 'Diagnosticar este ruido →',
  pickerNote: '¿No sabes cuál se parece más? El grabador de arriba analiza cualquier ruido del motor; no hace falta elegir una categoría antes.',
  sections: [
    {
      h2: '¿Qué es un analizador de ruidos del motor?',
      paras: [
        'Un mecánico con experiencia suele saber qué le pasa a un coche solo con oír el motor, incluso antes de abrir el capó. Esta herramienta hace lo mismo con inteligencia artificial: grabas o subes un audio del ruido que hace tu coche y la IA identifica la causa más probable, igual que lo haría un mecánico de oído.',
        'Sirve para cualquier ruido raro del motor, no solo los tres de arriba: silbidos, chirridos, zumbidos, rechinidos o clics. Si puedes grabarlo, la IA puede intentar diagnosticarlo. Añade una breve descripción (por ejemplo, "solo en frío") y la marca y el modelo para afinar el resultado.',
      ],
    },
    {
      h2: 'Por qué conviene tomarse en serio el ruido del motor',
      paras: [
        'Un ruido nuevo casi nunca aparece porque sí. Un tic-tic, un golpeteo o un traqueteo suele indicar que algo ha cambiado: una pieza que se desgasta, un nivel de aceite bajo o un componente que se ha aflojado. Algunos sonidos son inofensivos, pero otros avisan de averías que empeoran rápido, como el golpeteo de bielas.',
        'Grabar el ruido y obtener una primera opinión no cuesta nada y lleva menos de un minuto. Suele salir mucho más barato que esperar a que un problema pequeño se convierta en una reparación grande.',
      ],
    },
    {
      h2: 'Cómo se diferencia de buscar el síntoma en un foro',
      paras: [
        'Al buscar un síntoma en internet suele aparecer una lista larga y genérica de todo lo que podría causar ese ruido. Sirve para informarse, pero no para saber qué le pasa a tu coche. Aquí el análisis parte de tu propio audio y de los datos que aportes, y te dice qué causas son más probables y qué tan urgente es.',
        'Eso sí, no sustituye una revisión en el taller. Es un primer paso rápido y gratuito para saber si puedes seguir conduciendo y qué revisar o preguntar al mecánico antes de gastar dinero en una suposición.',
      ],
    },
  ],
  tipsTitle: 'Consejos para grabar un audio que se pueda diagnosticar',
  tips: [
    'Acércate al origen del ruido con seguridad: junto al motor para sonidos del motor, junto a una rueda si sospechas de frenos o suspensión.',
    'Apaga la radio y cierra las ventanillas para que el viento y el tráfico no tapen el sonido.',
    'Graba cuando el ruido se oiga mejor: en el arranque en frío para tic-tic de taqués, al acelerar para golpeteos o al pasar un bache para traqueteos.',
    'Anota cuándo ocurre (solo en frío, solo al girar, solo con carga): el campo de descripción ayuda a la IA a acotar el diagnóstico.',
  ],
  exampleTitle: 'Ejemplo: un tic-tic en frío que no era grave',
  exampleText: 'El Toyota Corolla de Marcos empezó a hacer tic-tic cada mañana al arrancar y el ruido desaparecía a los dos minutos, cuando el motor se calentaba. Preocupado por si eran los cojinetes, grabó 15 segundos y los pasó por esta herramienta. El patrón del sonido apuntaba a los taqués hidráulicos con el aceite aún frío y no a un problema de bielas. Revisó el nivel, vio que estaba bajo, hizo el cambio de aceite y el ruido se fue.',
  reviewedBefore: 'Revisado por',
  reviewedAfter: ', mecánico automotriz. Categorías de ruido comprobadas para que coincidan con la práctica de taller.',
  faqTitle: 'Preguntas frecuentes sobre el analizador de ruidos del motor',
  faqs: [
    { q: '¿Qué es un analizador de ruidos del motor?', a: 'Una herramienta que escucha la grabación del ruido de tu motor e identifica la causa probable con IA, como hace un mecánico de oído antes de abrir el capó.' },
    { q: '¿Qué ruidos del motor puede diagnosticar?', a: 'Tic-tic, golpeteo, traqueteo, chirridos, rechinidos, zumbidos y la mayoría de los ruidos inusuales. Si puedes grabarlo, la IA puede intentar un diagnóstico.' },
    { q: '¿Cuánto debe durar la grabación?', a: 'La versión gratuita analiza los primeros 30 segundos del audio, que normalmente bastan para un diagnóstico claro.' },
    { q: '¿El diagnóstico siempre es correcto?', a: 'No. Es un buen punto de partida, no una respuesta definitiva, y puede pasar por alto lo que solo detecta una revisión en persona. Si el ruido tiene que ver con frenos, dirección o combustible, deja de conducir y acude al taller.' },
    { q: '¿Es gratis?', a: 'Sí, es gratis y sin registro. Más adelante habrá una opción de pago para grabaciones de más de 30 segundos.' },
  ],
  relatedTitle: 'Más herramientas gratis',
  relatedLabels: { mechanic: 'Mecánico Virtual', value: '¿Cuánto vale mi auto?', vin: 'Decodificador de VIN' },
  subs: [
    {
      key: 'ticking',
      slug: 'ruido-tic-tic-del-motor',
      navLabel: 'Ruido tic-tic',
      cardDesc: 'Un golpecito ligero y rápido, tic-tic-tic: suele venir de taqués, inyectores o de la distribución.',
      metaTitle: 'Ruido Tic-Tic del Motor — Diagnóstico Gratis con IA | Naira Autos',
      metaDescription: '¿Tu motor hace tic-tic o chasquidos? Graba el ruido y obtén un diagnóstico con IA: taqués, inyectores, falta de aceite y más. Gratis y sin registro.',
      keywords: ['ruido tic-tic del motor', 'ruido de chasquido en el motor', 'motor hace tic tic', 'taqués ruidosos', 'ruido de taqués al arrancar en frío', 'motor hace ruido al arrancar', 'chasquido del motor al acelerar'],
      h1a: 'Analizador del',
      h1b: 'Ruido Tic-Tic',
      intro: 'Un tic-tic ligero y repetitivo tiene solución muchas veces sencilla. Grábalo y averigua si es cuestión de aceite o de algo más serio.',
      schemaDescription: 'Herramienta gratuita con IA que diagnostica el ruido tic-tic del motor a partir de una grabación.',
      sections: [
        {
          h2: '¿Qué causa el ruido tic-tic del motor?',
          paras: [
            'Un tic-tic es un ruido metálico ligero y rápido que sigue el ritmo del motor. Las causas más habituales son los taqués hidráulicos o las válvulas con holgura, un nivel de aceite bajo o aceite en mal estado, inyectores que chasquean (algo normal hasta cierto punto) y, con menos frecuencia, una cadena de distribución o un tensor desgastados.',
            'El momento en que aparece es una pista clave: un tic-tic que desaparece al calentar el motor suele ser menos grave que uno que sigue igual o crece con las revoluciones.',
          ],
        },
        {
          h2: 'Tic-tic solo en frío: ¿es grave?',
          paras: [
            'Muchos motores hacen un tic-tic breve al arrancar en frío porque el aceite tarda unos segundos en llegar a los taqués. Si se va en uno o dos minutos y el nivel de aceite es correcto, normalmente no es preocupante, aunque conviene vigilarlo.',
            'Si el ruido persiste con el motor caliente, empeora con el tiempo o va acompañado de pérdida de potencia o testigo de aceite, no lo dejes: revisa el nivel de inmediato y pide que lo mire un mecánico.',
          ],
        },
        {
          h2: 'Qué revisar antes de ir al taller',
          paras: [
            'Comprueba el nivel de aceite con el motor frío y en plano, y mira si el aceite está muy oscuro o espeso. Fíjate en si el ruido cambia con las revoluciones: si acelera al ritmo del motor, viene de la parte superior del motor; si sigue la velocidad del coche, puede ser de otro origen.',
          ],
        },
      ],
      exampleTitle: 'Ejemplo: tic-tic que se arregló con aceite',
      exampleText: 'Lucía notó un tic-tic constante en su Kia Rio después de varios meses sin revisar el aceite. Grabó el sonido, la herramienta apuntó a lubricación insuficiente en la parte alta del motor y le sugirió comprobar el nivel antes que nada. Estaba casi en el mínimo; tras el cambio de aceite y filtro, el ruido desapareció.',
      reviewedAfter: ', mecánico automotriz. Causas del tic-tic comprobadas para que coincidan con la práctica de taller.',
      faqTitle: 'Preguntas frecuentes sobre el ruido tic-tic del motor',
      faqs: [
        { q: '¿Por qué mi motor hace tic-tic?', a: 'Lo más habitual es falta de aceite o aceite degradado que afecta a taqués y válvulas; también pueden ser inyectores, la cadena de distribución o un componente suelto.' },
        { q: '¿Es normal que haga tic-tic al arrancar en frío?', a: 'Un tic-tic breve que desaparece al calentar suele ser normal en muchos motores. Si dura más o vuelve, revisa el aceite.' },
        { q: '¿Puedo seguir conduciendo con este ruido?', a: 'Si el nivel de aceite es correcto y el ruido es leve, normalmente sí durante poco tiempo, pero hazlo revisar pronto. Si hay testigo de aceite o pierde potencia, detente.' },
        { q: '¿Qué son los taqués?', a: 'Son piezas que transmiten el movimiento del árbol de levas a las válvulas. Si se lubrican mal o se desgastan, hacen un tic-tic característico.' },
      ],
    },
    {
      key: 'knocking',
      slug: 'golpeteo-del-motor',
      navLabel: 'Golpeteo del motor',
      cardDesc: 'Un golpe más grave y pesado: puede deberse al combustible o a un problema serio de cojinetes.',
      metaTitle: 'Golpeteo del Motor — Diagnóstico Gratis con IA | Naira Autos',
      metaDescription: '¿Golpeteo en el motor? Graba el ruido y obtén un diagnóstico con IA: golpeteo de bielas, detonación, inyectores y más. Gratis y sin registro.',
      keywords: ['golpeteo del motor', 'motor golpetea al acelerar', 'golpeteo de bielas', 'ruido de golpeteo en el motor', 'motor diésel golpetea', 'cascabeleo del motor', 'detonación del motor'],
      h1a: 'Analizador del',
      h1b: 'Golpeteo del Motor',
      intro: 'Un golpeteo grave y pesado hay que tomarlo en serio. Grábalo y averigua si es cosa del combustible o algo más mecánico.',
      schemaDescription: 'Herramienta gratuita con IA que diagnostica el golpeteo del motor a partir de una grabación.',
      sections: [
        {
          h2: '¿Qué causa el golpeteo del motor?',
          paras: [
            'El golpeteo es un escalón por encima del tic-tic: es más grave, más pesado y suele aumentar con la carga o las revoluciones. Las causas principales son la detonación (combustible que se enciende de forma irregular por bajo octanaje o carbonilla), cojinetes de biela o de bancada desgastados, un inyector diésel defectuoso o un accesorio flojo, como la polea del alternador.',
            'El momento importa mucho: un golpeteo que aparece justo después de repostar apunta al combustible; uno que crece poco a poco durante semanas, sin relación con el combustible, apunta más al desgaste de cojinetes.',
          ],
        },
        {
          h2: 'Golpeteo de bielas: el que hay que tomar en serio',
          paras: [
            'El golpeteo de bielas es un golpe grave y rítmico causado por holgura excesiva en un cojinete de biela desgastado. Suele sonar más fuerte al subir de revoluciones y a veces se nota más con carga que al ralentí. A diferencia del golpeteo por combustible, no mejora al cambiar de gasolina, y seguir conduciendo puede terminar en una avería grave del motor.',
          ],
        },
        {
          h2: '¿Puede el mal combustible causar golpeteo?',
          paras: [
            'Sí. Usar gasolina con menos octanaje del que pide el motor puede provocar detonación, que se percibe como un cascabeleo metálico al acelerar. Suele ser más ligero que un golpeteo mecánico y muchas veces desaparece al repostar con mejor combustible o al limpiar el sistema de inyección.',
          ],
        },
        {
          h2: 'Golpeteo en motores diésel',
          paras: [
            'Los diésel son por naturaleza más ruidosos que los de gasolina, así que un golpeteo nuevo cuesta más de notar, pero conviene prestarle atención en cuanto lo detectes. Si es un golpeteo nuevo o que va a más, una causa frecuente son los inyectores. Grábalo y compáralo con el sonido habitual de tu motor.',
          ],
        },
      ],
      exampleTitle: 'Ejemplo: era el combustible, no las bielas',
      exampleText: 'El Hyundai Elantra de Andrés empezó a golpetear al acelerar justo después de repostar en una gasolinera que no conocía. Con el kilometraje que tenía temía un problema de bielas y grabó el sonido antes de gastar en un diagnóstico. El patrón encajaba con detonación por combustible; al llenar el depósito con gasolina de mayor octanaje, el golpeteo desapareció.',
      reviewedAfter: ', mecánico automotriz. Tipos y causas del golpeteo comprobados para que coincidan con la práctica de taller.',
      faqTitle: 'Preguntas frecuentes sobre el golpeteo del motor',
      faqs: [
        { q: '¿Por qué golpetea mi motor al acelerar?', a: 'Detonación por combustible de bajo octanaje, cojinetes de biela desgastados, un inyector diésel defectuoso o un accesorio flojo. Cuándo aparece es una pista importante.' },
        { q: '¿El golpeteo del motor siempre es grave?', a: 'No siempre, pero merece más precaución que un tic-tic. El del combustible suele ser manejable; el de bielas es un problema mecánico real que empeora.' },
        { q: '¿Qué es el golpeteo de bielas?', a: 'Un golpe grave y rítmico por holgura en un cojinete de biela desgastado. Sube con las revoluciones, no mejora con otro combustible y daña más el motor cuanto más se conduce.' },
        { q: '¿Por qué golpetea mi motor diésel?', a: 'Los diésel son más ruidosos por diseño, pero un golpeteo nuevo o creciente suele apuntar a los inyectores.' },
        { q: '¿El mal combustible puede causar golpeteo?', a: 'Sí, la gasolina de bajo octanaje puede provocar detonación al acelerar. Suele ser más ligero y metálico que un golpeteo mecánico y mejora con mejor combustible.' },
      ],
    },
    {
      key: 'rattling',
      slug: 'traqueteo-del-motor',
      navLabel: 'Traqueteo del motor',
      cardDesc: 'Un traqueteo metálico y suelto: suele venir de un soporte, una pantalla térmica o la distribución.',
      metaTitle: 'Traqueteo del Motor — Diagnóstico Gratis con IA | Naira Autos',
      metaDescription: '¿Traqueteo bajo el capó? Graba el ruido y obtén un diagnóstico con IA: pantalla térmica, soportes, distribución y más. Gratis y sin registro.',
      keywords: ['traqueteo del motor', 'ruido de traqueteo bajo el capó', 'motor hace ruido de cascabel', 'ruido de latas en el coche', 'traqueteo al arrancar', 'ruido metálico en el motor', 'traqueteo del escape'],
      h1a: 'Analizador del',
      h1b: 'Traqueteo del Motor',
      intro: 'Un traqueteo metálico suelto puede ser desde un tornillo flojo hasta la distribución. Grábalo y averigua qué es.',
      schemaDescription: 'Herramienta gratuita con IA que diagnostica el traqueteo del motor a partir de una grabación.',
      sections: [
        {
          h2: '¿Qué causa el traqueteo del motor?',
          paras: [
            'El traqueteo es un ruido metálico y suelto, como de piezas que vibran entre sí. Las causas más comunes son una pantalla térmica del escape floja, soportes del motor o del escape desgastados, tornillos o fijaciones sueltas y, en casos más serios, la cadena de distribución o su tensor.',
            'La clave está en cuándo suena: al ralentí, al acelerar, en frío o solo al pasar baches. Ese dato ayuda a distinguir entre algo suelto sin importancia y un problema de distribución.',
          ],
        },
        {
          h2: 'Traqueteo en el arranque: cuándo preocuparse',
          paras: [
            'Un traqueteo breve en el arranque en frío que dura solo unos segundos puede venir de la cadena de distribución o de un tensor con poca presión de aceite. Si se repite cada vez o va a más, no lo ignores: una cadena de distribución dañada puede acabar en una avería muy costosa.',
          ],
        },
        {
          h2: 'Qué revisar tú mismo',
          paras: [
            'Con el motor apagado y frío, comprueba que las pantallas térmicas y las fijaciones del escape no bailen y mira si hay tornillos flojos bajo el capó. Si el ruido cambia con las revoluciones o solo aparece al pasar baches, es una pista útil que puedes anotar en el campo de descripción.',
          ],
        },
      ],
      exampleTitle: 'Ejemplo: una pantalla térmica floja',
      exampleText: 'La Honda CR-V de Carmen hacía un traqueteo metálico a ciertas revoluciones que la tenía preocupada por la distribución. Grabó el sonido y la herramienta lo relacionó con una pieza suelta bajo el coche y no con el motor. Un mecánico encontró una pantalla térmica del escape con un tornillo flojo y lo arregló en minutos.',
      reviewedAfter: ', mecánico automotriz. Causas del traqueteo comprobadas para que coincidan con la práctica de taller.',
      faqTitle: 'Preguntas frecuentes sobre el traqueteo del motor',
      faqs: [
        { q: '¿Por qué mi coche hace un traqueteo bajo el capó?', a: 'Lo más habitual es una pantalla térmica o una fijación floja; también pueden ser soportes desgastados o, más raramente, la distribución.' },
        { q: '¿Es grave un traqueteo en el arranque?', a: 'Depende. Si dura pocos segundos y no se repite, suele ser menor; si es constante o va a más, puede ser la cadena de distribución y hay que revisarlo.' },
        { q: '¿Cómo distingo un traqueteo del escape?', a: 'El del escape suele cambiar con las revoluciones y se oye más bajo el coche; el del motor se oye desde el compartimento del motor.' },
        { q: '¿Puedo seguir conduciendo?', a: 'Si es una pieza suelta y el ruido es leve, normalmente sí durante poco tiempo. Si sospechas de la distribución, evita conducir y consulta a un mecánico.' },
      ],
    },
  ],
  ui: {
    record: 'Grabar sonido',
    upload: 'Subir audio',
    stop: 'Detener',
    descPlaceholder: 'Opcional: ¿cuándo ocurre? (p. ej., solo en frío, solo al girar)',
    brand: 'Marca (opcional)',
    model: 'Modelo',
    year: 'Año',
    analyse: 'Analizar este sonido',
    analysing: 'Analizando el sonido...',
    listening: 'Escuchando tu grabación...',
    another: 'Analizar otro sonido',
    noticeTrimmed: 'Este audio dura {duration} s; en la versión gratuita solo analizamos los primeros {cap} s. Los audios más largos llegarán como opción de pago.',
    noticeLong: 'Este audio dura {duration} s. Te recomendamos recortarlo a {cap} s o menos antes de subirlo.',
    noticeCapped: 'La grabación se limitó a {cap} s en la versión gratuita; suele bastar para una muestra clara. Los audios más largos llegarán como opción de pago.',
    footnote: 'La versión gratuita analiza los primeros {cap} segundos de cada audio. El diagnóstico con IA no siempre es 100 % exacto: úsalo como punto de partida, no como respuesta final. Si se trata de frenos, dirección o combustible, deja de conducir y acude a un mecánico.',
    disclaimer: 'Diagnóstico generado por IA a partir de los primeros {cap} segundos de audio. No siempre es 100 % exacto y puede pasar por alto lo que detectaría una revisión en persona. Úsalo como punto de partida, no como respuesta final. Si se trata de frenos, dirección o combustible, deja de conducir y acude a un mecánico.',
    urgency: { safe: 'Puedes conducir', monitor: 'Vigílalo de cerca', urgent: 'Ve al mecánico pronto', stop_driving: 'Deja de conducir ya' },
    prob: { high: 'Alta', medium: 'Media', low: 'Baja' },
    priority: { immediate: 'Ahora', soon: 'Pronto', when_convenient: 'Sin prisa' },
    diy: 'Tú mismo',
    possibleCauses: 'Causas posibles',
    mostLikelyCause: 'Causa más probable',
    whatToDo: 'Qué hacer',
    betterDiagnosis: 'Para afinar el diagnóstico, prueba también',
    partsToInspect: 'Piezas a revisar',
    costEstimate: 'Coste estimado de la reparación',
    confidence: 'Confianza',
    costFrom: 'Desde {amount}',
    costUpTo: 'Hasta {amount}',
    errors: {
      generic: 'No se pudo analizar. Inténtalo de nuevo.',
      maxFile: 'Tamaño máximo del archivo: 20 MB.',
      mic: 'Acceso al micrófono denegado. Permite el acceso e inténtalo de nuevo.',
      no_audio: 'Adjunta una grabación del sonido.',
      too_large: 'El audio es demasiado grande. Usa clips de menos de 8 MB (unos 30 segundos).',
      unavailable: 'El servicio de IA no está disponible en este momento. Inténtalo de nuevo en unos instantes.',
      parse: 'No se pudo interpretar la respuesta de la IA. Inténtalo de nuevo.',
      server: 'Algo salió mal. Inténtalo de nuevo.',
    },
  },
};
