import type { EngineSoundCopy } from './types';

// French — search-term research: drivers search "bruit moteur", "cliquetis
// moteur" (ticking/tapping), "cognement moteur" (deep knock),
// "claquement moteur" / "bruit de ferraille" (rattling/slapping).
// Typographic apostrophes (’) are used throughout to avoid TS string escaping.
export const fr: EngineSoundCopy = {
  lang: 'fr',
  locale: 'fr_FR',
  dir: 'ltr',
  homeHref: '/accueil',
  homeLabel: 'Accueil',
  hubHref: '/outils',
  hubLabel: 'Outils',
  backLabel: 'Retour aux outils',
  slug: 'analyseur-de-bruit-moteur',
  metaTitle: 'Analyseur de Bruit Moteur — Diagnostic Gratuit par IA | Naira Autos',
  metaDescription: 'Enregistrez ou importez le bruit de votre moteur et obtenez un diagnostic IA immédiat de la cause probable : cliquetis, cognement, claquement, bruit de ferraille. Gratuit, sans inscription.',
  keywords: ['bruit moteur', 'bruit moteur voiture', 'cliquetis moteur', 'cognement moteur', 'claquement moteur', 'bruit de ferraille moteur', 'diagnostic bruit moteur', 'analyseur de bruit moteur', 'bruit anormal moteur causes'],
  ogDescription: 'Enregistrez ou importez le bruit de votre moteur et obtenez un diagnostic IA immédiat de la cause probable.',
  toolName: 'Analyseur de Bruit Moteur',
  schemaDescription: 'Outil gratuit par IA qui diagnostique les pannes d’une voiture à partir d’un enregistrement du bruit moteur.',
  badge: 'Outil gratuit',
  verified: 'Dernière vérification : septembre 2026',
  h1a: 'Analyseur de',
  h1b: 'Bruit Moteur',
  intro: 'Enregistrez ou importez le bruit que fait votre voiture et obtenez un diagnostic IA immédiat : causes probables, degré d’urgence et coût de réparation estimé.',
  pickerEyebrow: 'Quel bruit entendez-vous ?',
  pickerTitle: 'Choisissez le plus proche',
  pickerCta: 'Diagnostiquer ce bruit →',
  pickerNote: 'Vous ne savez pas lequel correspond ? L’enregistreur ci-dessus analyse n’importe quel bruit moteur : inutile de choisir une catégorie avant.',
  sections: [
    {
      h2: 'Qu’est-ce qu’un analyseur de bruit moteur ?',
      paras: [
        'Un mécanicien expérimenté devine souvent ce qui ne va pas rien qu’à l’oreille, avant même d’ouvrir le capot. Cet outil fait pareil avec l’IA : vous enregistrez ou importez un extrait du bruit de votre voiture, et l’IA identifie la cause la plus probable, comme un mécanicien qui diagnostique à l’oreille.',
        'Il fonctionne pour tout bruit moteur inhabituel, pas seulement les trois ci-dessus : sifflement, grincement, ronflement, claquement, cliquetis. Si vous pouvez l’enregistrer, l’IA peut tenter un diagnostic. Ajoutez une courte description (par exemple « seulement à froid ») ainsi que la marque et le modèle pour affiner le résultat.',
      ],
    },
    {
      h2: 'Pourquoi un bruit moteur ne doit pas être ignoré',
      paras: [
        'Un bruit moteur apparaît rarement sans raison. Un cliquetis, un cognement ou un bruit de ferraille indique presque toujours qu’un élément a changé : une pièce qui s’use, un niveau d’huile trop bas ou une fixation qui a pris du jeu. Certains bruits sont sans gravité, d’autres annoncent une panne qui s’aggrave vite, comme le cognement de bielle.',
        'Enregistrer le bruit et obtenir un premier avis ne coûte rien et prend moins d’une minute. C’est souvent bien moins cher que d’attendre qu’un petit défaut devienne une grosse réparation.',
      ],
    },
    {
      h2: 'Ce qui change par rapport à une recherche sur un forum',
      paras: [
        'Chercher un symptôme sur internet donne en général une longue liste générique de tout ce qui pourrait provoquer ce bruit : utile pour se renseigner, moins pour comprendre ce qui arrive à votre voiture. Ici, l’analyse part de votre propre enregistrement et des informations que vous ajoutez, et vous indique les causes les plus probables ainsi que l’urgence.',
        'Cela ne remplace pas un contrôle en atelier. Voyez-le comme une première étape rapide et gratuite pour savoir si vous pouvez continuer à rouler et quoi vérifier ou demander à votre garagiste avant de dépenser de l’argent sur une hypothèse.',
      ],
    },
  ],
  tipsTitle: 'Conseils pour un enregistrement exploitable',
  tips: [
    'Approchez-vous de la source du bruit en toute sécurité : près du bloc moteur pour un bruit moteur, près d’une roue pour les freins ou la suspension.',
    'Coupez la radio et fermez les vitres pour que le vent et la circulation ne couvrent pas le son.',
    'Enregistrez au moment où le bruit est le plus net : au démarrage à froid pour un cliquetis de poussoirs, en accélérant pour un cognement, sur un dos-d’âne pour un bruit de ferraille.',
    'Notez quand il apparaît (à froid seulement, en virage, en charge) : le champ de description aide l’IA à cibler le diagnostic.',
  ],
  exampleTitle: 'Exemple : un cliquetis à froid sans gravité',
  exampleText: 'La Renault Clio de Julien s’est mise à cliqueter chaque matin au démarrage, avant que le bruit disparaisse au bout de deux minutes, moteur chaud. Inquiet pour les coussinets, il a enregistré 15 secondes et les a passées dans cet outil. Le profil sonore évoquait des poussoirs hydrauliques avec une huile encore froide, pas un problème de bielle. Il a contrôlé le niveau : trop bas. Après la vidange, le bruit avait disparu.',
  reviewedBefore: 'Relu par',
  reviewedAfter: ', mécanicien automobile. Catégories de bruits vérifiées pour correspondre à la pratique en atelier.',
  faqTitle: 'FAQ de l’analyseur de bruit moteur',
  faqs: [
    { q: 'Qu’est-ce qu’un analyseur de bruit moteur ?', a: 'Un outil qui écoute l’enregistrement du bruit de votre moteur et identifie la cause probable grâce à l’IA, comme un mécanicien qui diagnostique à l’oreille avant d’ouvrir le capot.' },
    { q: 'Quels bruits moteur peut-il diagnostiquer ?', a: 'Cliquetis, cognement, claquement, bruit de ferraille, grincement, sifflement, ronflement et la plupart des bruits inhabituels. Si vous pouvez l’enregistrer, l’IA peut tenter un diagnostic.' },
    { q: 'Quelle durée pour l’enregistrement ?', a: 'La version gratuite analyse les 30 premières secondes de chaque extrait, ce qui suffit normalement pour un diagnostic clair.' },
    { q: 'Le diagnostic est-il toujours juste ?', a: 'Non. C’est un bon point de départ, pas une réponse définitive, et il peut passer à côté de ce qu’un contrôle sur place détecterait. Pour un bruit lié aux freins, à la direction ou au carburant, arrêtez de rouler et consultez un garage.' },
    { q: 'L’outil est-il gratuit ?', a: 'Oui, gratuit et sans inscription. Une option payante pour les enregistrements de plus de 30 secondes est prévue plus tard.' },
  ],
  relatedTitle: 'Plus d’outils gratuits',
  relatedLabels: { mechanic: 'Mécanicien Virtuel', value: 'Combien vaut ma voiture ?', vin: 'Décodeur VIN' },
  subs: [
    {
      key: 'ticking',
      slug: 'cliquetis-moteur',
      navLabel: 'Cliquetis moteur',
      cardDesc: 'Un tapotement léger et rapide, tic-tic-tic : souvent des poussoirs, des injecteurs ou la distribution.',
      metaTitle: 'Cliquetis Moteur — Diagnostic Gratuit par IA | Naira Autos',
      metaDescription: 'Cliquetis moteur ? Enregistrez le bruit et obtenez un diagnostic IA : poussoirs, manque d’huile, injecteurs et plus. Gratuit, sans inscription.',
      keywords: ['cliquetis moteur', 'bruit de cliquetis moteur', 'cliquetis moteur à froid', 'cliquetis moteur diesel', 'bruit de tic tic moteur', 'poussoirs hydrauliques bruit', 'cliquetis au démarrage'],
      h1a: 'Analyseur de',
      h1b: 'Cliquetis Moteur',
      intro: 'Un cliquetis léger et régulier a souvent une cause simple. Enregistrez-le et voyez s’il s’agit d’huile ou de quelque chose de plus sérieux.',
      schemaDescription: 'Outil gratuit par IA qui diagnostique le cliquetis moteur à partir d’un enregistrement audio.',
      sections: [
        {
          h2: 'Quelles sont les causes d’un cliquetis moteur ?',
          paras: [
            'Le cliquetis est un bruit métallique léger et rapide qui suit le rythme du moteur. Les causes les plus courantes : poussoirs hydrauliques ou jeu aux soupapes, niveau d’huile trop bas ou huile usée, injecteurs qui claquent (normal jusqu’à un certain point) et, plus rarement, chaîne de distribution ou tendeur usés.',
            'Le moment d’apparition est un indice clé : un cliquetis qui disparaît quand le moteur chauffe est en général moins grave qu’un bruit qui persiste ou augmente avec le régime.',
          ],
        },
        {
          h2: 'Cliquetis à froid seulement : est-ce grave ?',
          paras: [
            'Beaucoup de moteurs cliquettent brièvement à froid, le temps que l’huile atteigne les poussoirs. Si le bruit disparaît en une ou deux minutes et que le niveau d’huile est correct, il n’y a normalement pas d’inquiétude, mais surveillez-le.',
            'S’il persiste moteur chaud, s’aggrave avec le temps ou s’accompagne d’une perte de puissance ou du voyant d’huile, n’attendez pas : contrôlez le niveau tout de suite et faites examiner la voiture.',
          ],
        },
        {
          h2: 'Que vérifier avant d’aller au garage',
          paras: [
            'Contrôlez le niveau d’huile moteur froid, sur un sol plat, et regardez si l’huile est très noire ou épaisse. Observez si le bruit suit le régime moteur : s’il accélère avec le moteur, il vient du haut moteur ; s’il suit la vitesse du véhicule, l’origine est ailleurs.',
          ],
        },
      ],
      exampleTitle: 'Exemple : un cliquetis réglé par l’huile',
      exampleText: 'Camille a remarqué un cliquetis constant sur sa Peugeot 208 après plusieurs mois sans contrôler l’huile. Elle a enregistré le bruit ; l’outil a pointé un graissage insuffisant du haut moteur et conseillé de vérifier d’abord le niveau. Il était presque au minimum. Après vidange et changement de filtre, le bruit a disparu.',
      reviewedAfter: ', mécanicien automobile. Causes du cliquetis vérifiées pour correspondre à la pratique en atelier.',
      faqTitle: 'FAQ sur le cliquetis moteur',
      faqs: [
        { q: 'Pourquoi mon moteur cliquette-t-il ?', a: 'Le plus souvent, un manque d’huile ou une huile dégradée qui affecte poussoirs et soupapes ; ce peut aussi être les injecteurs, la chaîne de distribution ou une pièce desserrée.' },
        { q: 'Est-ce normal de cliqueter au démarrage à froid ?', a: 'Un cliquetis bref qui disparaît une fois le moteur chaud est courant sur beaucoup de moteurs. S’il dure ou revient, contrôlez l’huile.' },
        { q: 'Puis-je continuer à rouler avec ce bruit ?', a: 'Si le niveau d’huile est bon et le bruit léger, en général oui pour un temps court, mais faites vérifier bientôt. Voyant d’huile ou perte de puissance : arrêtez-vous.' },
        { q: 'Que sont les poussoirs hydrauliques ?', a: 'Des pièces qui transmettent le mouvement de l’arbre à cames aux soupapes. Mal lubrifiés ou usés, ils produisent un cliquetis caractéristique.' },
      ],
    },
    {
      key: 'knocking',
      slug: 'cognement-moteur',
      navLabel: 'Cognement moteur',
      cardDesc: 'Un choc plus grave et plus lourd : carburant en cause ou problème sérieux de coussinets.',
      metaTitle: 'Cognement Moteur — Diagnostic Gratuit par IA | Naira Autos',
      metaDescription: 'Cognement moteur ? Enregistrez le bruit et obtenez un diagnostic IA : cognement de bielle, cliquetis d’allumage, injecteurs et plus. Gratuit, sans inscription.',
      keywords: ['cognement moteur', 'bruit de cognement moteur', 'moteur qui cogne en accélérant', 'cognement de bielle', 'moteur diesel qui cogne', 'cliquetis moteur essence', 'auto-allumage moteur'],
      h1a: 'Analyseur de',
      h1b: 'Cognement Moteur',
      intro: 'Un choc grave et lourd est à prendre au sérieux. Enregistrez-le pour savoir s’il vient du carburant ou d’un défaut plus mécanique.',
      schemaDescription: 'Outil gratuit par IA qui diagnostique le cognement moteur à partir d’un enregistrement audio.',
      sections: [
        {
          h2: 'Quelles sont les causes d’un cognement moteur ?',
          paras: [
            'Un cognement est plus sérieux qu’un cliquetis : plus grave, plus lourd, et il augmente en général avec la charge ou le régime. Les causes principales : le cliquetis d’allumage (carburant qui s’enflamme de façon irrégulière à cause d’un indice d’octane trop bas ou de calamine), des coussinets de bielle ou de vilebrequin usés, un injecteur diesel défaillant ou un accessoire desserré comme la poulie d’alternateur.',
            'Le moment compte beaucoup : un cognement qui apparaît juste après un plein pointe vers le carburant ; un bruit qui s’installe progressivement sur des semaines, quel que soit le carburant, pointe plutôt vers l’usure des coussinets.',
          ],
        },
        {
          h2: 'Le cognement de bielle : celui qu’il faut prendre au sérieux',
          paras: [
            'Le cognement de bielle est un choc grave et rythmé causé par un jeu excessif dans un coussinet de bielle usé. Il devient plus fort quand le régime monte et s’entend parfois mieux en charge qu’au ralenti. Contrairement au cognement lié au carburant, il ne s’améliore pas en changeant d’essence, et continuer à rouler peut mener à une casse moteur.',
          ],
        },
        {
          h2: 'Un mauvais carburant peut-il faire cogner le moteur ?',
          paras: [
            'Oui. Rouler avec un carburant d’indice d’octane inférieur à celui demandé peut provoquer du cliquetis d’allumage, perçu comme un cliquetis métallique en accélération. Il est généralement plus léger qu’un cognement mécanique et disparaît souvent avec un meilleur carburant ou un nettoyage du circuit d’injection.',
          ],
        },
        {
          h2: 'Cognement sur un moteur diesel',
          paras: [
            'Un diesel est par nature plus bruyant qu’un essence : un nouveau cognement est donc plus difficile à repérer, mais mérite votre attention dès que vous le remarquez. S’il est récent ou s’aggrave, les injecteurs sont une cause fréquente. Enregistrez-le et comparez-le au bruit habituel de votre moteur.',
          ],
        },
      ],
      exampleTitle: 'Exemple : le carburant, pas la bielle',
      exampleText: 'La Hyundai i30 de Thomas s’est mise à cogner en accélérant juste après un plein dans une station inconnue. Vu le kilométrage, il craignait un problème de bielle et a enregistré le bruit avant de payer un diagnostic. Le profil correspondait à du cliquetis d’allumage lié au carburant ; après un plein d’un carburant à indice plus élevé, le cognement a disparu.',
      reviewedAfter: ', mécanicien automobile. Types et causes de cognement vérifiés pour correspondre à la pratique en atelier.',
      faqTitle: 'FAQ sur le cognement moteur',
      faqs: [
        { q: 'Pourquoi mon moteur cogne-t-il en accélérant ?', a: 'Cliquetis d’allumage dû à un carburant d’indice trop bas, coussinets de bielle usés, injecteur diesel défaillant ou accessoire desserré. Le moment d’apparition est un indice important.' },
        { q: 'Un cognement moteur est-il toujours grave ?', a: 'Pas toujours, mais il demande plus de prudence qu’un cliquetis. Celui du carburant est souvent gérable ; le cognement de bielle est un vrai problème mécanique qui s’aggrave.' },
        { q: 'Qu’est-ce que le cognement de bielle ?', a: 'Un choc grave et rythmé dû à un jeu dans un coussinet de bielle usé. Il monte avec le régime, ne s’améliore pas avec un autre carburant et endommage le moteur d’autant plus que vous roulez.' },
        { q: 'Pourquoi mon diesel cogne-t-il ?', a: 'Les diesels sont plus bruyants par conception, mais un cognement nouveau ou croissant vient souvent des injecteurs.' },
        { q: 'Un mauvais carburant peut-il causer un cognement ?', a: 'Oui, un carburant à faible indice d’octane peut provoquer du cliquetis d’allumage en accélération. Il est généralement plus léger et métallique qu’un cognement mécanique et s’améliore avec un meilleur carburant.' },
      ],
    },
    {
      key: 'rattling',
      slug: 'bruit-de-ferraille-moteur',
      navLabel: 'Bruit de ferraille',
      cardDesc: 'Un claquement métallique lâche : souvent un support, un écran thermique ou la distribution.',
      metaTitle: 'Bruit de Ferraille Moteur — Diagnostic Gratuit par IA | Naira Autos',
      metaDescription: 'Bruit de ferraille ou claquement sous le capot ? Enregistrez-le et obtenez un diagnostic IA : écran thermique, supports moteur, distribution et plus. Gratuit.',
      keywords: ['bruit de ferraille moteur', 'claquement moteur', 'bruit de ferraille sous le capot', 'bruit de ferraille au démarrage', 'bruit métallique moteur', 'ferraille échappement', 'chaîne de distribution bruit'],
      h1a: 'Analyseur de',
      h1b: 'Bruit de Ferraille',
      intro: 'Un bruit de ferraille peut être une simple vis desserrée comme un souci de distribution. Enregistrez-le et découvrez de quoi il s’agit.',
      schemaDescription: 'Outil gratuit par IA qui diagnostique un bruit de ferraille ou de claquement moteur à partir d’un enregistrement.',
      sections: [
        {
          h2: 'Quelles sont les causes d’un bruit de ferraille moteur ?',
          paras: [
            'Un bruit de ferraille est un son métallique lâche, comme des pièces qui vibrent l’une contre l’autre. Causes courantes : un écran thermique d’échappement desserré, des supports moteur ou d’échappement usés, des vis ou fixations desserrées et, dans les cas plus sérieux, la chaîne de distribution ou son tendeur.',
            'L’élément clé, c’est le moment : au ralenti, en accélérant, à froid ou seulement sur les bosses. Cela aide à distinguer une pièce desserrée sans importance d’un problème de distribution.',
          ],
        },
        {
          h2: 'Ferraille au démarrage : quand s’inquiéter ?',
          paras: [
            'Un bruit de ferraille bref au démarrage à froid, de quelques secondes, peut venir de la chaîne de distribution ou d’un tendeur manquant de pression d’huile. S’il revient à chaque fois ou s’aggrave, ne l’ignorez pas : une chaîne de distribution endommagée peut mener à une panne très coûteuse.',
          ],
        },
        {
          h2: 'Ce que vous pouvez vérifier vous-même',
          paras: [
            'Moteur coupé et froid, vérifiez que les écrans thermiques et les fixations d’échappement ne bougent pas et cherchez des vis desserrées sous le capot. Si le bruit varie avec le régime ou n’apparaît que sur les bosses, notez-le dans le champ de description : c’est un indice précieux.',
          ],
        },
      ],
      exampleTitle: 'Exemple : un écran thermique desserré',
      exampleText: 'La Honda CR-V de Nadia faisait un bruit de ferraille à certains régimes, ce qui l’inquiétait pour la distribution. Elle a enregistré le son et l’outil l’a relié à une pièce desserrée sous la voiture plutôt qu’au moteur. Le garagiste a trouvé un écran thermique d’échappement dont une vis avait pris du jeu et l’a resserré en quelques minutes.',
      reviewedAfter: ', mécanicien automobile. Causes du bruit de ferraille vérifiées pour correspondre à la pratique en atelier.',
      faqTitle: 'FAQ sur le bruit de ferraille moteur',
      faqs: [
        { q: 'Pourquoi ma voiture fait-elle un bruit de ferraille sous le capot ?', a: 'Le plus souvent un écran thermique ou une fixation desserrée ; ce peut aussi être des supports usés ou, plus rarement, la distribution.' },
        { q: 'Un bruit de ferraille au démarrage est-il grave ?', a: 'Cela dépend. S’il ne dure que quelques secondes et ne revient pas, c’est souvent mineur ; s’il est constant ou s’aggrave, ce peut être la chaîne de distribution et il faut la faire contrôler.' },
        { q: 'Comment distinguer la ferraille d’échappement de celle du moteur ?', a: 'Celle de l’échappement change souvent avec le régime et s’entend sous la voiture ; celle du moteur vient du compartiment moteur.' },
        { q: 'Puis-je continuer à rouler ?', a: 'Si c’est une pièce desserrée et que le bruit est léger, en général oui pour un temps court. Si vous soupçonnez la distribution, évitez de rouler et consultez un mécanicien.' },
      ],
    },
  ],
  ui: {
    record: 'Enregistrer le son',
    upload: 'Importer un extrait',
    stop: 'Arrêter',
    descPlaceholder: 'Facultatif : quand cela se produit-il ? (ex. seulement à froid, seulement en virage)',
    brand: 'Marque (facultatif)',
    model: 'Modèle',
    year: 'Année',
    analyse: 'Analyser ce son',
    analysing: 'Analyse du son en cours...',
    listening: 'Écoute de votre enregistrement...',
    another: 'Analyser un autre son',
    noticeTrimmed: 'Cet extrait dure {duration} s ; dans la version gratuite, seules les {cap} premières secondes sont analysées. Les extraits plus longs arriveront en option payante.',
    noticeLong: 'Cet extrait dure {duration} s. Nous vous conseillons de le couper à {cap} s ou moins avant l’import.',
    noticeCapped: 'L’enregistrement est limité à {cap} s dans la version gratuite, ce qui suffit en général pour un échantillon net. Les extraits plus longs arriveront en option payante.',
    footnote: 'La version gratuite analyse les {cap} premières secondes de chaque extrait. Le diagnostic par IA n’est pas toujours exact à 100 % : considérez-le comme un point de départ, pas une réponse définitive. Pour les freins, la direction ou le carburant, arrêtez de rouler et consultez un mécanicien.',
    disclaimer: 'Diagnostic généré par IA à partir des {cap} premières secondes d’audio. Il n’est pas toujours exact à 100 % et peut passer à côté de ce qu’un contrôle sur place détecterait. Considérez-le comme un point de départ, pas une réponse définitive. Pour les freins, la direction ou le carburant, arrêtez de rouler et consultez un mécanicien qualifié.',
    urgency: { safe: 'Roulage possible', monitor: 'À surveiller de près', urgent: 'Voir un garage rapidement', stop_driving: 'Arrêtez de rouler immédiatement' },
    prob: { high: 'Élevée', medium: 'Moyenne', low: 'Faible' },
    priority: { immediate: 'Maintenant', soon: 'Bientôt', when_convenient: 'Sans urgence' },
    diy: 'Vous-même',
    possibleCauses: 'Causes possibles',
    mostLikelyCause: 'Cause la plus probable',
    whatToDo: 'Que faire',
    betterDiagnosis: 'Pour affiner le diagnostic, essayez aussi',
    partsToInspect: 'Pièces à contrôler',
    costEstimate: 'Estimation du coût de réparation',
    confidence: 'Confiance',
    costFrom: 'À partir de {amount}',
    costUpTo: 'Jusqu’à {amount}',
    errors: {
      generic: 'Échec de l’analyse. Veuillez réessayer.',
      maxFile: 'Taille maximale du fichier : 20 Mo.',
      mic: 'Accès au micro refusé. Autorisez l’accès puis réessayez.',
      no_audio: 'Veuillez fournir un enregistrement du son.',
      too_large: 'Le fichier audio est trop volumineux. Utilisez des extraits de moins de 8 Mo (environ 30 secondes).',
      unavailable: 'Le service d’IA est temporairement indisponible. Réessayez dans un instant.',
      parse: 'Impossible de lire la réponse de l’IA. Veuillez réessayer.',
      server: 'Une erreur est survenue. Veuillez réessayer.',
    },
  },
};
