import type { EngineSoundCopy } from './types';

// Indonesian — search-term research: drivers search "suara mesin mobil kasar",
// "bunyi tek-tek / klotok-klotok" (ticking), "mesin ngelitik / engine knocking"
// (knock) and "bunyi grok-grok" (rattling).
export const id: EngineSoundCopy = {
  lang: 'id',
  locale: 'id_ID',
  dir: 'ltr',
  homeHref: '/beranda',
  homeLabel: 'Beranda',
  hubHref: '/alat',
  hubLabel: 'Alat',
  backLabel: 'Kembali ke alat',
  slug: 'analisis-suara-mesin',
  metaTitle: 'Analisis Suara Mesin Mobil — Diagnosis AI Gratis dari Audio | Naira Autos',
  metaDescription: 'Rekam atau unggah suara mesin mobil Anda dan dapatkan diagnosis AI instan untuk penyebab yang mungkin: bunyi tek-tek, mesin ngelitik, bunyi grok-grok, dan lainnya. Gratis, tanpa daftar.',
  keywords: ['suara mesin mobil kasar', 'suara mesin mobil aneh', 'bunyi tek-tek mesin', 'bunyi klotok-klotok mesin', 'mesin ngelitik', 'engine knocking', 'bunyi grok-grok mesin', 'diagnosis suara mesin', 'analisis suara mesin'],
  ogDescription: 'Rekam atau unggah suara mesin mobil Anda dan dapatkan diagnosis AI instan untuk penyebab yang mungkin.',
  toolName: 'Analisis Suara Mesin',
  schemaDescription: 'Alat AI gratis yang mendiagnosis masalah mobil dari rekaman suara mesin.',
  badge: 'Alat Gratis',
  verified: 'Terakhir diperiksa: September 2026',
  h1a: 'Analisis',
  h1b: 'Suara Mesin',
  intro: 'Rekam atau unggah suara yang dikeluarkan mobil Anda dan dapatkan diagnosis AI instan: penyebab yang mungkin, seberapa mendesak, dan perkiraan biaya perbaikan.',
  pickerEyebrow: 'Suara apa yang Anda dengar?',
  pickerTitle: 'Pilih yang paling mirip',
  pickerCta: 'Diagnosis suara ini →',
  pickerNote: 'Tidak yakin mana yang paling mirip? Perekam di atas bisa menganalisis suara mesin apa pun, jadi Anda tidak perlu memilih kategori dulu.',
  sections: [
    {
      h2: 'Apa itu analisis suara mesin?',
      paras: [
        'Mekanik berpengalaman sering bisa menebak kerusakan mobil hanya dari suara mesin, bahkan sebelum membuka kap. Alat ini melakukan hal yang sama dengan AI: Anda merekam atau mengunggah klip suara mobil, lalu AI mengidentifikasi penyebab yang paling mungkin, seperti mekanik yang mendiagnosis lewat telinga.',
        'Alat ini bekerja untuk semua suara mesin yang tidak biasa, bukan hanya tiga di atas: suara mendecit, mendengung, bergesekan, atau mengklik. Selama bisa direkam, AI akan mencoba mendiagnosisnya. Tambahkan deskripsi singkat (misalnya "hanya saat mesin dingin") serta merek dan tipe mobil agar hasilnya lebih akurat.',
      ],
    },
    {
      h2: 'Mengapa suara mesin tidak boleh diabaikan',
      paras: [
        'Suara baru pada mesin jarang muncul tanpa sebab. Bunyi tek-tek, ngelitik, atau grok-grok hampir selalu menandakan ada yang berubah: komponen yang aus, oli yang kurang, atau bagian yang mengendur. Sebagian suara tidak berbahaya, tetapi ada juga yang memberi tanda kerusakan yang cepat memburuk, seperti bearing stang piston yang mengetuk.',
        'Merekam suara dan mendapat pembacaan awal tidak memakan biaya dan kurang dari satu menit. Biasanya jauh lebih murah daripada menunggu masalah kecil berubah menjadi perbaikan besar.',
      ],
    },
    {
      h2: 'Bedanya dengan mencari gejala di forum',
      paras: [
        'Mencari gejala di internet biasanya menghasilkan daftar panjang dan umum tentang semua hal yang mungkin menyebabkan suara itu: berguna untuk wawasan, tapi kurang membantu mengetahui apa yang sebenarnya terjadi pada mobil Anda. Di sini analisis berangkat dari rekaman Anda sendiri dan data yang Anda isi, lalu menunjukkan penyebab paling mungkin dan tingkat urgensinya.',
        'Alat ini tidak menggantikan pemeriksaan di bengkel. Anggap saja sebagai langkah pertama yang cepat dan gratis untuk tahu apakah mobil masih aman dipakai dan apa yang perlu diperiksa atau ditanyakan ke mekanik sebelum mengeluarkan uang untuk sekadar tebakan.',
      ],
    },
  ],
  tipsTitle: 'Tips merekam suara yang bisa didiagnosis',
  tips: [
    'Dekatkan perekam ke sumber suara selama aman: dekat ruang mesin untuk suara mesin, atau dekat roda jika curiga rem atau kaki-kaki.',
    'Matikan radio dan tutup jendela agar angin dan kebisingan jalan tidak menutupi suara.',
    'Rekam saat suara paling jelas: saat start mesin dingin untuk bunyi tek-tek klep, saat menginjak gas untuk ngelitik, atau saat melewati lubang untuk bunyi grok-grok.',
    'Catat kapan suara muncul (hanya saat dingin, hanya saat belok, hanya saat beban berat): kolom deskripsi membantu AI mempersempit diagnosis.',
  ],
  exampleTitle: 'Contoh: bunyi tek-tek saat dingin yang tidak serius',
  exampleText: 'Toyota Avanza milik Budi berbunyi tek-tek setiap pagi saat dinyalakan, lalu hilang dalam satu-dua menit setelah mesin hangat. Khawatir ada masalah bearing, ia merekam 15 detik dan menganalisisnya dengan alat ini. Pola suaranya mengarah ke hydraulic lifter saat oli masih dingin, bukan masalah stang piston. Ia memeriksa oli dan ternyata kurang; setelah ganti oli, bunyinya hilang.',
  reviewedBefore: 'Ditinjau oleh',
  reviewedAfter: ', mekanik otomotif. Kategori suara diperiksa agar sesuai dengan praktik di bengkel.',
  faqTitle: 'FAQ analisis suara mesin',
  faqs: [
    { q: 'Apa itu analisis suara mesin?', a: 'Alat yang mendengarkan rekaman suara mesin Anda dan mengidentifikasi penyebab yang mungkin dengan AI, seperti mekanik yang mendiagnosis lewat telinga sebelum membuka kap.' },
    { q: 'Suara mesin apa saja yang bisa didiagnosis?', a: 'Bunyi tek-tek, ngelitik, grok-grok, mendecit, bergesekan, bersiul, mendengung, dan sebagian besar suara tidak biasa. Jika bisa direkam, AI bisa mencoba mendiagnosisnya.' },
    { q: 'Berapa lama rekaman yang dibutuhkan?', a: 'Versi gratis menganalisis 30 detik pertama dari setiap klip, yang biasanya cukup untuk diagnosis yang jelas.' },
    { q: 'Apakah diagnosisnya selalu akurat?', a: 'Tidak. Ini titik awal yang baik, bukan jawaban akhir, dan bisa melewatkan hal yang akan ditemukan pemeriksaan langsung. Untuk suara terkait rem, setir, atau bahan bakar, berhenti mengemudi dan datangi bengkel.' },
    { q: 'Apakah gratis?', a: 'Ya, gratis dan tanpa daftar. Rekaman lebih dari 30 detik direncanakan sebagai opsi berbayar di kemudian hari.' },
  ],
  relatedTitle: 'Alat gratis lainnya',
  relatedLabels: { mechanic: 'Montir Virtual', value: 'Berapa Harga Mobil Saya?', vin: 'Cek Nomor Rangka' },
  subs: [
    {
      key: 'ticking',
      slug: 'bunyi-tek-tek-mesin',
      navLabel: 'Bunyi tek-tek mesin',
      cardDesc: 'Ketukan ringan dan cepat, tek-tek-tek: sering dari klep, injektor, atau mekanisme katup.',
      metaTitle: 'Bunyi Tek-Tek pada Mesin Mobil — Diagnosis AI Gratis | Naira Autos',
      metaDescription: 'Mesin mobil berbunyi tek-tek atau klotok-klotok? Rekam suaranya dan dapatkan diagnosis AI: klep, oli kurang, injektor, dan lainnya. Gratis, tanpa daftar.',
      keywords: ['bunyi tek-tek mesin mobil', 'bunyi klotok-klotok mesin', 'bunyi tek tek saat mesin dingin', 'suara klep mesin', 'mesin bunyi saat start', 'suara mesin kasar saat dingin', 'mesin diesel bunyi tek-tek'],
      h1a: 'Analisis',
      h1b: 'Bunyi Tek-Tek Mesin',
      intro: 'Bunyi tek-tek yang ringan dan teratur sering punya penyebab sederhana. Rekam dan cari tahu apakah masalahnya oli atau sesuatu yang lebih serius.',
      schemaDescription: 'Alat AI gratis yang mendiagnosis bunyi tek-tek pada mesin dari rekaman audio.',
      sections: [
        {
          h2: 'Apa penyebab bunyi tek-tek pada mesin?',
          paras: [
            'Bunyi tek-tek adalah suara logam yang ringan dan cepat, mengikuti irama mesin. Penyebab paling umum adalah hydraulic lifter atau celah klep, oli mesin yang kurang atau sudah rusak, injektor yang berbunyi klik (normal sampai batas tertentu), dan lebih jarang rantai keteng atau tensioner yang aus.',
            'Waktu munculnya suara adalah petunjuk penting: bunyi tek-tek yang hilang saat mesin hangat biasanya tidak seserius yang tetap ada atau makin keras seiring putaran mesin.',
          ],
        },
        {
          h2: 'Bunyi tek-tek hanya saat mesin dingin: serius?',
          paras: [
            'Banyak mesin berbunyi tek-tek singkat saat dingin karena oli butuh beberapa detik untuk sampai ke lifter. Jika hilang dalam satu-dua menit dan level oli normal, biasanya tidak perlu khawatir, tetapi tetap pantau.',
            'Jika tetap ada saat mesin panas, makin parah, atau disertai tenaga turun atau lampu indikator oli menyala, jangan ditunda: periksa level oli segera dan bawa ke bengkel.',
          ],
        },
        {
          h2: 'Apa yang bisa diperiksa sebelum ke bengkel',
          paras: [
            'Periksa level oli saat mesin dingin di permukaan datar, dan lihat apakah oli sangat hitam atau kental. Perhatikan apakah suara mengikuti putaran mesin: jika makin cepat bersama mesin, sumbernya di bagian atas mesin; jika mengikuti kecepatan mobil, sumbernya mungkin di tempat lain.',
          ],
        },
      ],
      exampleTitle: 'Contoh: bunyi tek-tek yang selesai dengan oli',
      exampleText: 'Rina mendengar bunyi tek-tek terus-menerus di Honda Brio-nya setelah berbulan-bulan tidak mengecek oli. Ia merekam suaranya; alat ini menunjuk pelumasan kurang di bagian atas mesin dan menyarankan memeriksa level oli lebih dulu. Olinya hampir di batas minimum; setelah ganti oli dan filter, bunyinya hilang.',
      reviewedAfter: ', mekanik otomotif. Penyebab bunyi tek-tek diperiksa agar sesuai dengan praktik di bengkel.',
      faqTitle: 'FAQ bunyi tek-tek pada mesin',
      faqs: [
        { q: 'Mengapa mesin saya berbunyi tek-tek?', a: 'Yang paling umum adalah oli kurang atau rusak yang memengaruhi lifter dan klep; bisa juga injektor, rantai keteng, atau komponen yang longgar.' },
        { q: 'Apakah normal berbunyi tek-tek saat start dingin?', a: 'Bunyi tek-tek singkat yang hilang saat mesin hangat umum terjadi di banyak mesin. Jika lebih lama atau berulang, periksa oli.' },
        { q: 'Bolehkah mobil tetap dipakai dengan bunyi ini?', a: 'Jika level oli normal dan suaranya ringan, biasanya boleh sebentar, tetapi segera periksakan. Jika lampu oli menyala atau tenaga turun, berhenti.' },
        { q: 'Apa itu hydraulic lifter?', a: 'Komponen yang meneruskan gerakan noken as ke klep. Jika pelumasannya kurang atau aus, timbul bunyi tek-tek yang khas.' },
      ],
    },
    {
      key: 'knocking',
      slug: 'mesin-ngelitik',
      navLabel: 'Mesin ngelitik',
      cardDesc: 'Ketukan yang lebih dalam dan berat: bisa karena bahan bakar atau masalah bearing yang serius.',
      metaTitle: 'Mesin Ngelitik (Engine Knocking) — Diagnosis AI Gratis | Naira Autos',
      metaDescription: 'Mesin mobil ngelitik atau engine knocking? Rekam suaranya dan dapatkan diagnosis AI: bearing stang piston, detonasi, injektor, dan lainnya. Gratis, tanpa daftar.',
      keywords: ['mesin ngelitik', 'engine knocking', 'mesin ngelitik saat digas', 'penyebab mesin ngelitik', 'bearing stang piston bunyi', 'mesin diesel ngelitik', 'suara mesin kasar saat digas'],
      h1a: 'Analisis',
      h1b: 'Mesin Ngelitik',
      intro: 'Ketukan yang dalam dan berat perlu ditanggapi serius. Rekam dan cari tahu apakah penyebabnya bahan bakar atau sesuatu yang lebih mekanis.',
      schemaDescription: 'Alat AI gratis yang mendiagnosis mesin ngelitik (engine knocking) dari rekaman audio.',
      sections: [
        {
          h2: 'Apa penyebab mesin ngelitik?',
          paras: [
            'Ngelitik satu tingkat lebih serius dari tek-tek: lebih dalam, lebih berat, dan biasanya makin keras saat beban atau putaran naik. Penyebab utamanya adalah detonasi (bahan bakar terbakar tidak teratur karena oktan rendah atau kerak karbon), bearing stang piston atau bearing utama yang aus, injektor diesel bermasalah, atau aksesori yang kendur seperti pulley alternator.',
            'Waktu kemunculan sangat penting: ngelitik yang muncul tepat setelah mengisi bensin mengarah ke bahan bakar; yang makin keras pelan-pelan selama berminggu-minggu, tanpa kaitan dengan bahan bakar, lebih mengarah ke keausan bearing.',
          ],
        },
        {
          h2: 'Bearing stang piston mengetuk: yang harus ditanggapi serius',
          paras: [
            'Ketukan bearing stang piston adalah bunyi dalam yang berirama akibat celah berlebih pada bearing yang aus. Biasanya makin keras saat putaran naik dan kadang lebih jelas saat beban berat daripada saat idle. Berbeda dengan ngelitik karena bahan bakar, bunyi ini tidak membaik dengan mengganti bensin, dan terus mengemudi bisa berujung pada kerusakan mesin.',
          ],
        },
        {
          h2: 'Apakah bahan bakar buruk bisa membuat mesin ngelitik?',
          paras: [
            'Bisa. Memakai bahan bakar dengan oktan lebih rendah dari yang dibutuhkan mesin dapat memicu detonasi, yang terdengar seperti denting logam saat digas. Biasanya lebih ringan dari ketukan mekanis dan sering hilang dengan bahan bakar yang lebih baik atau pembersihan sistem injeksi.',
          ],
        },
        {
          h2: 'Ngelitik pada mesin diesel',
          paras: [
            'Mesin diesel secara alami lebih berisik daripada mesin bensin, sehingga ketukan baru lebih sulit disadari, tetapi layak diperhatikan begitu terdengar. Jika baru muncul atau makin parah, injektor adalah penyebab yang sering. Rekam dan bandingkan dengan suara normal mesin Anda.',
          ],
        },
      ],
      exampleTitle: 'Contoh: ternyata bahan bakar, bukan bearing',
      exampleText: 'Daihatsu Xenia milik Dimas mulai ngelitik saat digas tepat setelah mengisi bensin di SPBU yang belum pernah ia pakai. Dengan jarak tempuh yang sudah jauh, ia khawatir bearing dan merekam suaranya sebelum membayar diagnosis. Polanya sesuai dengan detonasi akibat bahan bakar; setelah mengisi penuh dengan bensin beroktan lebih tinggi, ngelitiknya hilang.',
      reviewedAfter: ', mekanik otomotif. Jenis dan penyebab ngelitik diperiksa agar sesuai dengan praktik di bengkel.',
      faqTitle: 'FAQ mesin ngelitik',
      faqs: [
        { q: 'Mengapa mesin saya ngelitik saat digas?', a: 'Detonasi akibat bahan bakar beroktan rendah, bearing stang piston aus, injektor diesel bermasalah, atau aksesori yang kendur. Waktu munculnya adalah petunjuk penting.' },
        { q: 'Apakah mesin ngelitik selalu serius?', a: 'Tidak selalu, tetapi perlu kehati-hatian lebih daripada bunyi tek-tek. Yang karena bahan bakar sering bisa diatasi; ketukan bearing stang piston adalah masalah mekanis nyata yang makin parah.' },
        { q: 'Apa itu ketukan bearing stang piston?', a: 'Bunyi dalam yang berirama akibat celah pada bearing stang piston yang aus. Naik seiring putaran, tidak membaik dengan bahan bakar lain, dan makin merusak mesin jika terus dipakai.' },
        { q: 'Mengapa mesin diesel saya ngelitik?', a: 'Diesel memang lebih berisik secara desain, tetapi ngelitik baru atau yang makin keras sering mengarah ke injektor.' },
        { q: 'Apakah bahan bakar buruk bisa menyebabkan ngelitik?', a: 'Ya, bensin beroktan rendah bisa memicu detonasi saat digas. Biasanya lebih ringan dan metalik daripada ketukan mekanis, dan membaik dengan bahan bakar yang lebih baik.' },
      ],
    },
    {
      key: 'rattling',
      slug: 'bunyi-grok-grok-mesin',
      navLabel: 'Bunyi grok-grok',
      cardDesc: 'Bunyi logam longgar yang bergetar: sering dari engine mounting, heat shield, atau rantai keteng.',
      metaTitle: 'Bunyi Grok-Grok pada Mesin Mobil — Diagnosis AI Gratis | Naira Autos',
      metaDescription: 'Ada bunyi grok-grok atau kemerincing dari ruang mesin? Rekam dan dapatkan diagnosis AI: heat shield, engine mounting, rantai keteng, dan lainnya. Gratis.',
      keywords: ['bunyi grok-grok mesin', 'suara kemerincing ruang mesin', 'suara logam di mesin', 'heat shield knalpot bunyi', 'rantai keteng bunyi', 'engine mounting rusak bunyi', 'knalpot bergetar bunyi'],
      h1a: 'Analisis',
      h1b: 'Bunyi Grok-Grok Mesin',
      intro: 'Bunyi logam longgar bisa saja baut yang kendur, atau bisa juga rantai keteng. Rekam dan cari tahu penyebabnya.',
      schemaDescription: 'Alat AI gratis yang mendiagnosis bunyi grok-grok pada mesin dari rekaman audio.',
      sections: [
        {
          h2: 'Apa penyebab bunyi grok-grok dari mesin?',
          paras: [
            'Bunyi grok-grok adalah suara logam longgar, seperti komponen yang saling bergetar. Penyebab umumnya adalah heat shield knalpot yang kendur, engine mounting atau karet gantungan knalpot yang aus, baut atau pengikat yang longgar, dan pada kasus lebih serius, rantai keteng atau tensionernya.',
            'Kuncinya adalah kapan suara muncul: saat idle, saat digas, saat dingin, atau hanya saat melewati lubang. Ini membantu membedakan komponen longgar yang sepele dari masalah rantai keteng.',
          ],
        },
        {
          h2: 'Bunyi grok-grok saat start: kapan perlu khawatir?',
          paras: [
            'Bunyi grok-grok singkat beberapa detik saat start mesin dingin bisa berasal dari rantai keteng atau tensioner yang kekurangan tekanan oli. Jika terjadi setiap kali atau makin parah, jangan diabaikan: rantai keteng yang rusak bisa berujung pada kerusakan yang sangat mahal.',
          ],
        },
        {
          h2: 'Yang bisa Anda periksa sendiri',
          paras: [
            'Saat mesin mati dan dingin, pastikan heat shield dan pengikat knalpot tidak goyang, dan cari baut longgar di ruang mesin. Jika suara berubah mengikuti putaran mesin atau hanya muncul saat melewati lubang, catat di kolom deskripsi: itu petunjuk berharga.',
          ],
        },
      ],
      exampleTitle: 'Contoh: heat shield yang kendur',
      exampleText: 'Honda CR-V milik Sari mengeluarkan bunyi grok-grok pada putaran tertentu dan ia khawatir soal rantai keteng. Ia merekam suaranya dan alat ini mengaitkannya dengan komponen longgar di bawah mobil, bukan mesin. Montir menemukan heat shield knalpot dengan baut kendur dan mengencangkannya dalam hitungan menit.',
      reviewedAfter: ', mekanik otomotif. Penyebab bunyi grok-grok diperiksa agar sesuai dengan praktik di bengkel.',
      faqTitle: 'FAQ bunyi grok-grok pada mesin',
      faqs: [
        { q: 'Mengapa mobil saya berbunyi grok-grok di bawah kap?', a: 'Paling sering heat shield atau pengikat yang kendur; bisa juga engine mounting aus atau, lebih jarang, rantai keteng.' },
        { q: 'Apakah bunyi grok-grok saat start serius?', a: 'Tergantung. Jika hanya beberapa detik dan tidak berulang, biasanya ringan; jika konstan atau makin parah, bisa jadi rantai keteng dan perlu diperiksa.' },
        { q: 'Bagaimana membedakan bunyi knalpot dari bunyi mesin?', a: 'Bunyi knalpot sering berubah mengikuti putaran dan terdengar dari bawah mobil; bunyi mesin berasal dari ruang mesin.' },
        { q: 'Bolehkah tetap mengemudi?', a: 'Jika hanya komponen longgar dan suaranya ringan, biasanya boleh sebentar. Jika curiga rantai keteng, hindari mengemudi dan konsultasikan ke mekanik.' },
      ],
    },
  ],
  ui: {
    record: 'Rekam suara',
    upload: 'Unggah klip',
    stop: 'Berhenti',
    descPlaceholder: 'Opsional: kapan terjadi? (mis. hanya saat dingin, hanya saat belok)',
    brand: 'Merek (opsional)',
    model: 'Tipe',
    year: 'Tahun',
    analyse: 'Analisis suara ini',
    analysing: 'Menganalisis suara...',
    listening: 'Mendengarkan rekaman Anda...',
    another: 'Analisis suara lain',
    noticeTrimmed: 'Klip ini berdurasi {duration} detik; di versi gratis kami hanya menganalisis {cap} detik pertama. Klip lebih panjang akan hadir sebagai opsi berbayar.',
    noticeLong: 'Klip ini berdurasi {duration} detik. Kami sarankan memotongnya menjadi {cap} detik atau kurang sebelum diunggah.',
    noticeCapped: 'Rekaman dibatasi {cap} detik di versi gratis, yang biasanya cukup untuk sampel suara yang jelas. Klip lebih panjang akan hadir sebagai opsi berbayar.',
    footnote: 'Versi gratis menganalisis {cap} detik pertama dari setiap klip. Diagnosis AI tidak selalu 100% akurat: anggap sebagai titik awal, bukan jawaban akhir. Untuk rem, setir, atau bahan bakar, berhenti mengemudi dan temui mekanik.',
    disclaimer: 'Diagnosis buatan AI berdasarkan {cap} detik pertama audio. Tidak selalu 100% akurat dan bisa melewatkan hal yang akan ditemukan pemeriksaan langsung. Anggap sebagai titik awal, bukan jawaban akhir. Untuk rem, setir, atau bahan bakar, berhenti mengemudi dan temui mekanik yang kompeten.',
    urgency: { safe: 'Aman dikendarai', monitor: 'Pantau dengan cermat', urgent: 'Segera ke bengkel', stop_driving: 'Berhenti mengemudi sekarang' },
    prob: { high: 'Tinggi', medium: 'Sedang', low: 'Rendah' },
    priority: { immediate: 'Sekarang', soon: 'Segera', when_convenient: 'Saat senggang' },
    diy: 'Sendiri',
    possibleCauses: 'Kemungkinan penyebab',
    mostLikelyCause: 'Penyebab paling mungkin',
    whatToDo: 'Yang perlu dilakukan',
    betterDiagnosis: 'Untuk diagnosis lebih baik, coba juga',
    partsToInspect: 'Komponen yang perlu diperiksa',
    costEstimate: 'Perkiraan biaya perbaikan',
    confidence: 'Tingkat keyakinan',
    costFrom: 'Mulai dari {amount}',
    costUpTo: 'Hingga {amount}',
    errors: {
      generic: 'Gagal menganalisis. Silakan coba lagi.',
      maxFile: 'Ukuran file maksimal 20 MB.',
      mic: 'Akses mikrofon ditolak. Izinkan akses lalu coba lagi.',
      no_audio: 'Mohon lampirkan rekaman suara.',
      too_large: 'File audio terlalu besar. Gunakan klip di bawah 8 MB (sekitar 30 detik).',
      unavailable: 'Layanan AI sedang tidak tersedia. Silakan coba lagi sebentar lagi.',
      parse: 'Respons AI tidak dapat dibaca. Silakan coba lagi.',
      server: 'Terjadi kesalahan. Silakan coba lagi.',
    },
  },
};
