import type { EngineSoundCopy } from './types';

// Italian — search-term research: drivers search "rumore motore",
// "ticchettio motore" (ticking: punterie), "battito in testa" / "motore
// sbiellato" (knock, bronzine) and "rumore di ferraglia / sferragliamento".
export const it: EngineSoundCopy = {
  lang: 'it',
  locale: 'it_IT',
  dir: 'ltr',
  homeHref: '/inizio',
  homeLabel: 'Home',
  hubHref: '/strumenti',
  hubLabel: 'Strumenti',
  backLabel: 'Torna agli strumenti',
  slug: 'analizzatore-rumori-motore',
  metaTitle: 'Analizzatore di Rumori del Motore — Diagnosi Gratis con IA | Naira Autos',
  metaDescription: 'Registra o carica il rumore del motore e ricevi subito una diagnosi con IA della causa probabile: ticchettio, battito in testa, rumore di ferraglia e altro. Gratis, senza registrazione.',
  keywords: ['rumore motore', 'rumori motore auto', 'ticchettio motore', 'battito in testa', 'motore sbiellato rumore', 'rumore di ferraglia motore', 'diagnosi rumore motore', 'analizzatore rumori motore', 'rumore strano motore cause'],
  ogDescription: 'Registra o carica il rumore del motore e ricevi subito una diagnosi con IA della causa probabile.',
  toolName: 'Analizzatore di Rumori del Motore',
  schemaDescription: 'Strumento gratuito con IA che diagnostica i problemi dell’auto a partire da una registrazione del rumore del motore.',
  badge: 'Strumento gratuito',
  verified: 'Ultima verifica: settembre 2026',
  h1a: 'Analizzatore di',
  h1b: 'Rumori del Motore',
  intro: 'Registra o carica il rumore che fa la tua auto e ricevi subito una diagnosi con IA: cause probabili, quanto è urgente e quanto potrebbe costare la riparazione.',
  pickerEyebrow: 'Che rumore senti?',
  pickerTitle: 'Scegli il più simile',
  pickerCta: 'Diagnostica questo rumore →',
  pickerNote: 'Non sai quale si avvicina di più? Il registratore qui sopra analizza qualsiasi rumore del motore: non devi scegliere prima una categoria.',
  sections: [
    {
      h2: 'Cos’è un analizzatore di rumori del motore?',
      paras: [
        'Un meccanico esperto capisce spesso cosa non va in un’auto solo ascoltando il motore, prima ancora di aprire il cofano. Questo strumento fa lo stesso con l’intelligenza artificiale: registri o carichi un audio del rumore dell’auto e l’IA individua la causa più probabile, come un meccanico che diagnostica a orecchio.',
        'Funziona per qualsiasi rumore insolito del motore, non solo i tre qui sopra: fischi, stridii, ronzii, sfregamenti o scatti. Se riesci a registrarlo, l’IA può provare a diagnosticarlo. Aggiungi una breve descrizione (per esempio “solo a freddo”) e marca e modello per rendere il risultato più preciso.',
      ],
    },
    {
      h2: 'Perché non conviene ignorare il rumore del motore',
      paras: [
        'Un rumore nuovo al motore raramente compare senza motivo. Un ticchettio, un battito o un rumore di ferraglia indica quasi sempre che qualcosa è cambiato: un componente che si usura, il livello dell’olio troppo basso o un elemento che si è allentato. Alcuni rumori sono innocui, altri annunciano guasti che peggiorano in fretta, come il battito delle bronzine di biella.',
        'Registrare il rumore e ottenere una prima valutazione non costa nulla e richiede meno di un minuto. Spesso costa molto meno che aspettare che un piccolo difetto diventi una riparazione pesante.',
      ],
    },
    {
      h2: 'La differenza rispetto a cercare il sintomo su un forum',
      paras: [
        'Cercare un sintomo online di solito restituisce un lungo elenco generico di tutto ciò che potrebbe causare quel rumore: utile per informarsi, meno per capire cosa succede alla tua auto. Qui l’analisi parte dal tuo audio e dai dati che inserisci, e ti indica le cause più probabili e l’urgenza.',
        'Non sostituisce comunque un controllo in officina. Consideralo un primo passo rapido e gratuito per capire se puoi continuare a guidare e cosa verificare o chiedere al meccanico prima di spendere soldi per un’ipotesi.',
      ],
    },
  ],
  tipsTitle: 'Consigli per registrare un audio utile alla diagnosi',
  tips: [
    'Avvicinati alla sorgente del rumore in sicurezza: vicino al vano motore per i rumori del motore, vicino a una ruota se sospetti freni o sospensioni.',
    'Spegni la radio e chiudi i finestrini perché vento e traffico non coprano il suono.',
    'Registra quando il rumore si sente meglio: all’avviamento a freddo per il ticchettio delle punterie, in accelerazione per il battito, su una buca per il rumore di ferraglia.',
    'Annota quando si presenta (solo a freddo, solo in curva, solo sotto sforzo): il campo descrizione aiuta l’IA a restringere la diagnosi.',
  ],
  exampleTitle: 'Esempio: un ticchettio a freddo che non era grave',
  exampleText: 'La Fiat Panda di Marco ha iniziato a ticchettare ogni mattina all’accensione, per poi smettere dopo uno o due minuti, a motore caldo. Preoccupato per le bronzine, ha registrato 15 secondi e li ha passati in questo strumento. Il profilo del suono indicava le punterie idrauliche con l’olio ancora freddo, non un problema di biella. Ha controllato il livello: era basso. Dopo il cambio dell’olio il rumore è sparito.',
  reviewedBefore: 'Revisionato da',
  reviewedAfter: ', meccanico. Categorie di rumori verificate per rispecchiare la pratica d’officina.',
  faqTitle: 'Domande frequenti sull’analizzatore di rumori del motore',
  faqs: [
    { q: 'Cos’è un analizzatore di rumori del motore?', a: 'Uno strumento che ascolta la registrazione del rumore del tuo motore e individua la causa probabile con l’IA, come un meccanico che diagnostica a orecchio prima di aprire il cofano.' },
    { q: 'Quali rumori del motore riesce a diagnosticare?', a: 'Ticchettio, battito in testa, rumore di ferraglia, stridii, sfregamenti, fischi, ronzii e la maggior parte dei rumori insoliti. Se riesci a registrarlo, l’IA può provare a diagnosticarlo.' },
    { q: 'Quanto deve durare la registrazione?', a: 'La versione gratuita analizza i primi 30 secondi di ogni audio, che di solito bastano per una diagnosi chiara.' },
    { q: 'La diagnosi è sempre corretta?', a: 'No. È un buon punto di partenza, non una risposta definitiva, e può non cogliere ciò che un controllo di persona troverebbe. Per rumori legati a freni, sterzo o carburante, smetti di guidare e rivolgiti a un’officina.' },
    { q: 'È gratuito?', a: 'Sì, gratis e senza registrazione. Le registrazioni oltre i 30 secondi arriveranno più avanti come opzione a pagamento.' },
  ],
  relatedTitle: 'Altri strumenti gratuiti',
  relatedLabels: { mechanic: 'Meccanico Virtuale', value: 'Quanto vale la mia auto?', vin: 'Verifica Numero di Telaio' },
  subs: [
    {
      key: 'ticking',
      slug: 'ticchettio-motore',
      navLabel: 'Ticchettio del motore',
      cardDesc: 'Un picchiettio leggero e veloce, tic-tic-tic: spesso punterie, iniettori o distribuzione.',
      metaTitle: 'Ticchettio del Motore — Diagnosi Gratis con IA | Naira Autos',
      metaDescription: 'Il motore fa un ticchettio? Registra il rumore e ricevi una diagnosi con IA: punterie, poco olio, iniettori e altro. Gratis, senza registrazione.',
      keywords: ['ticchettio motore', 'ticchettio motore a freddo', 'rumore punterie', 'motore fa tic tic', 'ticchettio motore al minimo', 'ticchettio motore diesel', 'ticchettio all’avviamento'],
      h1a: 'Analizzatore del',
      h1b: 'Ticchettio del Motore',
      intro: 'Un ticchettio leggero e regolare ha spesso una causa semplice. Registralo e scopri se è questione di olio o di qualcosa di più serio.',
      schemaDescription: 'Strumento gratuito con IA che diagnostica il ticchettio del motore da una registrazione audio.',
      sections: [
        {
          h2: 'Cosa causa il ticchettio del motore?',
          paras: [
            'Il ticchettio è un rumore metallico leggero e veloce che segue il ritmo del motore. Le cause più comuni sono punterie idrauliche o gioco valvole, livello dell’olio basso o olio esausto, iniettori che scattano (normale entro certi limiti) e, più raramente, catena di distribuzione o tenditore usurati.',
            'Il momento in cui compare è un indizio chiave: un ticchettio che sparisce quando il motore si scalda è di solito meno grave di uno che resta o aumenta con i giri.',
          ],
        },
        {
          h2: 'Ticchettio solo a freddo: è grave?',
          paras: [
            'Molti motori ticchettano brevemente a freddo perché l’olio impiega qualche secondo a raggiungere le punterie. Se sparisce in uno o due minuti e il livello dell’olio è corretto, di solito non c’è da preoccuparsi, ma tienilo d’occhio.',
            'Se continua a motore caldo, peggiora col tempo o si accompagna a perdita di potenza o alla spia dell’olio, non aspettare: controlla subito il livello e fai verificare l’auto.',
          ],
        },
        {
          h2: 'Cosa controllare prima di andare in officina',
          paras: [
            'Controlla il livello dell’olio a motore freddo e su terreno pianeggiante, e guarda se l’olio è molto scuro o denso. Osserva se il rumore segue i giri: se accelera con il motore, viene dalla parte alta; se segue la velocità dell’auto, l’origine è altrove.',
          ],
        },
      ],
      exampleTitle: 'Esempio: ticchettio risolto con l’olio',
      exampleText: 'Giulia ha notato un ticchettio costante sulla sua Lancia Ypsilon dopo mesi senza controllare l’olio. Ha registrato il suono; lo strumento ha indicato una lubrificazione insufficiente nella parte alta del motore e ha consigliato di verificare prima il livello. Era quasi al minimo; dopo il cambio di olio e filtro il rumore è scomparso.',
      reviewedAfter: ', meccanico. Cause del ticchettio verificate per rispecchiare la pratica d’officina.',
      faqTitle: 'Domande frequenti sul ticchettio del motore',
      faqs: [
        { q: 'Perché il mio motore fa un ticchettio?', a: 'Più spesso per poco olio o olio degradato che influisce su punterie e valvole; possono essere anche iniettori, catena di distribuzione o un componente allentato.' },
        { q: 'È normale il ticchettio all’avviamento a freddo?', a: 'Un ticchettio breve che sparisce a motore caldo è comune in molti motori. Se dura di più o ritorna, controlla l’olio.' },
        { q: 'Posso continuare a guidare con questo rumore?', a: 'Se il livello dell’olio è corretto e il rumore è lieve, di solito sì per poco tempo, ma fai controllare presto. Con spia dell’olio accesa o perdita di potenza, fermati.' },
        { q: 'Cosa sono le punterie?', a: 'Componenti che trasmettono il movimento dell’albero a camme alle valvole. Se lubrificate male o usurate, producono un tipico ticchettio.' },
      ],
    },
    {
      key: 'knocking',
      slug: 'battito-in-testa-motore',
      navLabel: 'Battito in testa',
      cardDesc: 'Un colpo più grave e pesante: può dipendere dal carburante o da un serio problema alle bronzine.',
      metaTitle: 'Battito in Testa del Motore — Diagnosi Gratis con IA | Naira Autos',
      metaDescription: 'Battito in testa o motore sbiellato? Registra il rumore e ricevi una diagnosi con IA: bronzine di biella, detonazione, iniettori e altro. Gratis, senza registrazione.',
      keywords: ['battito in testa', 'battito in testa motore', 'motore sbiellato rumore', 'bronzine rumore', 'rumore motore in accelerazione', 'battito in testa diesel', 'detonazione motore'],
      h1a: 'Analizzatore del',
      h1b: 'Battito in Testa',
      intro: 'Un colpo grave e pesante va preso sul serio. Registralo e scopri se dipende dal carburante o da qualcosa di più meccanico.',
      schemaDescription: 'Strumento gratuito con IA che diagnostica il battito in testa del motore da una registrazione audio.',
      sections: [
        {
          h2: 'Cosa causa il battito in testa?',
          paras: [
            'Il battito è un gradino più serio del ticchettio: più grave, più pesante e di solito più forte sotto sforzo o ai regimi alti. Le cause principali sono la detonazione (carburante che si accende in modo irregolare per ottano basso o depositi carboniosi), bronzine di biella o di banco usurate, un iniettore diesel difettoso o un accessorio allentato come la puleggia dell’alternatore.',
            'Il momento conta molto: un battito che compare subito dopo un rifornimento punta al carburante; uno che cresce piano piano nell’arco di settimane, a prescindere dal carburante, punta di più all’usura delle bronzine.',
          ],
        },
        {
          h2: 'Motore sbiellato: il battito da prendere sul serio',
          paras: [
            'Il battito di biella è un colpo grave e ritmico causato dal gioco eccessivo in una bronzina di biella usurata. Aumenta con i giri e a volte si sente meglio sotto carico che al minimo. A differenza del battito da carburante, non migliora cambiando benzina, e continuare a guidare può portare alla rottura del motore.',
          ],
        },
        {
          h2: 'Il carburante scadente può causare battito in testa?',
          paras: [
            'Sì. Usare carburante con un numero di ottano inferiore a quello richiesto dal motore può provocare detonazione, che in accelerazione suona come un tintinnio metallico. Di solito è più leggera di un battito meccanico e spesso sparisce con un carburante migliore o con la pulizia dell’impianto di iniezione.',
          ],
        },
        {
          h2: 'Battito nei motori diesel',
          paras: [
            'I diesel sono per natura più rumorosi dei benzina, quindi un nuovo battito è più difficile da notare, ma merita attenzione appena lo senti. Se è recente o peggiora, una causa frequente sono gli iniettori. Registralo e confrontalo con il suono abituale del tuo motore.',
          ],
        },
      ],
      exampleTitle: 'Esempio: era il carburante, non le bronzine',
      exampleText: 'La Hyundai i20 di Andrea ha iniziato a battere in accelerazione subito dopo un rifornimento in una stazione mai usata prima. Con quei chilometri temeva le bronzine e ha registrato il rumore prima di pagare una diagnosi. Il profilo era coerente con una detonazione da carburante; dopo aver fatto il pieno con benzina a più alto numero di ottano, il battito è sparito.',
      reviewedAfter: ', meccanico. Tipi e cause del battito verificati per rispecchiare la pratica d’officina.',
      faqTitle: 'Domande frequenti sul battito in testa',
      faqs: [
        { q: 'Perché il motore batte in accelerazione?', a: 'Detonazione da carburante a basso ottano, bronzine di biella usurate, un iniettore diesel difettoso o un accessorio allentato. Il momento in cui compare è un indizio importante.' },
        { q: 'Il battito in testa è sempre grave?', a: 'Non sempre, ma richiede più cautela di un ticchettio. Quello da carburante è spesso gestibile; il battito di biella è un vero problema meccanico che peggiora.' },
        { q: 'Cos’è il battito di biella?', a: 'Un colpo grave e ritmico dovuto al gioco in una bronzina di biella usurata. Sale con i giri, non migliora cambiando carburante e danneggia di più il motore quanto più si guida.' },
        { q: 'Perché il mio diesel batte?', a: 'I diesel sono più rumorosi per progetto, ma un battito nuovo o in aumento spesso dipende dagli iniettori.' },
        { q: 'Il carburante scadente può causare battito?', a: 'Sì, la benzina a basso ottano può causare detonazione in accelerazione. Di solito è più leggera e metallica di un battito meccanico e migliora con un carburante migliore.' },
      ],
    },
    {
      key: 'rattling',
      slug: 'rumore-di-ferraglia-motore',
      navLabel: 'Rumore di ferraglia',
      cardDesc: 'Uno sferragliare metallico allentato: spesso un supporto, una protezione termica o la distribuzione.',
      metaTitle: 'Rumore di Ferraglia dal Motore — Diagnosi Gratis con IA | Naira Autos',
      metaDescription: 'Rumore di ferraglia o sferragliamento dal cofano? Registralo e ricevi una diagnosi con IA: paracalore, supporti motore, distribuzione e altro. Gratis.',
      keywords: ['rumore di ferraglia motore', 'sferragliamento motore', 'rumore metallico motore', 'rumore ferraglia all’avviamento', 'paracalore scarico rumore', 'catena distribuzione rumore', 'supporti motore rumore'],
      h1a: 'Analizzatore del',
      h1b: 'Rumore di Ferraglia',
      intro: 'Un rumore di ferraglia può essere una semplice vite allentata o la catena di distribuzione. Registralo e scopri di cosa si tratta.',
      schemaDescription: 'Strumento gratuito con IA che diagnostica il rumore di ferraglia del motore da una registrazione audio.',
      sections: [
        {
          h2: 'Cosa causa il rumore di ferraglia dal motore?',
          paras: [
            'Il rumore di ferraglia è un suono metallico allentato, come di pezzi che vibrano uno contro l’altro. Le cause più comuni sono un paracalore dello scarico allentato, supporti motore o dello scarico usurati, viti o fissaggi allentati e, nei casi più seri, la catena di distribuzione o il suo tenditore.',
            'La chiave è quando si sente: al minimo, in accelerazione, a freddo o solo sulle buche. Questo aiuta a distinguere un pezzo allentato senza importanza da un problema alla distribuzione.',
          ],
        },
        {
          h2: 'Ferraglia all’avviamento: quando preoccuparsi?',
          paras: [
            'Un rumore di ferraglia breve all’avviamento a freddo, di pochi secondi, può venire dalla catena di distribuzione o da un tenditore a cui manca pressione dell’olio. Se si ripete ogni volta o peggiora, non ignorarlo: una catena di distribuzione danneggiata può portare a un guasto molto costoso.',
          ],
        },
        {
          h2: 'Cosa puoi controllare da solo',
          paras: [
            'A motore spento e freddo, verifica che i paracalore e i fissaggi dello scarico non ballino e cerca viti allentate nel vano motore. Se il rumore cambia con i giri o compare solo sulle buche, annotalo nel campo descrizione: è un indizio prezioso.',
          ],
        },
      ],
      exampleTitle: 'Esempio: un paracalore allentato',
      exampleText: 'La Honda CR-V di Chiara faceva un rumore di ferraglia a certi regimi e lei temeva un problema alla distribuzione. Ha registrato il suono e lo strumento lo ha collegato a un pezzo allentato sotto l’auto, non al motore. Il meccanico ha trovato un paracalore dello scarico con una vite allentata e l’ha stretta in pochi minuti.',
      reviewedAfter: ', meccanico. Cause del rumore di ferraglia verificate per rispecchiare la pratica d’officina.',
      faqTitle: 'Domande frequenti sul rumore di ferraglia dal motore',
      faqs: [
        { q: 'Perché la mia auto fa rumore di ferraglia sotto il cofano?', a: 'Più spesso un paracalore o un fissaggio allentato; possono essere anche supporti usurati o, più raramente, la distribuzione.' },
        { q: 'Il rumore di ferraglia all’avviamento è grave?', a: 'Dipende. Se dura pochi secondi e non si ripete, di solito è lieve; se è costante o peggiora, può essere la catena di distribuzione e va controllata.' },
        { q: 'Come distinguo la ferraglia dello scarico da quella del motore?', a: 'Quella dello scarico cambia spesso con i giri e si sente da sotto l’auto; quella del motore arriva dal vano motore.' },
        { q: 'Posso continuare a guidare?', a: 'Se è un pezzo allentato e il rumore è lieve, di solito sì per poco tempo. Se sospetti la distribuzione, evita di guidare e rivolgiti a un meccanico.' },
      ],
    },
  ],
  ui: {
    record: 'Registra il suono',
    upload: 'Carica audio',
    stop: 'Stop',
    descPlaceholder: 'Facoltativo: quando succede? (es. solo a freddo, solo in curva)',
    brand: 'Marca (facoltativo)',
    model: 'Modello',
    year: 'Anno',
    analyse: 'Analizza questo suono',
    analysing: 'Analisi del suono in corso...',
    listening: 'Ascolto della tua registrazione...',
    another: 'Analizza un altro suono',
    noticeTrimmed: 'Questo audio dura {duration} s; nella versione gratuita analizziamo solo i primi {cap} s. Gli audio più lunghi arriveranno come opzione a pagamento.',
    noticeLong: 'Questo audio dura {duration} s. Ti consigliamo di tagliarlo a {cap} s o meno prima di caricarlo.',
    noticeCapped: 'La registrazione è stata limitata a {cap} s nella versione gratuita, di solito sufficienti per un campione chiaro. Gli audio più lunghi arriveranno come opzione a pagamento.',
    footnote: 'La versione gratuita analizza i primi {cap} secondi di ogni audio. La diagnosi con IA non è sempre accurata al 100%: usala come punto di partenza, non come risposta definitiva. Per freni, sterzo o carburante, smetti di guidare e rivolgiti a un meccanico.',
    disclaimer: 'Diagnosi generata dall’IA sui primi {cap} secondi di audio. Non è sempre accurata al 100% e può non cogliere ciò che un controllo di persona troverebbe. Usala come punto di partenza, non come risposta definitiva. Per freni, sterzo o carburante, smetti di guidare e rivolgiti a un meccanico qualificato.',
    urgency: { safe: 'Puoi guidare', monitor: 'Tieni d’occhio', urgent: 'Vai presto dal meccanico', stop_driving: 'Smetti di guidare subito' },
    prob: { high: 'Alta', medium: 'Media', low: 'Bassa' },
    priority: { immediate: 'Subito', soon: 'A breve', when_convenient: 'Senza fretta' },
    diy: 'Fai da te',
    possibleCauses: 'Cause possibili',
    mostLikelyCause: 'Causa più probabile',
    whatToDo: 'Cosa fare',
    betterDiagnosis: 'Per una diagnosi migliore, prova anche',
    partsToInspect: 'Parti da controllare',
    costEstimate: 'Stima del costo di riparazione',
    confidence: 'Affidabilità',
    costFrom: 'Da {amount}',
    costUpTo: 'Fino a {amount}',
    errors: {
      generic: 'Analisi non riuscita. Riprova.',
      maxFile: 'Dimensione massima del file: 20 MB.',
      mic: 'Accesso al microfono negato. Consenti l’accesso e riprova.',
      no_audio: 'Allega una registrazione del suono.',
      too_large: 'Il file audio è troppo grande. Usa clip sotto gli 8 MB (circa 30 secondi).',
      unavailable: 'Il servizio di IA è temporaneamente non disponibile. Riprova tra un attimo.',
      parse: 'Impossibile leggere la risposta dell’IA. Riprova.',
      server: 'Qualcosa è andato storto. Riprova.',
    },
  },
};
