import type { EngineSoundCopy } from './types';

// Portuguese (Brazil) — search-term research: drivers search "barulho no motor",
// "motor batendo" / "batida de pino" (knock), "tucho batendo" / "tec-tec" (ticking),
// "barulho de chocalho / ruído metálico" (rattling).
export const pt: EngineSoundCopy = {
  lang: 'pt',
  locale: 'pt_BR',
  dir: 'ltr',
  homeHref: '/pagina-inicial',
  homeLabel: 'Início',
  hubHref: '/ferramentas',
  hubLabel: 'Ferramentas',
  backLabel: 'Voltar às ferramentas',
  slug: 'analisador-de-barulho-do-motor',
  metaTitle: 'Analisador de Barulho do Motor — Diagnóstico Grátis com IA | Naira Autos',
  metaDescription: 'Grave ou envie o barulho do motor do seu carro e receba na hora um diagnóstico com IA da causa provável: tec-tec, motor batendo, chocalho e mais. Grátis e sem cadastro.',
  keywords: ['barulho no motor', 'barulho no motor do carro', 'motor batendo', 'batida de pino', 'barulho de tucho batendo', 'barulho de chocalho no motor', 'ruído metálico no motor', 'diagnóstico de barulho do motor', 'analisador de barulho do motor'],
  ogDescription: 'Grave ou envie o barulho do motor do seu carro e receba na hora um diagnóstico com IA da causa provável.',
  toolName: 'Analisador de Barulho do Motor',
  schemaDescription: 'Ferramenta gratuita com IA que diagnostica problemas do carro a partir de uma gravação do barulho do motor.',
  badge: 'Ferramenta grátis',
  verified: 'Última revisão: setembro de 2026',
  h1a: 'Analisador de',
  h1b: 'Barulho do Motor',
  intro: 'Grave ou envie o barulho que o seu carro está fazendo e receba na hora um diagnóstico com IA: causas prováveis, urgência e quanto pode custar o conserto.',
  pickerEyebrow: 'Que barulho você está ouvindo?',
  pickerTitle: 'Escolha o mais parecido',
  pickerCta: 'Diagnosticar este barulho →',
  pickerNote: 'Não sabe qual se parece mais? O gravador acima analisa qualquer barulho do motor, e você não precisa escolher uma categoria antes.',
  sections: [
    {
      h2: 'O que é um analisador de barulho do motor?',
      paras: [
        'Um mecânico experiente muitas vezes descobre o que há de errado só de ouvir o motor, antes mesmo de abrir o capô. Esta ferramenta faz o mesmo com inteligência artificial: você grava ou envia um trecho do barulho do carro e a IA identifica a causa mais provável, como um mecânico que diagnostica de ouvido.',
        'Funciona para qualquer barulho estranho do motor, não só os três acima: assobio, chiado, zumbido, estalo ou tec-tec. Se você consegue gravar, a IA tenta diagnosticar. Adicione uma descrição curta (por exemplo, "só com o motor frio") e a marca e o modelo para deixar o resultado mais preciso.',
      ],
    },
    {
      h2: 'Por que não vale a pena ignorar o barulho do motor',
      paras: [
        'Um barulho novo no motor dificilmente aparece do nada. Um tec-tec, uma batida ou um chocalho quase sempre indica que algo mudou: uma peça se desgastando, óleo abaixo do nível ou um componente que soltou. Alguns sons são inofensivos, mas outros avisam de problemas que pioram rápido, como a bronzina batendo.',
        'Gravar o barulho e ter uma primeira leitura não custa nada e leva menos de um minuto. Costuma sair bem mais barato do que esperar um defeito pequeno virar um conserto grande.',
      ],
    },
    {
      h2: 'Qual a diferença de procurar o sintoma em um fórum',
      paras: [
        'Pesquisar o sintoma na internet costuma render uma lista longa e genérica de tudo que poderia causar aquele barulho: serve para se informar, mas não para saber o que está acontecendo com o seu carro. Aqui a análise parte do seu próprio áudio e dos dados que você informa, e mostra as causas mais prováveis e a urgência.',
        'Isso não substitui a avaliação na oficina. Pense nisso como um primeiro passo rápido e gratuito para saber se dá para continuar rodando e o que verificar ou perguntar ao mecânico antes de gastar dinheiro num palpite.',
      ],
    },
  ],
  tipsTitle: 'Dicas para gravar um áudio que dê para diagnosticar',
  tips: [
    'Chegue o mais perto possível da fonte do barulho com segurança: perto do motor para barulhos do motor, perto da roda se suspeitar de freio ou suspensão.',
    'Desligue o rádio e feche os vidros para o vento e o trânsito não abafarem o som.',
    'Grave quando o barulho estiver mais claro: na partida a frio para tec-tec de tucho, acelerando para batidas, passando num buraco para chocalho.',
    'Anote quando acontece (só a frio, só ao virar, só sob carga): o campo de descrição ajuda a IA a afunilar o diagnóstico.',
  ],
  exampleTitle: 'Exemplo: um tec-tec a frio que não era grave',
  exampleText: 'O Chevrolet Onix do Rafael começou a fazer tec-tec toda manhã ao ligar, e o barulho sumia em um ou dois minutos, com o motor quente. Com medo de ser bronzina, ele gravou 15 segundos e passou pela ferramenta. O padrão do som apontava para os tuchos hidráulicos com o óleo ainda frio, e não para problema de biela. Ele conferiu a vareta, o óleo estava baixo, fez a troca e o barulho acabou.',
  reviewedBefore: 'Revisado por',
  reviewedAfter: ', mecânico automotivo. Categorias de barulho conferidas para refletir a prática de oficina.',
  faqTitle: 'Perguntas frequentes sobre o analisador de barulho do motor',
  faqs: [
    { q: 'O que é um analisador de barulho do motor?', a: 'Uma ferramenta que ouve a gravação do barulho do seu motor e identifica a causa provável com IA, como um mecânico que diagnostica de ouvido antes de abrir o capô.' },
    { q: 'Que barulhos do motor ele consegue diagnosticar?', a: 'Tec-tec, motor batendo, chocalho, chiado, assobio, zumbido e a maioria dos barulhos incomuns. Se você consegue gravar, a IA tenta diagnosticar.' },
    { q: 'Quanto tempo precisa ter a gravação?', a: 'A versão gratuita analisa os primeiros 30 segundos de cada áudio, o que normalmente basta para um diagnóstico claro.' },
    { q: 'O diagnóstico é sempre certeiro?', a: 'Não. É um bom ponto de partida, não uma resposta final, e pode deixar passar o que uma avaliação presencial pegaria. Se o barulho tiver a ver com freio, direção ou combustível, pare de dirigir e procure uma oficina.' },
    { q: 'É gratuito?', a: 'Sim, grátis e sem cadastro. Gravações acima de 30 segundos devem chegar mais tarde como opção paga.' },
  ],
  relatedTitle: 'Mais ferramentas grátis',
  relatedLabels: { mechanic: 'Mecânico Virtual', value: 'Quanto vale meu carro?', vin: 'Decodificador de Chassi' },
  subs: [
    {
      key: 'ticking',
      slug: 'barulho-de-tucho-batendo',
      navLabel: 'Tec-tec / tucho batendo',
      cardDesc: 'Uma batidinha leve e rápida, tec-tec-tec: em geral tuchos, bicos injetores ou comando.',
      metaTitle: 'Tec-tec no Motor (Tucho Batendo) — Diagnóstico Grátis com IA | Naira Autos',
      metaDescription: 'Motor fazendo tec-tec ou tucho batendo? Grave o barulho e receba um diagnóstico com IA: tuchos, falta de óleo, bicos e mais. Grátis e sem cadastro.',
      keywords: ['barulho de tucho batendo', 'tec-tec no motor', 'barulho no motor ao ligar', 'tucho hidráulico barulho', 'barulho no motor a frio', 'estalo no motor', 'barulho de tec tec ao ligar o carro'],
      h1a: 'Analisador de',
      h1b: 'Tucho Batendo',
      intro: 'Um tec-tec leve e constante muitas vezes tem solução simples. Grave e descubra se é questão de óleo ou algo mais sério.',
      schemaDescription: 'Ferramenta gratuita com IA que diagnostica o tec-tec / tucho batendo do motor a partir de uma gravação.',
      sections: [
        {
          h2: 'O que causa o tec-tec no motor?',
          paras: [
            'O tec-tec é um ruído metálico leve e rápido que acompanha o ritmo do motor. As causas mais comuns são tuchos hidráulicos ou folga de válvulas, óleo baixo ou vencido, bicos injetores estalando (normal até certo ponto) e, mais raramente, corrente de comando ou tensor desgastados.',
            'O momento em que o barulho aparece é uma pista importante: um tec-tec que some quando o motor esquenta costuma ser menos grave do que um que continua ou aumenta com a rotação.',
          ],
        },
        {
          h2: 'Tec-tec só a frio: é grave?',
          paras: [
            'Muitos motores fazem um tec-tec rápido a frio porque o óleo leva alguns segundos para chegar aos tuchos. Se o barulho some em um ou dois minutos e o nível de óleo está certo, normalmente não é preocupante, mas fique de olho.',
            'Se continuar com o motor quente, piorar com o tempo ou vier junto com perda de força ou luz de óleo, não deixe para depois: confira o nível na hora e leve ao mecânico.',
          ],
        },
        {
          h2: 'O que verificar antes de ir à oficina',
          paras: [
            'Confira o nível de óleo com o motor frio e o carro em piso plano, e veja se o óleo está muito escuro ou grosso. Repare se o barulho acompanha a rotação: se acelera junto com o motor, vem da parte de cima; se acompanha a velocidade do carro, a origem pode ser outra.',
          ],
        },
      ],
      exampleTitle: 'Exemplo: tec-tec resolvido com óleo',
      exampleText: 'A Juliana percebeu um tec-tec constante no Fiat Argo depois de meses sem olhar o óleo. Ela gravou o som, a ferramenta apontou lubrificação insuficiente na parte alta do motor e sugeriu conferir o nível primeiro. Estava quase no mínimo; depois da troca de óleo e filtro, o barulho sumiu.',
      reviewedAfter: ', mecânico automotivo. Causas do tec-tec conferidas para refletir a prática de oficina.',
      faqTitle: 'Perguntas frequentes sobre o tec-tec no motor',
      faqs: [
        { q: 'Por que meu motor faz tec-tec?', a: 'Mais comum: falta de óleo ou óleo degradado afetando tuchos e válvulas. Também podem ser bicos injetores, corrente de comando ou uma peça solta.' },
        { q: 'É normal fazer tec-tec ao ligar a frio?', a: 'Um tec-tec curto que some quando o motor esquenta é comum em muitos motores. Se durar mais ou voltar, confira o óleo.' },
        { q: 'Posso continuar rodando com esse barulho?', a: 'Se o nível de óleo está certo e o barulho é leve, em geral sim por pouco tempo, mas leve para verificar logo. Com luz de óleo acesa ou perda de força, pare.' },
        { q: 'O que são tuchos?', a: 'Peças que transmitem o movimento do comando de válvulas às válvulas. Mal lubrificados ou desgastados, fazem um tec-tec característico.' },
      ],
    },
    {
      key: 'knocking',
      slug: 'motor-batendo',
      navLabel: 'Motor batendo',
      cardDesc: 'Uma batida mais grave e pesada: pode ser combustível ou um problema sério de bronzinas.',
      metaTitle: 'Motor Batendo (Batida de Pino) — Diagnóstico Grátis com IA | Naira Autos',
      metaDescription: 'Motor batendo ou batida de pino? Grave o barulho e receba um diagnóstico com IA: bronzina, detonação, bicos e mais. Grátis e sem cadastro.',
      keywords: ['motor batendo', 'batida de pino', 'motor batendo ao acelerar', 'barulho de motor batendo', 'bronzina batendo', 'motor diesel batendo', 'grilo no motor'],
      h1a: 'Analisador de',
      h1b: 'Motor Batendo',
      intro: 'Uma batida grave e pesada merece atenção. Grave e descubra se é combustível ou algo mais mecânico.',
      schemaDescription: 'Ferramenta gratuita com IA que diagnostica motor batendo a partir de uma gravação.',
      sections: [
        {
          h2: 'O que causa motor batendo?',
          paras: [
            'A batida é um degrau acima do tec-tec: mais grave, mais pesada e costuma aumentar com carga ou rotação. As causas principais são a detonação (batida de pino: combustível queimando de forma irregular por octanagem baixa ou depósito de carvão), bronzinas de biela ou de mancal gastas, bico diesel com defeito ou um acessório solto, como a polia do alternador.',
            'O momento faz muita diferença: uma batida que surge logo depois de abastecer aponta para o combustível; uma que cresce aos poucos ao longo de semanas, independente do combustível, aponta mais para desgaste de bronzinas.',
          ],
        },
        {
          h2: 'Bronzina batendo: a que é séria',
          paras: [
            'A bronzina batendo é uma pancada grave e ritmada causada por folga excessiva no mancal da biela. Fica mais forte conforme a rotação sobe e às vezes se ouve melhor sob carga do que em marcha lenta. Diferente da batida por combustível, não melhora trocando de gasolina, e continuar rodando pode terminar em quebra do motor.',
          ],
        },
        {
          h2: 'Combustível ruim pode fazer o motor bater?',
          paras: [
            'Pode. Usar combustível com octanagem menor que a exigida pelo motor causa detonação, que soa como um toc-toc metálico ao acelerar. Costuma ser mais leve que uma batida mecânica e muitas vezes some com um combustível melhor ou uma limpeza do sistema de injeção.',
          ],
        },
        {
          h2: 'Motor diesel batendo',
          paras: [
            'Motores diesel são naturalmente mais barulhentos que os a gasolina, então uma batida nova é mais difícil de notar, mas vale prestar atenção assim que perceber. Se for nova ou estiver piorando, os bicos injetores são causa frequente. Grave e compare com o som normal do seu motor.',
          ],
        },
      ],
      exampleTitle: 'Exemplo: era o combustível, não a bronzina',
      exampleText: 'O Hyundai HB20 do Marcelo começou a bater ao acelerar logo depois de abastecer num posto que ele nunca tinha usado. Pela quilometragem, temia bronzina e gravou o som antes de pagar um diagnóstico. O padrão combinava com detonação por combustível; depois de encher o tanque com gasolina de octanagem maior, a batida sumiu.',
      reviewedAfter: ', mecânico automotivo. Tipos e causas de batida conferidos para refletir a prática de oficina.',
      faqTitle: 'Perguntas frequentes sobre motor batendo',
      faqs: [
        { q: 'Por que meu motor bate ao acelerar?', a: 'Detonação por combustível de baixa octanagem, bronzinas de biela gastas, bico diesel com defeito ou acessório solto. O momento em que aparece é uma pista importante.' },
        { q: 'Motor batendo é sempre grave?', a: 'Nem sempre, mas pede mais cuidado que um tec-tec. A batida por combustível costuma ser administrável; bronzina batendo é problema mecânico real que piora.' },
        { q: 'O que é bronzina batendo?', a: 'Uma pancada grave e ritmada por folga no mancal da biela. Sobe com a rotação, não melhora com outro combustível e danifica mais o motor quanto mais você roda.' },
        { q: 'Por que meu motor diesel está batendo?', a: 'Diesel é mais barulhento por projeto, mas uma batida nova ou crescente costuma vir dos bicos injetores.' },
        { q: 'Combustível ruim pode causar batida?', a: 'Sim, gasolina de baixa octanagem pode causar detonação ao acelerar. Geralmente é mais leve e metálica que a batida mecânica e melhora com combustível melhor.' },
      ],
    },
    {
      key: 'rattling',
      slug: 'barulho-de-chocalho-no-motor',
      navLabel: 'Chocalho / ruído metálico',
      cardDesc: 'Um chacoalhar metálico solto: geralmente coxim, protetor térmico ou corrente de comando.',
      metaTitle: 'Barulho de Chocalho no Motor — Diagnóstico Grátis com IA | Naira Autos',
      metaDescription: 'Barulho de chocalho ou ruído metálico sob o capô? Grave e receba um diagnóstico com IA: protetor térmico, coxins, corrente de comando e mais. Grátis.',
      keywords: ['barulho de chocalho no motor', 'ruído metálico no motor', 'barulho de lata no carro', 'barulho de chocalho ao ligar', 'protetor térmico solto barulho', 'corrente de comando barulhenta', 'barulho no escapamento'],
      h1a: 'Analisador de',
      h1b: 'Chocalho no Motor',
      intro: 'Um chocalho metálico pode ser um simples parafuso solto ou a corrente de comando. Grave e descubra o que é.',
      schemaDescription: 'Ferramenta gratuita com IA que diagnostica barulho de chocalho ou ruído metálico do motor a partir de uma gravação.',
      sections: [
        {
          h2: 'O que causa barulho de chocalho no motor?',
          paras: [
            'O chocalho é um som metálico solto, como peças vibrando umas nas outras. As causas mais comuns são protetor térmico do escapamento solto, coxins do motor ou do escapamento gastos, parafusos ou fixações frouxas e, em casos mais sérios, a corrente de comando ou seu tensor.',
            'O segredo está em quando acontece: em marcha lenta, ao acelerar, a frio ou só em buracos. Isso ajuda a separar uma peça solta sem importância de um problema de comando.',
          ],
        },
        {
          h2: 'Chocalho na partida: quando se preocupar?',
          paras: [
            'Um chocalho curto na partida a frio, de poucos segundos, pode vir da corrente de comando ou de um tensor sem pressão de óleo. Se acontecer toda vez ou piorar, não ignore: corrente de comando danificada pode terminar numa quebra muito cara.',
          ],
        },
        {
          h2: 'O que você mesmo pode verificar',
          paras: [
            'Com o motor desligado e frio, veja se os protetores térmicos e as fixações do escapamento estão firmes e procure parafusos soltos sob o capô. Se o barulho muda com a rotação ou só aparece em buracos, anote no campo de descrição: é uma pista valiosa.',
          ],
        },
      ],
      exampleTitle: 'Exemplo: um protetor térmico solto',
      exampleText: 'A Honda HR-V da Fernanda fazia um chocalho metálico em certas rotações e ela temia problema no comando. Gravou o som e a ferramenta ligou o barulho a uma peça solta embaixo do carro, não ao motor. O mecânico achou um protetor térmico do escapamento com um parafuso frouxo e resolveu em minutos.',
      reviewedAfter: ', mecânico automotivo. Causas do chocalho conferidas para refletir a prática de oficina.',
      faqTitle: 'Perguntas frequentes sobre barulho de chocalho no motor',
      faqs: [
        { q: 'Por que meu carro faz barulho de chocalho sob o capô?', a: 'Na maioria das vezes, protetor térmico ou fixação solta; também podem ser coxins gastos ou, mais raramente, a corrente de comando.' },
        { q: 'Chocalho na partida é grave?', a: 'Depende. Se dura poucos segundos e não volta, geralmente é menor; se é constante ou piora, pode ser a corrente de comando e precisa de avaliação.' },
        { q: 'Como distinguir chocalho do escapamento do motor?', a: 'O do escapamento costuma mudar com a rotação e se ouve por baixo do carro; o do motor vem do cofre do motor.' },
        { q: 'Posso continuar rodando?', a: 'Se for peça solta e o barulho for leve, em geral sim por pouco tempo. Se suspeitar do comando, evite rodar e procure um mecânico.' },
      ],
    },
  ],
  ui: {
    record: 'Gravar som',
    upload: 'Enviar áudio',
    stop: 'Parar',
    descPlaceholder: 'Opcional: quando acontece? (ex.: só a frio, só ao virar)',
    brand: 'Marca (opcional)',
    model: 'Modelo',
    year: 'Ano',
    analyse: 'Analisar este som',
    analysing: 'Analisando o som...',
    listening: 'Ouvindo a sua gravação...',
    another: 'Analisar outro som',
    noticeTrimmed: 'Este áudio tem {duration} s; na versão gratuita analisamos só os primeiros {cap} s. Áudios mais longos chegarão como opção paga.',
    noticeLong: 'Este áudio tem {duration} s. Recomendamos cortar para {cap} s ou menos antes de enviar.',
    noticeCapped: 'A gravação foi limitada a {cap} s na versão gratuita, o que costuma bastar para uma amostra clara. Áudios mais longos chegarão como opção paga.',
    footnote: 'A versão gratuita analisa os primeiros {cap} segundos de cada áudio. O diagnóstico por IA nem sempre é 100% preciso: use como ponto de partida, não como resposta final. Para freios, direção ou combustível, pare de dirigir e procure um mecânico.',
    disclaimer: 'Diagnóstico gerado por IA com base nos primeiros {cap} segundos de áudio. Nem sempre é 100% preciso e pode deixar passar o que uma avaliação presencial pegaria. Use como ponto de partida, não como resposta final. Para freios, direção ou combustível, pare de dirigir e procure um mecânico qualificado.',
    urgency: { safe: 'Pode dirigir', monitor: 'Fique de olho', urgent: 'Procure um mecânico logo', stop_driving: 'Pare de dirigir agora' },
    prob: { high: 'Alta', medium: 'Média', low: 'Baixa' },
    priority: { immediate: 'Agora', soon: 'Em breve', when_convenient: 'Sem pressa' },
    diy: 'Você mesmo',
    possibleCauses: 'Causas possíveis',
    mostLikelyCause: 'Causa mais provável',
    whatToDo: 'O que fazer',
    betterDiagnosis: 'Para um diagnóstico melhor, tente também',
    partsToInspect: 'Peças para verificar',
    costEstimate: 'Estimativa de custo do conserto',
    confidence: 'Confiança',
    costFrom: 'A partir de {amount}',
    costUpTo: 'Até {amount}',
    errors: {
      generic: 'Não foi possível analisar. Tente novamente.',
      maxFile: 'Tamanho máximo do arquivo: 20 MB.',
      mic: 'Acesso ao microfone negado. Permita o acesso e tente novamente.',
      no_audio: 'Envie uma gravação do som.',
      too_large: 'O arquivo de áudio é grande demais. Use trechos com menos de 8 MB (cerca de 30 segundos).',
      unavailable: 'O serviço de IA está temporariamente indisponível. Tente novamente em instantes.',
      parse: 'Não foi possível interpretar a resposta da IA. Tente novamente.',
      server: 'Algo deu errado. Tente novamente.',
    },
  },
};
