import type { EngineSoundCopy } from './types';

// Turkish — search-term research: drivers search "motordan gelen sesler",
// "motor tıkırtısı" (ticking: hidrolik külbütör/subap), "motor vuruntu sesi"
// (knock: kol yatağı, piston etek sesi) and "motor şıkırtı sesi" (rattling).
export const tr: EngineSoundCopy = {
  lang: 'tr',
  locale: 'tr_TR',
  dir: 'ltr',
  homeHref: '/ana-sayfa',
  homeLabel: 'Ana Sayfa',
  hubHref: '/araclar',
  hubLabel: 'Araçlar',
  backLabel: 'Araçlara dön',
  slug: 'motor-sesi-analizi',
  metaTitle: 'Motor Sesi Analizi — Ücretsiz Yapay Zekâ ile Ses Teşhisi | Naira Autos',
  metaDescription: 'Motor sesini kaydedin veya yükleyin, olası arıza nedenini anında yapay zekâ ile öğrenin: tıkırtı, vuruntu, şıkırtı ve daha fazlası. Ücretsiz, üyelik gerekmez.',
  keywords: ['motordan gelen sesler', 'motor sesi', 'motor tıkırtısı', 'motor vuruntu sesi', 'motor şıkırtı sesi', 'motor sesi arıza teşhisi', 'motor sesi analizi', 'motordan tık tık sesi gelmesi'],
  ogDescription: 'Motor sesini kaydedin veya yükleyin, olası arıza nedenini anında yapay zekâ ile öğrenin.',
  toolName: 'Motor Sesi Analizi',
  schemaDescription: 'Motor sesi kaydından araç arızalarını teşhis eden ücretsiz yapay zekâ aracı.',
  badge: 'Ücretsiz Araç',
  verified: 'Son kontrol: Eylül 2026',
  h1a: 'Motor Sesi',
  h1b: 'Analizi',
  intro: 'Aracınızın çıkardığı sesi kaydedin veya yükleyin, anında yapay zekâ teşhisi alın: olası nedenler, aciliyet düzeyi ve tahmini tamir maliyeti.',
  pickerEyebrow: 'Hangi sesi duyuyorsunuz?',
  pickerTitle: 'En yakın olanı seçin',
  pickerCta: 'Bu sesi teşhis et →',
  pickerNote: 'Hangisine benzediğinden emin değil misiniz? Yukarıdaki kayıt aracı her türlü motor sesini analiz eder; önce kategori seçmeniz gerekmez.',
  sections: [
    {
      h2: 'Motor sesi analizi nedir?',
      paras: [
        'Deneyimli bir usta, kaputu açmadan sadece motor sesine bakarak arızanın ne olduğunu çoğu zaman anlayabilir. Bu araç aynı işi yapay zekâ ile yapar: aracınızın sesini kaydedersiniz veya yüklersiniz, yapay zekâ da en olası nedeni belirler; tıpkı bir ustanın kulakla teşhis koyması gibi.',
        'Yukarıdaki üç sesle sınırlı değildir; ıslık, gıcırtı, uğultu, sürtünme veya tıklama gibi her türlü olağan dışı motor sesinde çalışır. Kaydedebiliyorsanız yapay zekâ teşhis etmeyi dener. Kısa bir açıklama (örneğin “sadece soğukken”) ile marka ve modeli eklerseniz sonuç daha isabetli olur.',
      ],
    },
    {
      h2: 'Motor sesini neden ciddiye almalısınız?',
      paras: [
        'Motorda yeni bir ses nadiren sebepsiz çıkar. Tıkırtı, vuruntu veya şıkırtı neredeyse her zaman bir şeyin değiştiğini gösterir: aşınan bir parça, azalan motor yağı ya da gevşeyen bir bağlantı. Bazı sesler zararsızdır, ama bazıları kol yatağı vuruntusu gibi hızla kötüleşen arızaların habercisidir.',
        'Sesi kaydedip ilk değerlendirmeyi almak hiçbir şeye mal olmaz ve bir dakikadan az sürer. Küçük bir arızanın pahalı bir tamire dönüşmesini beklemekten çoğu zaman çok daha ucuzdur.',
      ],
    },
    {
      h2: 'Forumlarda belirti aramaktan farkı',
      paras: [
        'İnternette bir belirtiyi aradığınızda genellikle o sese yol açabilecek her şeyin uzun ve genel bir listesi çıkar; bilgi edinmek için yararlıdır ama aracınızda tam olarak ne olduğunu anlamak için pek değil. Burada analiz sizin kaydınızdan ve eklediğiniz bilgilerden yola çıkar, en olası nedenleri ve aciliyeti gösterir.',
        'Servisteki muayenenin yerini tutmaz. Bunu, tahmine para harcamadan önce yola devam edip edemeyeceğinizi ve ustaya neyi kontrol ettirmeniz veya sormanız gerektiğini öğrenmek için hızlı ve ücretsiz bir ilk adım olarak düşünün.',
      ],
    },
  ],
  tipsTitle: 'Teşhis edilebilir bir kayıt için ipuçları',
  tips: [
    'Güvenli olduğu ölçüde ses kaynağına yaklaşın: motor sesleri için motor bölmesine, fren veya süspansiyon şüphesinde tekerleğin yanına.',
    'Radyoyu kapatın ve camları kapatın ki rüzgâr ve trafik gürültüsü sesi bastırmasın.',
    'Sesin en net olduğu anı kaydedin: hidrolik külbütör tıkırtısı için soğuk çalıştırmada, vuruntu için gaza basarken, şıkırtı için çukur veya kasisten geçerken.',
    'Sesin ne zaman çıktığını (sadece soğukken, sadece dönüşlerde, sadece yük altında) not edin; açıklama alanı yapay zekânın teşhisi daraltmasına yardımcı olur.',
  ],
  exampleTitle: 'Örnek: Ciddi olmayan soğuk çalıştırma tıkırtısı',
  exampleText: 'Murat’ın Renault Clio’su her sabah çalıştırınca tıkırdıyor, motor ısındıktan bir iki dakika sonra ses kayboluyordu. Yataklardan şüphelenen Murat 15 saniyelik bir kayıt alıp bu araçla analiz etti. Ses örüntüsü, kol yatağını değil, yağı henüz soğuk olan hidrolik külbütörleri işaret ediyordu. Yağ seviyesine baktı, düşüktü; yağı değiştirdikten sonra ses kayboldu.',
  reviewedBefore: 'İnceleyen:',
  reviewedAfter: ', otomobil teknisyeni. Ses kategorileri atölye uygulamasına uygunluk açısından kontrol edilmiştir.',
  faqTitle: 'Motor sesi analizi hakkında sık sorulan sorular',
  faqs: [
    { q: 'Motor sesi analizi nedir?', a: 'Motor sesi kaydını dinleyip olası nedeni yapay zekâ ile belirleyen bir araçtır; tıpkı ustanın kaputu açmadan kulakla teşhis koyması gibi.' },
    { q: 'Hangi motor seslerini teşhis edebilir?', a: 'Tıkırtı, vuruntu, şıkırtı, gıcırtı, sürtünme, ıslık, uğultu ve çoğu olağan dışı ses. Kaydedebiliyorsanız yapay zekâ teşhis etmeyi dener.' },
    { q: 'Kayıt ne kadar uzun olmalı?', a: 'Ücretsiz sürüm her kaydın ilk 30 saniyesini analiz eder; bu genellikle net bir teşhis için yeterlidir.' },
    { q: 'Teşhis her zaman doğru mu?', a: 'Hayır. İyi bir başlangıç noktasıdır, kesin cevap değildir; yerinde muayenenin yakalayacağı şeyleri kaçırabilir. Ses fren, direksiyon veya yakıtla ilgiliyse aracı kullanmayı bırakın ve servise gidin.' },
    { q: 'Ücretsiz mi?', a: 'Evet, ücretsiz ve üyeliksiz. 30 saniyeden uzun kayıtlar ileride ücretli seçenek olarak sunulacak.' },
  ],
  relatedTitle: 'Daha fazla ücretsiz araç',
  relatedLabels: { mechanic: 'Sanal Usta', value: 'Arabam Ne Kadar Eder?', vin: 'Şasi Numarası Sorgulama' },
  subs: [
    {
      key: 'ticking',
      slug: 'motor-tikirtisi',
      navLabel: 'Motor tıkırtısı',
      cardDesc: 'Hafif ve hızlı tık-tık sesi: çoğunlukla hidrolik külbütör, enjektör veya subap mekanizması.',
      metaTitle: 'Motor Tıkırtısı (Tık Tık Sesi) — Ücretsiz Yapay Zekâ Teşhisi | Naira Autos',
      metaDescription: 'Motordan tıkırtı mı geliyor? Sesi kaydedin, yapay zekâ teşhisini alın: hidrolik külbütör, yağ eksikliği, enjektör ve daha fazlası. Ücretsiz, üyelik gerekmez.',
      keywords: ['motor tıkırtısı', 'motordan tık tık sesi gelmesi', 'soğukken motor tıkırtısı', 'hidrolik külbütör sesi', 'motor tıkırtı sebepleri', 'dizel motor tıkırtısı', 'rölantide tıkırtı'],
      h1a: 'Motor Tıkırtısı',
      h1b: 'Analizi',
      intro: 'Hafif ve düzenli bir tıkırtının nedeni çoğu zaman basittir. Kaydedin, yağ meselesi mi yoksa daha ciddi bir şey mi öğrenin.',
      schemaDescription: 'Motor tıkırtısını ses kaydından teşhis eden ücretsiz yapay zekâ aracı.',
      sections: [
        {
          h2: 'Motordan tıkırtı sesi neden gelir?',
          paras: [
            'Tıkırtı, motorun ritmini izleyen hafif ve hızlı bir metal sesidir. En yaygın nedenler: hidrolik külbütörler veya subap boşluğu, düşük ya da eskimiş motor yağı, tıkırdayan enjektörler (belli ölçüde normaldir) ve daha nadiren aşınmış triger zinciri veya gergi.',
            'Sesin ne zaman çıktığı önemli bir ipucudur: motor ısınınca kaybolan tıkırtı, devirle birlikte süren veya artan sese göre genellikle daha az ciddidir.',
          ],
        },
        {
          h2: 'Sadece soğuk çalıştırmada tıkırtı: Ciddi mi?',
          paras: [
            'Birçok motor soğuk çalıştırmada kısa süre tıkırdar, çünkü yağın külbütörlere ulaşması birkaç saniye sürer. Ses bir iki dakikada kayboluyorsa ve yağ seviyesi doğruysa genellikle endişelenmeye gerek yoktur, ama gözlemleyin.',
            'Motor ısındıktan sonra da sürüyorsa, zamanla kötüleşiyorsa veya güç kaybı ya da yağ ikaz lambası eşlik ediyorsa ertelemeyin: yağ seviyesini hemen kontrol edin ve aracı baktırın.',
          ],
        },
        {
          h2: 'Servise gitmeden önce neleri kontrol etmelisiniz?',
          paras: [
            'Motor soğukken ve araç düz zemindeyken yağ seviyesine bakın; yağın çok koyu veya çok yoğun olup olmadığını kontrol edin. Sesin devirle değişip değişmediğine dikkat edin: motorla birlikte hızlanıyorsa motorun üst kısmından, araç hızını izliyorsa başka bir yerden geliyor olabilir.',
          ],
        },
      ],
      exampleTitle: 'Örnek: Yağ ile çözülen tıkırtı',
      exampleText: 'Elif, aylardır yağ seviyesine bakmadığı Fiat Egea’sında sürekli bir tıkırtı fark etti. Sesi kaydetti; araç motorun üst kısmında yetersiz yağlamaya işaret etti ve önce seviyenin kontrol edilmesini önerdi. Yağ neredeyse minimumdaydı; yağ ve filtre değişiminden sonra ses kayboldu.',
      reviewedAfter: ', otomobil teknisyeni. Tıkırtı nedenleri atölye uygulamasına uygunluk açısından kontrol edilmiştir.',
      faqTitle: 'Motor tıkırtısı hakkında sık sorulan sorular',
      faqs: [
        { q: 'Motorum neden tıkırdıyor?', a: 'En sık neden, külbütör ve subapları etkileyen yağ eksikliği veya bozulmuş yağdır; enjektörler, triger zinciri veya gevşek bir parça da olabilir.' },
        { q: 'Soğuk çalıştırmada tıkırdaması normal mi?', a: 'Motor ısınınca kaybolan kısa bir tıkırtı birçok motorda yaygındır. Daha uzun sürerse veya geri gelirse yağı kontrol edin.' },
        { q: 'Bu sesle araç kullanmaya devam edebilir miyim?', a: 'Yağ seviyesi doğruysa ve ses hafifse genellikle kısa süre evet, ama yakında baktırın. Yağ lambası yanıyorsa veya güç kaybı varsa durun.' },
        { q: 'Hidrolik külbütör nedir?', a: 'Eksantrik milinin hareketini supaplara ileten parçalardır. Yağlaması zayıfsa veya aşınmışsa karakteristik bir tıkırtı çıkarırlar.' },
      ],
    },
    {
      key: 'knocking',
      slug: 'motor-vuruntu-sesi',
      navLabel: 'Motor vuruntu sesi',
      cardDesc: 'Daha tok ve ağır bir vuruş: yakıt kaynaklı olabilir ya da ciddi bir yatak sorunu.',
      metaTitle: 'Motor Vuruntu Sesi — Ücretsiz Yapay Zekâ Teşhisi | Naira Autos',
      metaDescription: 'Motorda vuruntu sesi mi var? Sesi kaydedin, yapay zekâ teşhisini alın: kol yatağı vuruntusu, detonasyon, enjektör ve daha fazlası. Ücretsiz, üyelik gerekmez.',
      keywords: ['motor vuruntu sesi', 'motorda vuruntu', 'kol yatağı vuruntusu', 'piston etek sesi', 'gaza basınca vuruntu', 'dizel motor vuruntu', 'motor vuruntu sebepleri'],
      h1a: 'Motor Vuruntu Sesi',
      h1b: 'Analizi',
      intro: 'Tok ve ağır bir vuruntuyu hafife almayın. Kaydedin, yakıt kaynaklı mı yoksa daha mekanik bir sorun mu öğrenin.',
      schemaDescription: 'Motor vuruntu sesini ses kaydından teşhis eden ücretsiz yapay zekâ aracı.',
      sections: [
        {
          h2: 'Motorda vuruntu sesi neden olur?',
          paras: [
            'Vuruntu, tıkırtıdan bir kademe ciddidir: daha tok, daha ağırdır ve genellikle yükle ya da devirle artar. Başlıca nedenler: düşük oktan veya karbon birikimi yüzünden düzensiz yanma (detonasyon), aşınmış kol veya ana yatakları, arızalı dizel enjektör ya da alternatör kasnağı gibi gevşemiş bir yardımcı parça.',
            'Zamanlama çok önemlidir: yakıt aldıktan hemen sonra başlayan vuruntu yakıtı işaret eder; yakıttan bağımsız olarak haftalar içinde yavaş yavaş artan vuruntu ise daha çok yatak aşınmasını işaret eder.',
          ],
        },
        {
          h2: 'Kol yatağı vuruntusu: Ciddiye alınması gereken',
          paras: [
            'Kol yatağı vuruntusu, aşınmış biyel yatağındaki aşırı boşluktan kaynaklanan tok ve ritmik bir sestir. Devir arttıkça yükselir, bazen rölantiden çok yük altında daha net duyulur. Yakıt kaynaklı vuruntunun aksine benzin değiştirmekle düzelmez ve kullanmaya devam etmek motorun ciddi şekilde zarar görmesiyle sonuçlanabilir.',
          ],
        },
        {
          h2: 'Kötü yakıt motorda vuruntuya yol açar mı?',
          paras: [
            'Evet. Motorun istediğinden düşük oktanlı yakıt kullanmak detonasyona yol açabilir; gaza basarken metalik bir tıkırtı gibi duyulur. Genellikle mekanik vuruntudan daha hafiftir ve daha iyi yakıt veya enjeksiyon sisteminin temizliğiyle sıklıkla geçer.',
          ],
        },
        {
          h2: 'Dizel motorlarda vuruntu',
          paras: [
            'Dizel motorlar yapıları gereği benzinlilerden daha gürültülüdür; bu yüzden yeni bir vuruntuyu fark etmek zordur, ama fark ettiğinizde dikkate almaya değer. Yeni başladıysa veya artıyorsa enjektörler sık görülen bir nedendir. Kaydedin ve motorunuzun alışılmış sesiyle karşılaştırın.',
          ],
        },
      ],
      exampleTitle: 'Örnek: Sorun yatak değil, yakıttı',
      exampleText: 'Burak’ın Hyundai i20’si, daha önce hiç kullanmadığı bir istasyondan yakıt aldıktan hemen sonra gaza basınca vuruntu yapmaya başladı. Kilometresi nedeniyle yataklardan korkan Burak, pahalı bir teşhise para harcamadan önce sesi kaydetti. Örüntü yakıt kaynaklı detonasyonla uyumluydu; depoyu daha yüksek oktanlı benzinle doldurunca vuruntu kayboldu.',
      reviewedAfter: ', otomobil teknisyeni. Vuruntu türleri ve nedenleri atölye uygulamasına uygunluk açısından kontrol edilmiştir.',
      faqTitle: 'Motor vuruntu sesi hakkında sık sorulan sorular',
      faqs: [
        { q: 'Motorum gaza basınca neden vuruntu yapıyor?', a: 'Düşük oktanlı yakıtın yol açtığı detonasyon, aşınmış kol yatakları, arızalı dizel enjektör veya gevşek bir yardımcı parça olabilir. Ne zaman çıktığı önemli bir ipucudur.' },
        { q: 'Motor vuruntusu her zaman ciddi mi?', a: 'Her zaman değil, ama tıkırtıdan daha fazla dikkat ister. Yakıt kaynaklısı çoğu zaman yönetilebilir; kol yatağı vuruntusu ise kötüleşen gerçek bir mekanik sorundur.' },
        { q: 'Kol yatağı vuruntusu nedir?', a: 'Aşınmış biyel yatağındaki boşluktan kaynaklanan tok ve ritmik bir ses. Devirle yükselir, yakıt değiştirmekle düzelmez, ne kadar kullanırsanız motora o kadar zarar verir.' },
        { q: 'Dizel motorum neden vuruntu yapıyor?', a: 'Dizeller tasarımları gereği daha gürültülüdür, ama yeni veya artan bir vuruntu çoğunlukla enjektörleri işaret eder.' },
        { q: 'Kötü yakıt vuruntuya yol açar mı?', a: 'Evet, düşük oktanlı yakıt gaza basarken detonasyona yol açabilir. Genellikle mekanik vuruntudan daha hafif ve metaliktir, daha iyi yakıtla düzelir.' },
      ],
    },
    {
      key: 'rattling',
      slug: 'motor-sikirti-sesi',
      navLabel: 'Motor şıkırtı sesi',
      cardDesc: 'Gevşek, metalik şıkırtı: çoğunlukla motor takozu, ısı kalkanı veya triger zinciri.',
      metaTitle: 'Motor Şıkırtı Sesi — Ücretsiz Yapay Zekâ Teşhisi | Naira Autos',
      metaDescription: 'Kaputun altından şıkırtı mı geliyor? Sesi kaydedin, yapay zekâ teşhisini alın: ısı kalkanı, motor takozu, triger zinciri ve daha fazlası. Ücretsiz.',
      keywords: ['motor şıkırtı sesi', 'motordan şıkırtı', 'motor takırtı sesi', 'ısı kalkanı şıkırtı', 'triger zinciri sesi', 'egzoz şıkırtı sesi', 'motor takozu sesi'],
      h1a: 'Motor Şıkırtı Sesi',
      h1b: 'Analizi',
      intro: 'Metalik bir şıkırtı, gevşek bir cıvata da olabilir triger zinciri de. Kaydedin ve ne olduğunu öğrenin.',
      schemaDescription: 'Motor şıkırtı sesini ses kaydından teşhis eden ücretsiz yapay zekâ aracı.',
      sections: [
        {
          h2: 'Motordan şıkırtı sesi neden gelir?',
          paras: [
            'Şıkırtı, parçaların birbirine çarpıp titreştiği gibi gevşek, metalik bir sestir. En sık nedenler: egzoz ısı kalkanının gevşemesi, aşınmış motor veya egzoz takozları, gevşek cıvata ve bağlantılar ve daha ciddi durumlarda triger zinciri ya da gergisi.',
            'Anahtar, sesin ne zaman çıktığıdır: rölantide mi, gaza basarken mi, soğukken mi, yoksa sadece çukurlarda mı? Bu, önemsiz bir gevşek parçayı triger zinciri sorunundan ayırmaya yardımcı olur.',
          ],
        },
        {
          h2: 'Çalıştırmada şıkırtı: Ne zaman endişelenmeli?',
          paras: [
            'Soğuk çalıştırmada birkaç saniye süren kısa bir şıkırtı, yağ basıncı yetersiz kalan triger zincirinden veya gergiden gelebilir. Her seferinde tekrarlıyorsa veya kötüleşiyorsa göz ardı etmeyin: hasarlı bir triger zinciri çok pahalı bir arızayla sonuçlanabilir.',
          ],
        },
        {
          h2: 'Kendiniz neleri kontrol edebilirsiniz?',
          paras: [
            'Motor kapalı ve soğukken ısı kalkanlarının ve egzoz bağlantılarının oynamadığını kontrol edin, kaput altında gevşek cıvata arayın. Ses devirle değişiyorsa veya sadece çukurlarda çıkıyorsa açıklama alanına not edin; değerli bir ipucudur.',
          ],
        },
      ],
      exampleTitle: 'Örnek: Gevşek bir ısı kalkanı',
      exampleText: 'Selin’in Honda CR-V’si belli devirlerde metalik bir şıkırtı yapıyordu ve Selin triger konusunda endişeliydi. Sesi kaydetti; araç sesi motorla değil, aracın altındaki gevşek bir parçayla ilişkilendirdi. Usta, egzoz ısı kalkanının cıvatasının gevşediğini buldu ve birkaç dakikada sıktı.',
      reviewedAfter: ', otomobil teknisyeni. Şıkırtı nedenleri atölye uygulamasına uygunluk açısından kontrol edilmiştir.',
      faqTitle: 'Motor şıkırtı sesi hakkında sık sorulan sorular',
      faqs: [
        { q: 'Aracım kaputun altından neden şıkırdıyor?', a: 'En sık gevşek bir ısı kalkanı veya bağlantı; aşınmış takozlar ya da daha nadiren triger de olabilir.' },
        { q: 'Çalıştırmada şıkırtı ciddi mi?', a: 'Duruma bağlı. Birkaç saniye sürüp tekrarlamıyorsa genellikle önemsizdir; sürekliyse veya kötüleşiyorsa triger zinciri olabilir ve baktırılmalıdır.' },
        { q: 'Egzoz şıkırtısını motordan nasıl ayırırım?', a: 'Egzoz şıkırtısı çoğunlukla devirle değişir ve aracın altından duyulur; motorunki motor bölmesinden gelir.' },
        { q: 'Araç kullanmaya devam edebilir miyim?', a: 'Gevşek bir parçaysa ve ses hafifse genellikle kısa süre evet. Triger şüphesi varsa aracı kullanmayın ve ustaya danışın.' },
      ],
    },
  ],
  ui: {
    record: 'Sesi kaydet',
    upload: 'Ses yükle',
    stop: 'Durdur',
    descPlaceholder: 'İsteğe bağlı: Ne zaman oluyor? (örn. sadece soğukken, sadece dönüşlerde)',
    brand: 'Marka (isteğe bağlı)',
    model: 'Model',
    year: 'Yıl',
    analyse: 'Bu sesi analiz et',
    analysing: 'Ses analiz ediliyor...',
    listening: 'Kaydınız dinleniyor...',
    another: 'Başka bir sesi analiz et',
    noticeTrimmed: 'Bu kayıt {duration} sn uzunluğunda; ücretsiz sürümde yalnızca ilk {cap} sn analiz edilir. Daha uzun kayıtlar ücretli seçenek olarak gelecek.',
    noticeLong: 'Bu kayıt {duration} sn uzunluğunda. Yüklemeden önce {cap} sn veya daha kısa olacak şekilde kırpmanızı öneririz.',
    noticeCapped: 'Ücretsiz sürümde kayıt {cap} sn ile sınırlandı; bu genellikle net bir örnek için yeterlidir. Daha uzun kayıtlar ücretli seçenek olarak gelecek.',
    footnote: 'Ücretsiz sürüm her kaydın ilk {cap} saniyesini analiz eder. Yapay zekâ teşhisi her zaman %100 doğru değildir; kesin cevap değil, başlangıç noktası olarak görün. Fren, direksiyon veya yakıtla ilgiliyse aracı kullanmayı bırakıp bir ustaya gidin.',
    disclaimer: 'İlk {cap} saniyelik ses kaydına dayanan yapay zekâ teşhisidir. Her zaman %100 doğru değildir ve yerinde muayenenin yakalayacağı şeyleri kaçırabilir. Kesin cevap değil, başlangıç noktası olarak görün. Fren, direksiyon veya yakıtla ilgiliyse aracı kullanmayı bırakıp nitelikli bir ustaya gidin.',
    urgency: { safe: 'Kullanılabilir', monitor: 'Yakından izleyin', urgent: 'Yakında ustaya gidin', stop_driving: 'Hemen kullanmayı bırakın' },
    prob: { high: 'Yüksek', medium: 'Orta', low: 'Düşük' },
    priority: { immediate: 'Hemen', soon: 'Yakında', when_convenient: 'Fırsatta' },
    diy: 'Kendiniz',
    possibleCauses: 'Olası nedenler',
    mostLikelyCause: 'En olası neden',
    whatToDo: 'Ne yapmalı',
    betterDiagnosis: 'Daha iyi teşhis için şunları da deneyin',
    partsToInspect: 'Kontrol edilecek parçalar',
    costEstimate: 'Tahmini tamir maliyeti',
    confidence: 'Güvenilirlik',
    costFrom: '{amount} ve üzeri',
    costUpTo: '{amount} kadar',
    errors: {
      generic: 'Analiz başarısız oldu. Lütfen tekrar deneyin.',
      maxFile: 'Maksimum dosya boyutu 20 MB.',
      mic: 'Mikrofon erişimi reddedildi. Lütfen erişime izin verip tekrar deneyin.',
      no_audio: 'Lütfen sesin bir kaydını ekleyin.',
      too_large: 'Ses dosyası çok büyük. Lütfen 8 MB’ın altında (yaklaşık 30 saniye) kayıtlar kullanın.',
      unavailable: 'Yapay zekâ hizmeti geçici olarak kullanılamıyor. Lütfen biraz sonra tekrar deneyin.',
      parse: 'Yapay zekâ yanıtı işlenemedi. Lütfen tekrar deneyin.',
      server: 'Bir şeyler ters gitti. Lütfen tekrar deneyin.',
    },
  },
};
