import type { EngineSoundCopy } from './types';

// Vietnamese — search-term research: drivers search "tiếng động cơ lạ / bất
// thường", "tiếng gõ cốc cốc / tách tách" (ticking: thiếu dầu, con đội),
// "kích nổ / tiếng gõ động cơ / bạc biên" (knock) and "tiếng lạch cạch" (rattling).
export const vi: EngineSoundCopy = {
  lang: 'vi',
  locale: 'vi_VN',
  dir: 'ltr',
  homeHref: '/trang-chu',
  homeLabel: 'Trang chủ',
  hubHref: '/cong-cu',
  hubLabel: 'Công cụ',
  backLabel: 'Quay lại công cụ',
  slug: 'phan-tich-tieng-dong-co',
  metaTitle: 'Phân Tích Tiếng Động Cơ — Chẩn Đoán AI Miễn Phí Qua Âm Thanh | Naira Autos',
  metaDescription: 'Ghi âm hoặc tải lên tiếng động cơ xe và nhận ngay chẩn đoán AI về nguyên nhân có thể: tiếng tách tách, tiếng gõ, tiếng lạch cạch và nhiều hơn nữa. Miễn phí, không cần đăng ký.',
  keywords: ['tiếng động cơ lạ', 'tiếng động cơ bất thường', 'tiếng gõ động cơ', 'tiếng tách tách động cơ', 'tiếng lạch cạch động cơ', 'kích nổ động cơ', 'chẩn đoán tiếng động cơ', 'phân tích tiếng động cơ'],
  ogDescription: 'Ghi âm hoặc tải lên tiếng động cơ xe và nhận ngay chẩn đoán AI về nguyên nhân có thể.',
  toolName: 'Phân Tích Tiếng Động Cơ',
  schemaDescription: 'Công cụ AI miễn phí chẩn đoán sự cố xe từ bản ghi âm tiếng động cơ.',
  badge: 'Công cụ miễn phí',
  verified: 'Kiểm tra lần cuối: Tháng 9/2026',
  h1a: 'Phân Tích',
  h1b: 'Tiếng Động Cơ',
  intro: 'Ghi âm hoặc tải lên tiếng xe của bạn đang phát ra và nhận ngay chẩn đoán AI: nguyên nhân có thể, mức độ khẩn cấp và chi phí sửa chữa dự kiến.',
  pickerEyebrow: 'Bạn đang nghe tiếng gì?',
  pickerTitle: 'Chọn tiếng gần giống nhất',
  pickerCta: 'Chẩn đoán tiếng này →',
  pickerNote: 'Không chắc tiếng nào giống nhất? Công cụ ghi âm ở trên phân tích được mọi tiếng động cơ, bạn không cần chọn nhóm trước.',
  sections: [
    {
      h2: 'Phân tích tiếng động cơ là gì?',
      paras: [
        'Một thợ máy giàu kinh nghiệm thường đoán được xe hỏng gì chỉ qua tiếng động cơ, thậm chí trước khi mở nắp capo. Công cụ này làm điều tương tự bằng AI: bạn ghi âm hoặc tải lên đoạn âm thanh xe phát ra, AI sẽ xác định nguyên nhân có khả năng cao nhất, giống như thợ chẩn đoán bằng tai.',
        'Công cụ hoạt động với mọi tiếng động cơ bất thường, không chỉ ba loại ở trên: tiếng rít, tiếng ù, tiếng mài, tiếng click. Nếu bạn ghi âm được, AI sẽ cố gắng chẩn đoán. Hãy thêm mô tả ngắn (ví dụ “chỉ khi máy nguội”) cùng hãng và đời xe để kết quả chính xác hơn.',
      ],
    },
    {
      h2: 'Vì sao không nên bỏ qua tiếng động cơ lạ',
      paras: [
        'Tiếng lạ trong động cơ hiếm khi tự nhiên xuất hiện. Tiếng tách tách, tiếng gõ hay tiếng lạch cạch gần như luôn báo hiệu có gì đó thay đổi: chi tiết bị mòn, dầu máy thiếu hoặc một bộ phận bị lỏng. Một số tiếng vô hại, nhưng có tiếng cảnh báo hư hỏng nặng nhanh, như tiếng gõ của bạc biên.',
        'Ghi âm và nhận đánh giá ban đầu không tốn đồng nào và mất chưa đầy một phút. Cách này thường rẻ hơn nhiều so với chờ một lỗi nhỏ biến thành đợt sửa chữa lớn.',
      ],
    },
    {
      h2: 'Khác gì so với tìm triệu chứng trên diễn đàn',
      paras: [
        'Tìm triệu chứng trên mạng thường cho ra danh sách dài và chung chung về mọi thứ có thể gây ra tiếng đó: hữu ích để tham khảo nhưng ít giúp biết xe của bạn thực sự bị gì. Ở đây, phân tích xuất phát từ chính đoạn ghi âm và thông tin bạn nhập, rồi chỉ ra nguyên nhân khả dĩ nhất cùng mức độ khẩn cấp.',
        'Công cụ không thay thế việc kiểm tra tại gara. Hãy xem đây là bước đầu nhanh và miễn phí để biết xe còn chạy được không và cần kiểm tra hay hỏi thợ điều gì, trước khi bạn tốn tiền cho một phỏng đoán.',
      ],
    },
  ],
  tipsTitle: 'Mẹo ghi âm để chẩn đoán được',
  tips: [
    'Đưa thiết bị lại gần nguồn tiếng động trong điều kiện an toàn: gần khoang máy với tiếng động cơ, gần bánh xe nếu nghi ngờ phanh hoặc hệ thống treo.',
    'Tắt radio và đóng cửa kính để gió và tiếng ồn đường phố không át mất âm thanh.',
    'Ghi âm lúc tiếng rõ nhất: khi khởi động máy nguội với tiếng tách tách của con đội, khi tăng ga với tiếng gõ, khi qua ổ gà với tiếng lạch cạch.',
    'Ghi lại thời điểm xuất hiện (chỉ khi nguội, chỉ khi đánh lái, chỉ khi chịu tải): ô mô tả giúp AI thu hẹp chẩn đoán.',
  ],
  exampleTitle: 'Ví dụ: tiếng tách tách lúc máy nguội không nghiêm trọng',
  exampleText: 'Chiếc Toyota Vios của anh Minh phát ra tiếng tách tách mỗi sáng khi nổ máy, rồi biến mất sau một hai phút khi máy nóng. Lo bạc biên có vấn đề, anh ghi âm 15 giây và đưa vào công cụ này. Mẫu âm thanh chỉ về con đội thủy lực khi dầu còn nguội, không phải sự cố bạc biên. Anh kiểm tra thì dầu máy thấp; sau khi thay dầu, tiếng động biến mất.',
  reviewedBefore: 'Kiểm duyệt bởi',
  reviewedAfter: ', kỹ thuật viên ô tô. Các nhóm tiếng động được kiểm tra để phù hợp với thực tế tại gara.',
  faqTitle: 'Câu hỏi thường gặp về phân tích tiếng động cơ',
  faqs: [
    { q: 'Phân tích tiếng động cơ là gì?', a: 'Công cụ nghe bản ghi âm tiếng động cơ của bạn và xác định nguyên nhân có thể bằng AI, giống như thợ chẩn đoán bằng tai trước khi mở capo.' },
    { q: 'Công cụ chẩn đoán được những tiếng động cơ nào?', a: 'Tiếng tách tách, tiếng gõ, tiếng lạch cạch, tiếng rít, tiếng mài, tiếng ù và hầu hết các tiếng bất thường. Nếu ghi âm được, AI sẽ cố gắng chẩn đoán.' },
    { q: 'Bản ghi âm cần dài bao lâu?', a: 'Bản miễn phí phân tích 30 giây đầu của mỗi đoạn, thường đủ cho một chẩn đoán rõ ràng.' },
    { q: 'Chẩn đoán có luôn chính xác không?', a: 'Không. Đây là điểm khởi đầu tốt chứ không phải câu trả lời cuối cùng, và có thể bỏ sót điều mà việc kiểm tra trực tiếp sẽ phát hiện. Nếu tiếng động liên quan đến phanh, lái hoặc nhiên liệu, hãy ngừng lái và đến gara.' },
    { q: 'Có miễn phí không?', a: 'Có, miễn phí và không cần đăng ký. Đoạn ghi âm dài hơn 30 giây dự kiến sẽ là tùy chọn trả phí sau này.' },
  ],
  relatedTitle: 'Thêm công cụ miễn phí',
  relatedLabels: { mechanic: 'Thợ Máy Ảo', value: 'Xe Của Tôi Đáng Giá Bao Nhiêu?', vin: 'Kiểm Tra Số VIN' },
  subs: [
    {
      key: 'ticking',
      slug: 'tieng-tach-tach-dong-co',
      navLabel: 'Tiếng tách tách động cơ',
      cardDesc: 'Tiếng gõ nhẹ, nhanh, tách-tách-tách: thường do con đội, kim phun hoặc cơ cấu xupap.',
      metaTitle: 'Tiếng Tách Tách Động Cơ (Cốc Cốc) — Chẩn Đoán AI Miễn Phí | Naira Autos',
      metaDescription: 'Động cơ kêu tách tách hoặc cốc cốc? Ghi âm và nhận chẩn đoán AI: con đội, thiếu dầu, kim phun và nhiều hơn nữa. Miễn phí, không cần đăng ký.',
      keywords: ['tiếng tách tách động cơ', 'tiếng cốc cốc động cơ', 'động cơ kêu tách tách khi nguội', 'tiếng con đội xupap', 'xe nổ máy có tiếng gõ', 'động cơ diesel kêu tách tách', 'tiếng động cơ thiếu dầu'],
      h1a: 'Phân Tích',
      h1b: 'Tiếng Tách Tách Động Cơ',
      intro: 'Tiếng tách tách nhẹ và đều đặn thường có nguyên nhân đơn giản. Hãy ghi âm và xem đó là chuyện dầu máy hay điều gì nghiêm trọng hơn.',
      schemaDescription: 'Công cụ AI miễn phí chẩn đoán tiếng tách tách của động cơ từ bản ghi âm.',
      sections: [
        {
          h2: 'Nguyên nhân gây tiếng tách tách trong động cơ là gì?',
          paras: [
            'Tiếng tách tách là âm thanh kim loại nhẹ và nhanh, đi theo nhịp động cơ. Nguyên nhân phổ biến nhất là con đội thủy lực hoặc khe hở nhiệt xupap, dầu máy thiếu hoặc đã xuống cấp, kim phun kêu lách tách (bình thường ở một mức độ nhất định) và hiếm hơn là xích cam hoặc bộ căng xích bị mòn.',
            'Thời điểm xuất hiện là manh mối quan trọng: tiếng tách tách mất đi khi máy nóng thường ít nghiêm trọng hơn tiếng kéo dài hoặc to dần theo vòng tua.',
          ],
        },
        {
          h2: 'Chỉ kêu tách tách khi máy nguội: có nghiêm trọng không?',
          paras: [
            'Nhiều động cơ kêu tách tách ngắn khi nguội vì dầu cần vài giây mới lên tới con đội. Nếu tiếng mất trong một hai phút và mức dầu đúng, thường không đáng lo, nhưng hãy theo dõi.',
            'Nếu tiếng vẫn còn khi máy nóng, nặng dần theo thời gian hoặc kèm mất công suất hay đèn báo áp suất dầu, đừng trì hoãn: hãy kiểm tra mức dầu ngay và đưa xe đi kiểm tra.',
          ],
        },
        {
          h2: 'Nên kiểm tra gì trước khi đến gara',
          paras: [
            'Kiểm tra mức dầu khi máy nguội và xe đỗ trên mặt phẳng, xem dầu có quá đen hoặc quá đặc không. Chú ý tiếng có đổi theo vòng tua không: nếu nhanh dần theo động cơ, nguồn ở phần trên máy; nếu theo tốc độ xe, nguyên nhân có thể ở chỗ khác.',
          ],
        },
      ],
      exampleTitle: 'Ví dụ: tiếng tách tách được giải quyết bằng thay dầu',
      exampleText: 'Chị Lan nhận thấy tiếng tách tách liên tục trên chiếc Kia Morning sau nhiều tháng không kiểm tra dầu. Chị ghi âm lại; công cụ chỉ ra bôi trơn không đủ ở phần trên động cơ và khuyên kiểm tra mức dầu trước. Dầu gần chạm mức tối thiểu; sau khi thay dầu và lọc dầu, tiếng động biến mất.',
      reviewedAfter: ', kỹ thuật viên ô tô. Nguyên nhân tiếng tách tách được kiểm tra để phù hợp với thực tế tại gara.',
      faqTitle: 'Câu hỏi thường gặp về tiếng tách tách động cơ',
      faqs: [
        { q: 'Vì sao động cơ của tôi kêu tách tách?', a: 'Phổ biến nhất là thiếu dầu hoặc dầu xuống cấp ảnh hưởng tới con đội và xupap; cũng có thể do kim phun, xích cam hoặc một chi tiết bị lỏng.' },
        { q: 'Kêu tách tách khi nổ máy nguội có bình thường không?', a: 'Tiếng tách tách ngắn mất đi khi máy nóng khá phổ biến ở nhiều động cơ. Nếu kéo dài hoặc quay lại, hãy kiểm tra dầu.' },
        { q: 'Tôi có thể tiếp tục lái xe với tiếng này không?', a: 'Nếu mức dầu đúng và tiếng nhẹ, thường được trong thời gian ngắn, nhưng nên kiểm tra sớm. Nếu đèn dầu sáng hoặc mất công suất, hãy dừng xe.' },
        { q: 'Con đội là gì?', a: 'Chi tiết truyền chuyển động từ trục cam tới xupap. Nếu bôi trơn kém hoặc mòn sẽ phát ra tiếng tách tách đặc trưng.' },
      ],
    },
    {
      key: 'knocking',
      slug: 'tieng-go-dong-co',
      navLabel: 'Tiếng gõ động cơ',
      cardDesc: 'Tiếng gõ trầm và nặng hơn: có thể do nhiên liệu hoặc sự cố bạc biên nghiêm trọng.',
      metaTitle: 'Tiếng Gõ Động Cơ (Kích Nổ) — Chẩn Đoán AI Miễn Phí | Naira Autos',
      metaDescription: 'Động cơ có tiếng gõ? Ghi âm và nhận chẩn đoán AI: gõ bạc biên, kích nổ, kim phun và nhiều hơn nữa. Miễn phí, không cần đăng ký.',
      keywords: ['tiếng gõ động cơ', 'động cơ kích nổ', 'tiếng gõ khi tăng tốc', 'bạc biên kêu', 'động cơ diesel gõ', 'tiếng đập mạnh trong động cơ', 'nguyên nhân tiếng gõ động cơ'],
      h1a: 'Phân Tích',
      h1b: 'Tiếng Gõ Động Cơ',
      intro: 'Tiếng gõ trầm và nặng cần được coi trọng. Hãy ghi âm và xem do nhiên liệu hay một sự cố cơ khí nặng hơn.',
      schemaDescription: 'Công cụ AI miễn phí chẩn đoán tiếng gõ động cơ từ bản ghi âm.',
      sections: [
        {
          h2: 'Nguyên nhân gây tiếng gõ động cơ là gì?',
          paras: [
            'Tiếng gõ nghiêm trọng hơn tiếng tách tách một bậc: trầm hơn, nặng hơn và thường to lên khi tải hoặc vòng tua tăng. Nguyên nhân chính là kích nổ (nhiên liệu cháy không đều do trị số octan thấp hoặc muội than), bạc biên hoặc bạc trục khuỷu mòn, kim phun diesel hỏng hoặc phụ kiện lỏng như puly máy phát.',
            'Thời điểm rất quan trọng: tiếng gõ xuất hiện ngay sau khi đổ xăng chỉ về nhiên liệu; tiếng to dần từ từ qua nhiều tuần, bất kể nhiên liệu, thiên về bạc mòn hơn.',
          ],
        },
        {
          h2: 'Tiếng gõ bạc biên: loại cần coi trọng',
          paras: [
            'Tiếng gõ bạc biên là tiếng gõ trầm có nhịp, do khe hở quá lớn ở bạc biên bị mòn. Tiếng thường to lên khi vòng tua tăng và đôi khi rõ khi có tải hơn là lúc chạy không tải. Khác với tiếng gõ do nhiên liệu, nó không đỡ khi đổi xăng, và tiếp tục chạy có thể dẫn tới hỏng động cơ.',
          ],
        },
        {
          h2: 'Nhiên liệu kém chất lượng có gây tiếng gõ không?',
          paras: [
            'Có. Dùng nhiên liệu có trị số octan thấp hơn mức động cơ yêu cầu có thể gây kích nổ, nghe như tiếng lách cách kim loại khi tăng ga. Tiếng này thường nhẹ hơn tiếng gõ cơ khí và hay biến mất khi dùng nhiên liệu tốt hơn hoặc vệ sinh hệ thống phun.',
          ],
        },
        {
          h2: 'Tiếng gõ ở động cơ diesel',
          paras: [
            'Động cơ diesel vốn ồn hơn động cơ xăng nên tiếng gõ mới khó nhận ra, nhưng đáng chú ý ngay khi bạn nghe thấy. Nếu tiếng mới xuất hiện hoặc nặng dần, kim phun là nguyên nhân thường gặp. Hãy ghi âm và so sánh với tiếng quen thuộc của động cơ.',
          ],
        },
      ],
      exampleTitle: 'Ví dụ: do nhiên liệu, không phải bạc biên',
      exampleText: 'Chiếc Hyundai Accent của anh Hùng bắt đầu gõ khi tăng ga ngay sau khi đổ xăng ở một cây xăng lạ. Với số km đã chạy, anh lo bạc biên và ghi âm lại trước khi trả tiền chẩn đoán. Mẫu âm thanh khớp với kích nổ do nhiên liệu; sau khi đổ đầy xăng có trị số octan cao hơn, tiếng gõ biến mất.',
      reviewedAfter: ', kỹ thuật viên ô tô. Các loại và nguyên nhân tiếng gõ được kiểm tra để phù hợp với thực tế tại gara.',
      faqTitle: 'Câu hỏi thường gặp về tiếng gõ động cơ',
      faqs: [
        { q: 'Vì sao động cơ gõ khi tăng tốc?', a: 'Kích nổ do nhiên liệu octan thấp, bạc biên mòn, kim phun diesel hỏng hoặc phụ kiện lỏng. Thời điểm xuất hiện là manh mối quan trọng.' },
        { q: 'Tiếng gõ động cơ có luôn nghiêm trọng không?', a: 'Không phải lúc nào, nhưng cần thận trọng hơn tiếng tách tách. Tiếng do nhiên liệu thường xử lý được; tiếng gõ bạc biên là sự cố cơ khí thật sự và nặng dần.' },
        { q: 'Tiếng gõ bạc biên là gì?', a: 'Tiếng gõ trầm có nhịp do khe hở ở bạc biên mòn. Tăng theo vòng tua, không đỡ khi đổi nhiên liệu và càng chạy càng hại động cơ.' },
        { q: 'Vì sao động cơ diesel của tôi gõ?', a: 'Diesel ồn hơn theo thiết kế, nhưng tiếng gõ mới hoặc to dần thường chỉ về kim phun.' },
        { q: 'Nhiên liệu kém có gây tiếng gõ không?', a: 'Có, xăng octan thấp có thể gây kích nổ khi tăng ga. Tiếng thường nhẹ và kim loại hơn tiếng gõ cơ khí, và đỡ khi dùng nhiên liệu tốt hơn.' },
      ],
    },
    {
      key: 'rattling',
      slug: 'tieng-lach-cach-dong-co',
      navLabel: 'Tiếng lạch cạch động cơ',
      cardDesc: 'Tiếng kim loại lỏng lẻo lạch cạch: thường do chân máy, tấm chắn nhiệt hoặc xích cam.',
      metaTitle: 'Tiếng Lạch Cạch Động Cơ — Chẩn Đoán AI Miễn Phí | Naira Autos',
      metaDescription: 'Có tiếng lạch cạch dưới nắp capo? Ghi âm và nhận chẩn đoán AI: tấm chắn nhiệt, chân máy, xích cam và nhiều hơn nữa. Miễn phí.',
      keywords: ['tiếng lạch cạch động cơ', 'tiếng lạch cạch dưới nắp capo', 'xe kêu lạch cạch', 'tấm chắn nhiệt lỏng', 'xích cam kêu', 'ống xả kêu lạch cạch', 'chân máy hỏng tiếng ồn'],
      h1a: 'Phân Tích',
      h1b: 'Tiếng Lạch Cạch Động Cơ',
      intro: 'Tiếng lạch cạch kim loại có thể chỉ là một con ốc lỏng, nhưng cũng có thể là xích cam. Hãy ghi âm và xem đó là gì.',
      schemaDescription: 'Công cụ AI miễn phí chẩn đoán tiếng lạch cạch của động cơ từ bản ghi âm.',
      sections: [
        {
          h2: 'Nguyên nhân gây tiếng lạch cạch ở động cơ là gì?',
          paras: [
            'Tiếng lạch cạch là âm thanh kim loại lỏng lẻo, như các chi tiết rung va vào nhau. Nguyên nhân phổ biến là tấm chắn nhiệt ống xả bị lỏng, chân máy hoặc cao su treo ống xả mòn, bu lông và điểm bắt bị lỏng, và ở trường hợp nghiêm trọng hơn là xích cam hoặc bộ căng xích.',
            'Mấu chốt là tiếng xuất hiện khi nào: lúc chạy cầm chừng, khi tăng ga, khi máy nguội hay chỉ khi qua ổ gà. Điều này giúp phân biệt chi tiết lỏng không đáng kể với sự cố xích cam.',
          ],
        },
        {
          h2: 'Lạch cạch khi nổ máy: khi nào nên lo?',
          paras: [
            'Tiếng lạch cạch ngắn vài giây khi khởi động máy nguội có thể đến từ xích cam hoặc bộ căng xích thiếu áp suất dầu. Nếu lặp lại mỗi lần hoặc nặng dần, đừng bỏ qua: xích cam hỏng có thể dẫn tới sự cố rất tốn kém.',
          ],
        },
        {
          h2: 'Những gì bạn có thể tự kiểm tra',
          paras: [
            'Khi tắt máy và để nguội, kiểm tra tấm chắn nhiệt và điểm bắt ống xả có rung lắc không, và tìm bu lông lỏng trong khoang máy. Nếu tiếng đổi theo vòng tua hoặc chỉ xuất hiện khi qua ổ gà, hãy ghi vào ô mô tả: đó là manh mối quý giá.',
          ],
        },
      ],
      exampleTitle: 'Ví dụ: tấm chắn nhiệt bị lỏng',
      exampleText: 'Chiếc Honda CR-V của chị Thảo kêu lạch cạch ở một số vòng tua và chị lo về xích cam. Chị ghi âm lại và công cụ liên hệ tiếng này với một chi tiết lỏng dưới gầm xe, không phải động cơ. Thợ phát hiện tấm chắn nhiệt ống xả có bu lông lỏng và siết lại trong vài phút.',
      reviewedAfter: ', kỹ thuật viên ô tô. Nguyên nhân tiếng lạch cạch được kiểm tra để phù hợp với thực tế tại gara.',
      faqTitle: 'Câu hỏi thường gặp về tiếng lạch cạch động cơ',
      faqs: [
        { q: 'Vì sao xe kêu lạch cạch dưới nắp capo?', a: 'Thường là tấm chắn nhiệt hoặc điểm bắt bị lỏng; cũng có thể là chân máy mòn hoặc hiếm hơn là xích cam.' },
        { q: 'Tiếng lạch cạch khi nổ máy có nghiêm trọng không?', a: 'Tùy trường hợp. Nếu chỉ vài giây và không lặp lại thường nhẹ; nếu liên tục hoặc nặng dần có thể là xích cam và cần kiểm tra.' },
        { q: 'Làm sao phân biệt tiếng ống xả với tiếng động cơ?', a: 'Tiếng ống xả thường đổi theo vòng tua và nghe từ dưới gầm; tiếng động cơ phát ra từ khoang máy.' },
        { q: 'Tôi có thể tiếp tục lái không?', a: 'Nếu là chi tiết lỏng và tiếng nhẹ, thường được trong thời gian ngắn. Nếu nghi ngờ xích cam, hãy tránh lái và hỏi thợ.' },
      ],
    },
  ],
  ui: {
    record: 'Ghi âm',
    upload: 'Tải đoạn âm thanh',
    stop: 'Dừng',
    descPlaceholder: 'Tùy chọn: xảy ra khi nào? (vd: chỉ khi máy nguội, chỉ khi đánh lái)',
    brand: 'Hãng xe (tùy chọn)',
    model: 'Dòng xe',
    year: 'Năm',
    analyse: 'Phân tích âm thanh này',
    analysing: 'Đang phân tích âm thanh...',
    listening: 'Đang nghe bản ghi âm của bạn...',
    another: 'Phân tích âm thanh khác',
    noticeTrimmed: 'Đoạn này dài {duration} giây; bản miễn phí chỉ phân tích {cap} giây đầu. Đoạn dài hơn sẽ có dưới dạng tùy chọn trả phí.',
    noticeLong: 'Đoạn này dài {duration} giây. Chúng tôi khuyên bạn cắt còn {cap} giây hoặc ngắn hơn trước khi tải lên.',
    noticeCapped: 'Bản miễn phí giới hạn ghi âm ở {cap} giây, thường đủ cho một mẫu âm thanh rõ ràng. Đoạn dài hơn sẽ có dưới dạng tùy chọn trả phí.',
    footnote: 'Bản miễn phí phân tích {cap} giây đầu của mỗi đoạn. Chẩn đoán AI không phải lúc nào cũng chính xác 100%: hãy xem đây là điểm khởi đầu chứ không phải câu trả lời cuối cùng. Với phanh, lái hoặc nhiên liệu, hãy ngừng lái và đến gặp thợ.',
    disclaimer: 'Chẩn đoán do AI tạo ra dựa trên {cap} giây đầu của âm thanh. Không phải lúc nào cũng chính xác 100% và có thể bỏ sót điều mà việc kiểm tra trực tiếp sẽ phát hiện. Hãy xem đây là điểm khởi đầu chứ không phải câu trả lời cuối cùng. Với phanh, lái hoặc nhiên liệu, hãy ngừng lái và đến gặp thợ có chuyên môn.',
    urgency: { safe: 'Có thể lái xe', monitor: 'Theo dõi sát', urgent: 'Sớm đưa xe đến gara', stop_driving: 'Ngừng lái ngay lập tức' },
    prob: { high: 'Cao', medium: 'Trung bình', low: 'Thấp' },
    priority: { immediate: 'Ngay', soon: 'Sớm', when_convenient: 'Khi tiện' },
    diy: 'Tự làm',
    possibleCauses: 'Nguyên nhân có thể',
    mostLikelyCause: 'Nguyên nhân khả dĩ nhất',
    whatToDo: 'Nên làm gì',
    betterDiagnosis: 'Để chẩn đoán tốt hơn, hãy thử thêm',
    partsToInspect: 'Bộ phận cần kiểm tra',
    costEstimate: 'Chi phí sửa chữa dự kiến',
    confidence: 'Độ tin cậy',
    costFrom: 'Từ {amount}',
    costUpTo: 'Tối đa {amount}',
    errors: {
      generic: 'Phân tích không thành công. Vui lòng thử lại.',
      maxFile: 'Dung lượng tệp tối đa 20 MB.',
      mic: 'Quyền truy cập micro bị từ chối. Vui lòng cho phép rồi thử lại.',
      no_audio: 'Vui lòng đính kèm bản ghi âm.',
      too_large: 'Tệp âm thanh quá lớn. Vui lòng dùng đoạn dưới 8 MB (khoảng 30 giây).',
      unavailable: 'Dịch vụ AI tạm thời không khả dụng. Vui lòng thử lại sau ít phút.',
      parse: 'Không đọc được phản hồi của AI. Vui lòng thử lại.',
      server: 'Đã xảy ra lỗi. Vui lòng thử lại.',
    },
  },
};
