import type { Metadata } from 'next';
import Link from 'next/link';
import { ChevronRight, Scale } from 'lucide-react';

export const metadata: Metadata = {
  title: 'Terms of Service — Naira Autos',
  description: 'Review the terms and usage guidelines regulating your access to the free automotive estimation applications at Naira Autos.',
  alternates: {
    canonical: 'https://www.naira.autos/terms',
  },
  openGraph: {
    title: 'Naira Autos Terms of Service',
    description: 'Usage framework for calculators, information aggregation sheets, and AI mechanic components.',
    url: 'https://www.naira.autos/terms',
    type: 'website',
  },
};

export default function TermsPage() {
  return (
    <>
      <div className="bg-[#080C10] border-b border-white/10">
        <div className="max-w-screen-xl mx-auto px-4 sm:px-6 pt-10 pb-12">
          <nav className="flex items-center gap-1.5 text-xs text-white/30 mb-8" aria-label="Breadcrumb">
            <Link href="/" className="hover:text-white/60 transition-colors">Home</Link>
            <ChevronRight className="h-3 w-3" />
            <span className="text-white/50">Terms of Service</span>
          </nav>

          <div className="flex items-center gap-3 mb-3">
            <Scale className="h-5 w-5 text-emerald-400" />
            <span className="text-xs font-bold tracking-widest text-emerald-400 uppercase">Legal Policy</span>
          </div>

          <h1
            className="font-black uppercase text-white leading-none tracking-tight mb-2"
            style={{ fontFamily: "'Barlow Condensed', Impact, sans-serif", fontSize: 'clamp(32px, 5vw, 60px)' }}
          >
            Terms of Service
          </h1>
          <p className="text-white/60 text-xs">Last Updated: May 2026</p>
        </div>
      </div>

      <div className="bg-background">
        <div className="max-w-screen-md mx-auto px-4 py-14">
          <div className="prose dark:prose-invert space-y-8 text-sm text-muted-foreground leading-relaxed">
            
            <section>
              <h2 className="text-base font-bold text-foreground mb-2">1. Acceptance of Terms</h2>
              <p>
                By visiting and pulling data tools from www.naira.autos ("Naira Autos"), you agree to follow and be explicitly bound by these Terms of Service. If you do not agree with any part of these frameworks, you are restricted from utilizing our web pages.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-foreground mb-2">2. Nature of Services & Disclaimers</h2>
              <p>
                Naira Autos publishes estimations, mathematical projections, and automated guidance utilities—including the Import Duty Calculator, AI Mechanic, and Auto Loan Calculator. 
              </p>
              <p className="mt-2 bg-muted/40 border border-border p-3 rounded-lg text-xs">
                <strong>Crucial Note:</strong> All results generated by our applications are intended strictly for educational and informational references. We are not a customs brokerage agency, financial bank, or certified auto garage workshop. Exact figures must be verified with formal regulatory agencies or professionals before financial obligations are cleared.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-foreground mb-2">3. Prohibited Exploitation</h2>
              <p>When pulling assets from our site, you agree to refrain from:</p>
              <ul className="list-disc pl-5 space-y-1 mt-1">
                <li>Using programmatic scraping scripts, bots, or harvesting algorithms to scrape our organized glossary terms or dataset tables.</li>
                <li>Attempting to bypass security infrastructure or malicious overloading of API layers hosting our AI endpoints.</li>
                <li>Masking data outputs to pass off Naira Autos software applications as proprietary third-party property.</li>
              </ul>
            </section>

            <section>
              <h2 className="text-base font-bold text-foreground mb-2">4. Intellectual Property</h2>
              <p>
                The layouts, custom application formulas, user-interface code, text documentation setups, and trademark configurations displayed under the Naira Autos label belong firmly to the site creators and are shielded by global copyright protocols.
              </p>
            </section>

            <section>
              <h2 className="text-base font-bold text-foreground mb-2">5. Liability Limitations</h2>
              <p>
                Under no situation will Naira Autos or its administrators be responsible for financial loss, bad vehicular investments, or mechanical breakdowns derived from utilizing or misinterpreting material displayed across our site tools.
              </p>
            </section>
            
          </div>
        </div>
      </div>
    </>
  );
}