// Curated routes for the Global Fuel Cost Calculator family. Distances
// are real road distances (typical highway route), not straight-line —
// a straight-line-plus-flat-percentage estimate was tested against known
// road distances and was off by 20–34% on mountainous or indirect routes
// (e.g. Bogotá–Medellín, Lagos–Abuja), so each route below is a verified
// road-distance figure instead, the same approach the original
// Nigeria-focused calculator uses.
//
// `country` groups the dropdown into <optgroup> sections — with 50+
// countries a flat list stopped being usable, so every route is tagged.
//
// Sources: national mapping/road-distance data as of Aug 2026. Batch
// researched across India, China, Indonesia, Pakistan, Brazil, Bangladesh,
// Russia, Japan, Ethiopia, Egypt, Philippines, Vietnam, Iran, Turkey,
// Germany, Thailand, France, Italy, Tanzania, Kenya, South Korea, Algeria,
// Poland, Saudi Arabia, Malaysia, Australia, Netherlands, Sweden,
// Switzerland, Singapore, UAE, Norway, New Zealand, Belgium, Denmark,
// Finland, Ireland, Austria, Israel, Taiwan, Hong Kong, Portugal, Czechia.

export interface FuelRoute { label: string; km: number; country: string; }

export const GLOBAL_ROUTES: FuelRoute[] = [
  { label: 'Lagos → Abuja', km: 791, country: 'Nigeria' },
  { label: 'New York → Los Angeles', km: 4500, country: 'United States' },
  { label: 'Los Angeles → San Francisco', km: 615, country: 'United States' },
  { label: 'London → Manchester', km: 330, country: 'United Kingdom' },
  { label: 'London → Birmingham', km: 195, country: 'United Kingdom' },
  { label: 'London → Edinburgh', km: 660, country: 'United Kingdom' },
  { label: 'Manchester → Liverpool', km: 57, country: 'United Kingdom' },
  { label: 'Toronto → Montreal', km: 540, country: 'Canada' },
  { label: 'Toronto → Ottawa', km: 455, country: 'Canada' },
  { label: 'Vancouver → Calgary', km: 985, country: 'Canada' },
  { label: 'Toronto → Winnipeg', km: 2050, country: 'Canada' },
  { label: 'Montreal → Quebec City', km: 260, country: 'Canada' },
  { label: 'Sydney → Melbourne', km: 880, country: 'Australia' },
  { label: 'Cape Town → Johannesburg', km: 1400, country: 'South Africa' },
  { label: 'Mumbai → Delhi', km: 1400, country: 'India' },
  { label: 'Delhi → Jaipur', km: 275, country: 'India' },
  { label: 'Mumbai → Bangalore', km: 990, country: 'India' },
  { label: 'Bangalore → Chennai', km: 355, country: 'India' },
  { label: 'Hyderabad → Bangalore', km: 575, country: 'India' },
  { label: 'Dubai → Abu Dhabi', km: 140, country: 'United Arab Emirates' },
  { label: 'Mexico City → Guadalajara', km: 540, country: 'Mexico' },
  { label: 'Madrid → Barcelona', km: 620, country: 'Spain' },
  { label: 'Buenos Aires → Córdoba', km: 700, country: 'Argentina' },
  { label: 'Buenos Aires → Mendoza', km: 1050, country: 'Argentina' },
  { label: 'Buenos Aires → Mar del Plata', km: 410, country: 'Argentina' },
  { label: 'Córdoba → Mendoza', km: 665, country: 'Argentina' },
  { label: 'Bogotá → Medellín', km: 415, country: 'Colombia' },
  { label: 'Santiago → Valparaíso', km: 120, country: 'Chile' },
  { label: 'Beijing → Shanghai', km: 1250, country: 'China' },
  { label: 'Shanghai → Hangzhou', km: 175, country: 'China' },
  { label: 'Guangzhou → Shenzhen', km: 145, country: 'China' },
  { label: 'Chengdu → Chongqing', km: 310, country: 'China' },
  { label: 'Jakarta → Bandung', km: 155, country: 'Indonesia' },
  { label: 'Jakarta → Yogyakarta', km: 550, country: 'Indonesia' },
  { label: 'Surabaya → Malang', km: 95, country: 'Indonesia' },
  { label: 'Jakarta → Semarang', km: 460, country: 'Indonesia' },
  { label: 'Karachi → Lahore', km: 1230, country: 'Pakistan' },
  { label: 'Lahore → Islamabad', km: 385, country: 'Pakistan' },
  { label: 'Lahore → Multan', km: 350, country: 'Pakistan' },
  { label: 'Islamabad → Peshawar', km: 175, country: 'Pakistan' },
  { label: 'São Paulo → Rio de Janeiro', km: 440, country: 'Brazil' },
  { label: 'São Paulo → Brasília', km: 1025, country: 'Brazil' },
  { label: 'Salvador → Recife', km: 825, country: 'Brazil' },
  { label: 'Porto Alegre → Curitiba', km: 710, country: 'Brazil' },
  { label: 'Dhaka → Chittagong', km: 260, country: 'Bangladesh' },
  { label: 'Dhaka → Sylhet', km: 250, country: 'Bangladesh' },
  { label: 'Dhaka → Khulna', km: 290, country: 'Bangladesh' },
  { label: 'Chittagong → Cox\'s Bazar', km: 155, country: 'Bangladesh' },
  { label: 'Moscow → St. Petersburg', km: 710, country: 'Russia' },
  { label: 'Moscow → Kazan', km: 810, country: 'Russia' },
  { label: 'Moscow → Yekaterinburg', km: 1825, country: 'Russia' },
  { label: 'Novosibirsk → Omsk', km: 665, country: 'Russia' },
  { label: 'Tokyo → Osaka', km: 510, country: 'Japan' },
  { label: 'Tokyo → Nagoya', km: 360, country: 'Japan' },
  { label: 'Osaka → Kyoto', km: 55, country: 'Japan' },
  { label: 'Tokyo → Sendai', km: 360, country: 'Japan' },
  { label: 'Addis Ababa → Dire Dawa', km: 445, country: 'Ethiopia' },
  { label: 'Addis Ababa → Bahir Dar', km: 570, country: 'Ethiopia' },
  { label: 'Addis Ababa → Hawassa', km: 275, country: 'Ethiopia' },
  { label: 'Addis Ababa → Mekelle', km: 790, country: 'Ethiopia' },
  { label: 'Cairo → Alexandria', km: 225, country: 'Egypt' },
  { label: 'Cairo → Luxor', km: 675, country: 'Egypt' },
  { label: 'Cairo → Aswan', km: 900, country: 'Egypt' },
  { label: 'Cairo → Hurghada', km: 465, country: 'Egypt' },
  { label: 'Manila → Baguio', km: 260, country: 'Philippines' },
  { label: 'Davao → Cagayan de Oro', km: 325, country: 'Philippines' },
  { label: 'Hanoi → Ho Chi Minh City', km: 1725, country: 'Vietnam' },
  { label: 'Hanoi → Da Nang', km: 785, country: 'Vietnam' },
  { label: 'Ho Chi Minh City → Can Tho', km: 175, country: 'Vietnam' },
  { label: 'Hanoi → Hai Phong', km: 110, country: 'Vietnam' },
  { label: 'Tehran → Isfahan', km: 435, country: 'Iran' },
  { label: 'Tehran → Mashhad', km: 925, country: 'Iran' },
  { label: 'Tehran → Shiraz', km: 925, country: 'Iran' },
  { label: 'Isfahan → Shiraz', km: 490, country: 'Iran' },
  { label: 'Istanbul → Ankara', km: 460, country: 'Turkey' },
  { label: 'Istanbul → Izmir', km: 490, country: 'Turkey' },
  { label: 'Ankara → Antalya', km: 490, country: 'Turkey' },
  { label: 'Istanbul → Bursa', km: 155, country: 'Turkey' },
  { label: 'Berlin → Munich', km: 590, country: 'Germany' },
  { label: 'Berlin → Hamburg', km: 295, country: 'Germany' },
  { label: 'Frankfurt → Munich', km: 395, country: 'Germany' },
  { label: 'Cologne → Berlin', km: 575, country: 'Germany' },
  { label: 'Bangkok → Chiang Mai', km: 710, country: 'Thailand' },
  { label: 'Bangkok → Phuket', km: 840, country: 'Thailand' },
  { label: 'Bangkok → Pattaya', km: 155, country: 'Thailand' },
  { label: 'Chiang Mai → Chiang Rai', km: 190, country: 'Thailand' },
  { label: 'Paris → Lyon', km: 470, country: 'France' },
  { label: 'Paris → Marseille', km: 785, country: 'France' },
  { label: 'Paris → Bordeaux', km: 590, country: 'France' },
  { label: 'Lyon → Nice', km: 480, country: 'France' },
  { label: 'Rome → Milan', km: 585, country: 'Italy' },
  { label: 'Rome → Naples', km: 225, country: 'Italy' },
  { label: 'Milan → Venice', km: 275, country: 'Italy' },
  { label: 'Rome → Florence', km: 290, country: 'Italy' },
  { label: 'Dar es Salaam → Arusha', km: 650, country: 'Tanzania' },
  { label: 'Dar es Salaam → Dodoma', km: 465, country: 'Tanzania' },
  { label: 'Dar es Salaam → Mwanza', km: 1125, country: 'Tanzania' },
  { label: 'Arusha → Moshi', km: 85, country: 'Tanzania' },
  { label: 'Nairobi → Mombasa', km: 490, country: 'Kenya' },
  { label: 'Nairobi → Kisumu', km: 360, country: 'Kenya' },
  { label: 'Nairobi → Nakuru', km: 165, country: 'Kenya' },
  { label: 'Nairobi → Eldoret', km: 320, country: 'Kenya' },
  { label: 'Seoul → Busan', km: 330, country: 'South Korea' },
  { label: 'Seoul → Daegu', km: 290, country: 'South Korea' },
  { label: 'Busan → Gwangju', km: 260, country: 'South Korea' },
  { label: 'Seoul → Daejeon', km: 165, country: 'South Korea' },
  { label: 'Algiers → Oran', km: 430, country: 'Algeria' },
  { label: 'Algiers → Constantine', km: 440, country: 'Algeria' },
  { label: 'Oran → Tlemcen', km: 145, country: 'Algeria' },
  { label: 'Algiers → Annaba', km: 565, country: 'Algeria' },
  { label: 'Warsaw → Kraków', km: 295, country: 'Poland' },
  { label: 'Warsaw → Gdańsk', km: 350, country: 'Poland' },
  { label: 'Warsaw → Wrocław', km: 360, country: 'Poland' },
  { label: 'Kraków → Katowice', km: 85, country: 'Poland' },
  { label: 'Riyadh → Jeddah', km: 965, country: 'Saudi Arabia' },
  { label: 'Riyadh → Dammam', km: 410, country: 'Saudi Arabia' },
  { label: 'Jeddah → Mecca', km: 85, country: 'Saudi Arabia' },
  { label: 'Riyadh → Medina', km: 865, country: 'Saudi Arabia' },
  { label: 'Kuala Lumpur → Penang', km: 360, country: 'Malaysia' },
  { label: 'Kuala Lumpur → Johor Bahru', km: 330, country: 'Malaysia' },
  { label: 'Kuala Lumpur → Ipoh', km: 205, country: 'Malaysia' },
  { label: 'Kuala Lumpur → Malacca', km: 145, country: 'Malaysia' },
  { label: 'Amsterdam → Rotterdam', km: 78, country: 'Netherlands' },
  { label: 'Amsterdam → The Hague', km: 62, country: 'Netherlands' },
  { label: 'Rotterdam → Eindhoven', km: 115, country: 'Netherlands' },
  { label: 'Amsterdam → Maastricht', km: 215, country: 'Netherlands' },
  { label: 'Stockholm → Gothenburg', km: 475, country: 'Sweden' },
  { label: 'Stockholm → Malmö', km: 620, country: 'Sweden' },
  { label: 'Gothenburg → Malmö', km: 275, country: 'Sweden' },
  { label: 'Stockholm → Uppsala', km: 75, country: 'Sweden' },
  { label: 'Zurich → Geneva', km: 285, country: 'Switzerland' },
  { label: 'Zurich → Bern', km: 125, country: 'Switzerland' },
  { label: 'Geneva → Lausanne', km: 62, country: 'Switzerland' },
  { label: 'Zurich → Basel', km: 87, country: 'Switzerland' },
  { label: 'Changi → Jurong', km: 35, country: 'Singapore' },
  { label: 'Changi → Woodlands', km: 30, country: 'Singapore' },
  { label: 'Oslo → Bergen', km: 470, country: 'Norway' },
  { label: 'Oslo → Trondheim', km: 500, country: 'Norway' },
  { label: 'Oslo → Stavanger', km: 460, country: 'Norway' },
  { label: 'Bergen → Stavanger', km: 220, country: 'Norway' },
  { label: 'Auckland → Wellington', km: 650, country: 'New Zealand' },
  { label: 'Auckland → Hamilton', km: 135, country: 'New Zealand' },
  { label: 'Christchurch → Queenstown', km: 490, country: 'New Zealand' },
  { label: 'Auckland → Tauranga', km: 205, country: 'New Zealand' },
  { label: 'Brussels → Antwerp', km: 47, country: 'Belgium' },
  { label: 'Brussels → Ghent', km: 57, country: 'Belgium' },
  { label: 'Brussels → Liège', km: 105, country: 'Belgium' },
  { label: 'Antwerp → Bruges', km: 95, country: 'Belgium' },
  { label: 'Copenhagen → Aarhus', km: 187, country: 'Denmark' },
  { label: 'Copenhagen → Odense', km: 162, country: 'Denmark' },
  { label: 'Copenhagen → Aalborg', km: 305, country: 'Denmark' },
  { label: 'Aarhus → Aalborg', km: 115, country: 'Denmark' },
  { label: 'Helsinki → Tampere', km: 177, country: 'Finland' },
  { label: 'Helsinki → Turku', km: 165, country: 'Finland' },
  { label: 'Helsinki → Oulu', km: 605, country: 'Finland' },
  { label: 'Helsinki → Jyväskylä', km: 270, country: 'Finland' },
  { label: 'Dublin → Cork', km: 255, country: 'Ireland' },
  { label: 'Dublin → Galway', km: 205, country: 'Ireland' },
  { label: 'Dublin → Limerick', km: 197, country: 'Ireland' },
  { label: 'Cork → Limerick', km: 97, country: 'Ireland' },
  { label: 'Vienna → Graz', km: 195, country: 'Austria' },
  { label: 'Vienna → Salzburg', km: 297, country: 'Austria' },
  { label: 'Vienna → Innsbruck', km: 475, country: 'Austria' },
  { label: 'Salzburg → Innsbruck', km: 180, country: 'Austria' },
  { label: 'Tel Aviv → Jerusalem', km: 65, country: 'Israel' },
  { label: 'Tel Aviv → Haifa', km: 95, country: 'Israel' },
  { label: 'Jerusalem → Haifa', km: 155, country: 'Israel' },
  { label: 'Tel Aviv → Beersheba', km: 105, country: 'Israel' },
  { label: 'Taipei → Taichung', km: 160, country: 'Taiwan' },
  { label: 'Taipei → Kaohsiung', km: 345, country: 'Taiwan' },
  { label: 'Taichung → Kaohsiung', km: 190, country: 'Taiwan' },
  { label: 'Taipei → Hualien', km: 165, country: 'Taiwan' },
  { label: 'Central → Hong Kong Airport', km: 35, country: 'Hong Kong' },
  { label: 'Kowloon → New Territories', km: 25, country: 'Hong Kong' },
  { label: 'Lisbon → Porto', km: 310, country: 'Portugal' },
  { label: 'Lisbon → Faro', km: 275, country: 'Portugal' },
  { label: 'Porto → Coimbra', km: 120, country: 'Portugal' },
  { label: 'Porto → Braga', km: 55, country: 'Portugal' },
  { label: 'Prague → Brno', km: 205, country: 'Czechia' },
  { label: 'Prague → Ostrava', km: 360, country: 'Czechia' },
  { label: 'Prague → Plzeň', km: 95, country: 'Czechia' },
  { label: 'Brno → Ostrava', km: 170, country: 'Czechia' },  { label: 'Custom distance', km: 0, country: 'Custom' },
];

/** Spanish-speaking-country routes, for the Spanish tool's default list. */
export const GLOBAL_ROUTES_ES: FuelRoute[] = [
  { label: 'Madrid → Barcelona', km: 620, country: 'España' },
  { label: 'Madrid → Valencia', km: 355, country: 'España' },
  { label: 'Madrid → Sevilla', km: 535, country: 'España' },
  { label: 'Ciudad de México → Guadalajara', km: 540, country: 'México' },
  { label: 'Ciudad de México → Monterrey', km: 930, country: 'México' },
  { label: 'Buenos Aires → Córdoba', km: 700, country: 'Argentina' },
  { label: 'Buenos Aires → Rosario', km: 300, country: 'Argentina' },
  { label: 'Buenos Aires → Mendoza', km: 1050, country: 'Argentina' },
  { label: 'Bogotá → Medellín', km: 415, country: 'Colombia' },
  { label: 'Bogotá → Cali', km: 460, country: 'Colombia' },
  { label: 'Santiago → Valparaíso', km: 120, country: 'Chile' },
  { label: 'Santiago → Concepción', km: 500, country: 'Chile' },
  { label: 'Distancia personalizada', km: 0, country: 'Personalizado' },
];
