// Nigeria vehicle plate LGA-prefix dataset.
//
// Source: eduweb.com.ng per-state plate-code pages (fetched and cross-checked
// against official LGA counts per state — see COVERED_STATES below for the
// count match for each state currently included). Lagos was additionally
// cross-verified against an independent second source.
//
// This is a growing dataset, not a claim of full national coverage — see
// COVERED_STATES for what's verified so far. Anything not in PLATE_CODES
// should be verified directly at https://nvis.frsc.gov.ng/VehicleManagement/VerifyPlateNo
// rather than guessed.

export interface PlateCodeEntry {
  code: string;
  lga: string;
  state: string;
}

export const COVERED_STATES = [
  { state: 'Lagos', lgaCount: 20, verified: 20 },
  { state: 'FCT (Abuja)', lgaCount: 6, verified: 6 },
  { state: 'Kano', lgaCount: 44, verified: 44 },
  { state: 'Ogun', lgaCount: 20, verified: 20 },
  { state: 'Anambra', lgaCount: 21, verified: 21 },
  { state: 'Akwa Ibom', lgaCount: 31, verified: 31 },
  { state: 'Enugu', lgaCount: 17, verified: 17 },
  { state: 'Kaduna', lgaCount: 23, verified: 23 },
  { state: 'Katsina', lgaCount: 34, verified: 34 },
  { state: 'Niger', lgaCount: 25, verified: 25 },
  { state: 'Jigawa', lgaCount: 27, verified: 27 },
  { state: 'Borno', lgaCount: 27, verified: 27 },
  { state: 'Kogi', lgaCount: 21, verified: 21 },
  { state: 'Taraba', lgaCount: 16, verified: 16 },
  { state: 'Ondo', lgaCount: 18, verified: 17 }, // one source entry ("Ijaye"/GBA) was confirmed wrong — likely mislabeled Ilaje LGA — excluded rather than guessed
  { state: 'Plateau', lgaCount: 17, verified: 17 },
  { state: 'Kwara', lgaCount: 16, verified: 16 },
  { state: 'Ebonyi', lgaCount: 13, verified: 13 },
  { state: 'Abia', lgaCount: 17, verified: 16 }, // source missing Umu Nneochi LGA — excluded rather than guessed
  { state: 'Adamawa', lgaCount: 21, verified: 21 },
];

export const PLATE_CODES: PlateCodeEntry[] = [
  // Lagos (20 LGAs)
  { code: 'GGE', lga: 'Agege', state: 'Lagos' },
  { code: 'AGL', lga: 'Ajeromi-Ifelodun', state: 'Lagos' },
  { code: 'KTU', lga: 'Alimosho', state: 'Lagos' },
  { code: 'FST', lga: 'Amuwo-Odofin', state: 'Lagos' },
  { code: 'APP', lga: 'Apapa', state: 'Lagos' },
  { code: 'BDG', lga: 'Badagry', state: 'Lagos' },
  { code: 'EPE', lga: 'Epe', state: 'Lagos' },
  { code: 'EKY', lga: 'Eti-Osa', state: 'Lagos' },
  { code: 'AKD', lga: 'Ibeju-Lekki', state: 'Lagos' },
  { code: 'FKJ', lga: 'Ifako-Ijaiye', state: 'Lagos' },
  { code: 'KJA', lga: 'Ikeja', state: 'Lagos' },
  { code: 'KRD', lga: 'Ikorodu', state: 'Lagos' },
  { code: 'KSF', lga: 'Kosofe', state: 'Lagos' },
  { code: 'AAA', lga: 'Lagos Island', state: 'Lagos' },
  { code: 'LND', lga: 'Lagos Mainland', state: 'Lagos' },
  { code: 'MUS', lga: 'Mushin', state: 'Lagos' },
  { code: 'JJJ', lga: 'Ojo', state: 'Lagos' },
  { code: 'LSD', lga: 'Oshodi-Isolo', state: 'Lagos' },
  { code: 'SMK', lga: 'Somolu', state: 'Lagos' },
  { code: 'LSR', lga: 'Surulere', state: 'Lagos' },

  // FCT / Abuja (6 area councils)
  { code: 'ABJ', lga: 'Abaji', state: 'FCT (Abuja)' },
  { code: 'ABC', lga: 'Abuja Municipal Area Council', state: 'FCT (Abuja)' },
  { code: 'BWR', lga: 'Bwari', state: 'FCT (Abuja)' },
  { code: 'GWA', lga: 'Gwagwalada', state: 'FCT (Abuja)' },
  { code: 'KUJ', lga: 'Kuje', state: 'FCT (Abuja)' },
  { code: 'KWL', lga: 'Kwali', state: 'FCT (Abuja)' },

  // Kano (44 LGAs)
  { code: 'AJG', lga: 'Ajingi', state: 'Kano' },
  { code: 'ABS', lga: 'Albasu', state: 'Kano' },
  { code: 'BGW', lga: 'Bagwai', state: 'Kano' },
  { code: 'BBJ', lga: 'Bebeji', state: 'Kano' },
  { code: 'BCH', lga: 'Bichi', state: 'Kano' },
  { code: 'BNK', lga: 'Bunkure', state: 'Kano' },
  { code: 'DAL', lga: 'Dala', state: 'Kano' },
  { code: 'DBT', lga: 'Danbatta', state: 'Kano' },
  { code: 'DKD', lga: 'Dawakin Kudu', state: 'Kano' },
  { code: 'DTF', lga: 'Dawakin Tofa', state: 'Kano' },
  { code: 'DGW', lga: 'Doguwa', state: 'Kano' },
  { code: 'FGE', lga: 'Fagge', state: 'Kano' },
  { code: 'DSW', lga: 'Gabasawa', state: 'Kano' },
  { code: 'GAK', lga: 'Garko', state: 'Kano' },
  { code: 'GNM', lga: 'Garun Mallam', state: 'Kano' },
  { code: 'GYA', lga: 'Gaya', state: 'Kano' },
  { code: 'GZW', lga: 'Gezawa', state: 'Kano' },
  { code: 'GWL', lga: 'Gwale', state: 'Kano' },
  { code: 'GRZ', lga: 'Gwarzo', state: 'Kano' },
  { code: 'KMC', lga: 'Kano Municipal', state: 'Kano' },
  { code: 'KRY', lga: 'Karaye', state: 'Kano' },
  { code: 'KBY', lga: 'Kibiya', state: 'Kano' },
  { code: 'KKU', lga: 'Kiru', state: 'Kano' },
  { code: 'KBT', lga: 'Kumbotso', state: 'Kano' },
  { code: 'KNC', lga: 'Kunchi', state: 'Kano' },
  { code: 'KUR', lga: 'Kura', state: 'Kano' },
  { code: 'MDB', lga: 'Madobi', state: 'Kano' },
  { code: 'MKK', lga: 'Makoda', state: 'Kano' },
  { code: 'MJB', lga: 'Minjibir', state: 'Kano' },
  { code: 'NSR', lga: 'Nassarawa', state: 'Kano' },
  { code: 'RAN', lga: 'Rano', state: 'Kano' },
  { code: 'RMG', lga: 'Rimin Gado', state: 'Kano' },
  { code: 'RGG', lga: 'Rogo', state: 'Kano' },
  { code: 'SNN', lga: 'Shanono', state: 'Kano' },
  { code: 'SML', lga: 'Sumaila', state: 'Kano' },
  { code: 'TAK', lga: 'Takai', state: 'Kano' },
  { code: 'TRN', lga: 'Tarauni', state: 'Kano' },
  { code: 'TEA', lga: 'Tofa', state: 'Kano' },
  { code: 'TYW', lga: 'Tsanyawa', state: 'Kano' },
  { code: 'TWD', lga: 'Tudun Wada', state: 'Kano' },
  { code: 'UGG', lga: 'Ungogo', state: 'Kano' },
  { code: 'WRA', lga: 'Warawa', state: 'Kano' },
  { code: 'WDL', lga: 'Wudil', state: 'Kano' },
  { code: 'KBK', lga: 'Kabo', state: 'Kano' },

  // Ogun (20 LGAs)
  { code: 'AKM', lga: 'Abeokuta North', state: 'Ogun' },
  { code: 'AAB', lga: 'Abeokuta South', state: 'Ogun' },
  { code: 'OTA', lga: 'Ado-Odo/Ota', state: 'Ogun' },
  { code: 'TRE', lga: 'Ewekoro', state: 'Ogun' },
  { code: 'FFF', lga: 'Ifo', state: 'Ogun' },
  { code: 'AYE', lga: 'Yewa North (Egbado North)', state: 'Ogun' },
  { code: 'LAR', lga: 'Yewa South (Egbado South)', state: 'Ogun' },
  { code: 'GBE', lga: 'Ijebu East', state: 'Ogun' },
  { code: 'JGB', lga: 'Ijebu North', state: 'Ogun' },
  { code: 'JNE', lga: 'Ijebu North East', state: 'Ogun' },
  { code: 'JBD', lga: 'Ijebu Ode', state: 'Ogun' },
  { code: 'KNN', lga: 'Ikenne', state: 'Ogun' },
  { code: 'MEK', lga: 'Imeko Afon', state: 'Ogun' },
  { code: 'PKA', lga: 'Ipokia', state: 'Ogun' },
  { code: 'WDE', lga: 'Obafemi Owode', state: 'Ogun' },
  { code: 'DED', lga: 'Odeda', state: 'Ogun' },
  { code: 'DGB', lga: 'Odogbolu', state: 'Ogun' },
  { code: 'ABG', lga: 'Ogun Waterside', state: 'Ogun' },
  { code: 'JRM', lga: 'Remo North', state: 'Ogun' },
  { code: 'SMG', lga: 'Shagamu', state: 'Ogun' },

  // Anambra (21 LGAs)
  { code: 'AGU', lga: 'Aguata', state: 'Anambra' },
  { code: 'AAH', lga: 'Anambra East', state: 'Anambra' },
  { code: 'NZM', lga: 'Anambra West', state: 'Anambra' },
  { code: 'NEN', lga: 'Anaocha', state: 'Anambra' },
  { code: 'ACA', lga: 'Awka North', state: 'Anambra' },
  { code: 'AWK', lga: 'Awka South', state: 'Anambra' },
  { code: 'NKK', lga: 'Ayamelum', state: 'Anambra' },
  { code: 'KPP', lga: 'Dunukofia', state: 'Anambra' },
  { code: 'ZBL', lga: 'Ekwusigo', state: 'Anambra' },
  { code: 'GDD', lga: 'Idemili North', state: 'Anambra' },
  { code: 'JJT', lga: 'Idemili South', state: 'Anambra' },
  { code: 'HAL', lga: 'Ogbaru/Mala', state: 'Anambra' },
  { code: 'ABN', lga: 'Njikoka', state: 'Anambra' },
  { code: 'NNE', lga: 'Nnewi North', state: 'Anambra' },
  { code: 'UKP', lga: 'Nnewi South', state: 'Anambra' },
  { code: 'ATN', lga: 'Ogbaru', state: 'Anambra' },
  { code: 'NSH', lga: 'Onitsha North', state: 'Anambra' },
  { code: 'FGG', lga: 'Onitsha South', state: 'Anambra' },
  { code: 'AJL', lga: 'Orumba North', state: 'Anambra' },
  { code: 'UMZ', lga: 'Orumba South', state: 'Anambra' },
  { code: 'HTE', lga: 'Oyi', state: 'Anambra' },

  // Akwa Ibom (31 LGAs)
  { code: 'ABK', lga: 'Abak', state: 'Akwa Ibom' },
  { code: 'KRT', lga: 'Eastern Obolo', state: 'Akwa Ibom' },
  { code: 'KET', lga: 'Eket', state: 'Akwa Ibom' },
  { code: 'KST', lga: 'Esit Eket', state: 'Akwa Ibom' },
  { code: 'AFH', lga: 'Essien Udim', state: 'Akwa Ibom' },
  { code: 'AEE', lga: 'Etim Ekpo', state: 'Akwa Ibom' },
  { code: 'ETN', lga: 'Etinan', state: 'Akwa Ibom' },
  { code: 'PNG', lga: 'Ibeno', state: 'Akwa Ibom' },
  { code: 'NGD', lga: 'Ibesikpo Asutan', state: 'Akwa Ibom' },
  { code: 'BMT', lga: 'Ibiono Ibom', state: 'Akwa Ibom' },
  { code: 'NYA', lga: 'Ika', state: 'Akwa Ibom' },
  { code: 'KKN', lga: 'Ikono', state: 'Akwa Ibom' },
  { code: 'KTS', lga: 'Ikot Abasi', state: 'Akwa Ibom' },
  { code: 'KTE', lga: 'Ikot Ekpene', state: 'Akwa Ibom' },
  { code: 'DRK', lga: 'Ini', state: 'Akwa Ibom' },
  { code: 'TTU', lga: 'Itu', state: 'Akwa Ibom' },
  { code: 'ENW', lga: 'Mbo', state: 'Akwa Ibom' },
  { code: 'MKP', lga: 'Mkpat Enin', state: 'Akwa Ibom' },
  { code: 'AFG', lga: 'Nsit Ibom', state: 'Akwa Ibom' },
  { code: 'KTD', lga: 'Nsit Ubium', state: 'Akwa Ibom' },
  { code: 'TAI', lga: 'Nsit Atai', state: 'Akwa Ibom' },
  { code: 'NTE', lga: 'Obot Akara', state: 'Akwa Ibom' },
  { code: 'KPD', lga: 'Okobo', state: 'Akwa Ibom' },
  { code: 'ABT', lga: 'Onna', state: 'Akwa Ibom' },
  { code: 'RNN', lga: 'Oron', state: 'Akwa Ibom' },
  { code: 'KTM', lga: 'Oruk Anam', state: 'Akwa Ibom' },
  { code: 'EYF', lga: 'Udung Uko', state: 'Akwa Ibom' },
  { code: 'KPK', lga: 'Ukanafun', state: 'Akwa Ibom' },
  { code: 'UFG', lga: 'Uruan Offong Oruko', state: 'Akwa Ibom' },
  { code: 'DUU', lga: 'Uruan', state: 'Akwa Ibom' },
  { code: 'UYY', lga: 'Uyo', state: 'Akwa Ibom' },

  // Enugu (17 LGAs)
  { code: 'DBR', lga: 'Aninri', state: 'Enugu' },
  { code: 'AWG', lga: 'Awgu', state: 'Enugu' },
  { code: 'NKW', lga: 'Enugu East', state: 'Enugu' },
  { code: 'ENU', lga: 'Enugu North', state: 'Enugu' },
  { code: 'UWN', lga: 'Enugu South', state: 'Enugu' },
  { code: 'AGW', lga: 'Ezeagu', state: 'Enugu' },
  { code: 'GBD', lga: 'Igbo Etiti', state: 'Enugu' },
  { code: 'ENZ', lga: 'Igbo Eze North', state: 'Enugu' },
  { code: 'BBG', lga: 'Igbo Eze South', state: 'Enugu' },
  { code: 'KEM', lga: 'Isi Uzo', state: 'Enugu' },
  { code: 'MGL', lga: 'Nkanu East', state: 'Enugu' },
  { code: 'AGN', lga: 'Nkanu West', state: 'Enugu' },
  { code: 'NSK', lga: 'Nsukka', state: 'Enugu' },
  { code: 'JRV', lga: 'Oji River', state: 'Enugu' },
  { code: 'BLF', lga: 'Udenu', state: 'Enugu' },
  { code: 'UDD', lga: 'Udi', state: 'Enugu' },
  { code: 'UMU', lga: 'Uzo-Uwani', state: 'Enugu' },

  // Kaduna (23 LGAs)
  { code: 'BNG', lga: 'Birnin Gwari', state: 'Kaduna' },
  { code: 'KJM', lga: 'Chikun', state: 'Kaduna' },
  { code: 'GKW', lga: 'Giwa', state: 'Kaduna' },
  { code: 'TRK', lga: 'Igabi', state: 'Kaduna' },
  { code: 'KAR', lga: 'Ikara', state: 'Kaduna' },
  { code: 'KWB', lga: 'Jaba', state: 'Kaduna' },
  { code: 'KAF', lga: 'Jemaa', state: 'Kaduna' },
  { code: 'KCH', lga: 'Kachia', state: 'Kaduna' },
  { code: 'DKA', lga: 'Kaduna North', state: 'Kaduna' },
  { code: 'KGK', lga: 'Kagarko', state: 'Kaduna' },
  { code: 'KJR', lga: 'Kajuru', state: 'Kaduna' },
  { code: 'KRA', lga: 'Kaura', state: 'Kaduna' },
  { code: 'MKA', lga: 'Kaduna South', state: 'Kaduna' },
  { code: 'KRU', lga: 'Kauru', state: 'Kaduna' },
  { code: 'ANC', lga: 'Kubau', state: 'Kaduna' },
  { code: 'HKY', lga: 'Kudan', state: 'Kaduna' },
  { code: 'SNK', lga: 'Lere', state: 'Kaduna' },
  { code: 'MKR', lga: 'Makarfi', state: 'Kaduna' },
  { code: 'SBG', lga: 'Sabon Gari', state: 'Kaduna' },
  { code: 'GWT', lga: 'Sanga', state: 'Kaduna' },
  { code: 'MGN', lga: 'Soba', state: 'Kaduna' },
  { code: 'ZKW', lga: 'Zangon Kataf', state: 'Kaduna' },
  { code: 'ZAR', lga: 'Zaria', state: 'Kaduna' },

  // Katsina (34 LGAs)
  { code: 'BKR', lga: 'Bakori', state: 'Katsina' },
  { code: 'BAT', lga: 'Batagarawa', state: 'Katsina' },
  { code: 'BTR', lga: 'Batsari', state: 'Katsina' },
  { code: 'BRE', lga: 'Baure', state: 'Katsina' },
  { code: 'BDW', lga: 'Bindawa', state: 'Katsina' },
  { code: 'CRC', lga: 'Charanchi', state: 'Katsina' },
  { code: 'DMS', lga: 'Dan Musa', state: 'Katsina' },
  { code: 'DDM', lga: 'Dandume', state: 'Katsina' },
  { code: 'DJA', lga: 'Danja', state: 'Katsina' },
  { code: 'DRA', lga: 'Daura', state: 'Katsina' },
  { code: 'DTS', lga: 'Dutsi', state: 'Katsina' },
  { code: 'DTM', lga: 'Dutsinma', state: 'Katsina' },
  { code: 'FSK', lga: 'Faskari', state: 'Katsina' },
  { code: 'FTA', lga: 'Funtua', state: 'Katsina' },
  { code: 'NGW', lga: 'Ingawa', state: 'Katsina' },
  { code: 'JBY', lga: 'Jibia', state: 'Katsina' },
  { code: 'KFR', lga: 'Kafur', state: 'Katsina' },
  { code: 'KAT', lga: 'Kaita', state: 'Katsina' },
  { code: 'KKR', lga: 'Kankara', state: 'Katsina' },
  { code: 'KNK', lga: 'Kankia', state: 'Katsina' },
  { code: 'KTN', lga: 'Katsina', state: 'Katsina' },
  { code: 'KUF', lga: 'Kurfi', state: 'Katsina' },
  { code: 'KSD', lga: 'Kusada', state: 'Katsina' },
  { code: 'MDW', lga: 'Mai\'Adua', state: 'Katsina' },
  { code: 'MNF', lga: 'Malumfashi', state: 'Katsina' },
  { code: 'MAN', lga: 'Mani', state: 'Katsina' },
  { code: 'MSH', lga: 'Mashi', state: 'Katsina' },
  { code: 'MTZ', lga: 'Matazu', state: 'Katsina' },
  { code: 'MSW', lga: 'Musawa', state: 'Katsina' },
  { code: 'RMY', lga: 'Rimi', state: 'Katsina' },
  { code: 'SBA', lga: 'Sabuwa', state: 'Katsina' },
  { code: 'SFN', lga: 'Safana', state: 'Katsina' },
  { code: 'SDM', lga: 'Sandamu', state: 'Katsina' },
  { code: 'ZNG', lga: 'Zango', state: 'Katsina' },

  // Niger (25 LGAs)
  { code: 'AGA', lga: 'Agaie', state: 'Niger' },
  { code: 'AGR', lga: 'Agwara', state: 'Niger' },
  { code: 'BDA', lga: 'Bida', state: 'Niger' },
  { code: 'NBS', lga: 'Borgu', state: 'Niger' },
  { code: 'MAK', lga: 'Bosso', state: 'Niger' },
  { code: 'MNA', lga: 'Chanchaga', state: 'Niger' },
  { code: 'ENG', lga: 'Edati', state: 'Niger' },
  { code: 'LMU', lga: 'Gbako', state: 'Niger' },
  { code: 'GWU', lga: 'Gurara', state: 'Niger' },
  { code: 'KHA', lga: 'Katcha', state: 'Niger' },
  { code: 'KNT', lga: 'Kontagora', state: 'Niger' },
  { code: 'LAP', lga: 'Lapai', state: 'Niger' },
  { code: 'KUG', lga: 'Lavun', state: 'Niger' },
  { code: 'NAS', lga: 'Magama', state: 'Niger' },
  { code: 'BMG', lga: 'Mariga', state: 'Niger' },
  { code: 'MSG', lga: 'Mashegu', state: 'Niger' },
  { code: 'MKW', lga: 'Mokwa', state: 'Niger' },
  { code: 'SRP', lga: 'Munya', state: 'Niger' },
  { code: 'PAK', lga: 'Paikoro', state: 'Niger' },
  { code: 'KAG', lga: 'Rafi', state: 'Niger' },
  { code: 'RJA', lga: 'Rijau', state: 'Niger' },
  { code: 'KUT', lga: 'Shiroro', state: 'Niger' },
  { code: 'SUL', lga: 'Suleja', state: 'Niger' },
  { code: 'WSE', lga: 'Tafa', state: 'Niger' },
  { code: 'WSU', lga: 'Wushishi', state: 'Niger' },

  // Jigawa (27 LGAs)
  { code: 'AUY', lga: 'Auyo', state: 'Jigawa' },
  { code: 'BBR', lga: 'Babura', state: 'Jigawa' },
  { code: 'BNW', lga: 'Biriniwa', state: 'Jigawa' },
  { code: 'BKD', lga: 'Birnin Kudu', state: 'Jigawa' },
  { code: 'BUJ', lga: 'Buji', state: 'Jigawa' },
  { code: 'DUT', lga: 'Dutse', state: 'Jigawa' },
  { code: 'GGW', lga: 'Gagarawa', state: 'Jigawa' },
  { code: 'GRK', lga: 'Garki', state: 'Jigawa' },
  { code: 'GML', lga: 'Gumel', state: 'Jigawa' },
  { code: 'GRR', lga: 'Guri', state: 'Jigawa' },
  { code: 'GRM', lga: 'Gwaram', state: 'Jigawa' },
  { code: 'GWW', lga: 'Gwiwa', state: 'Jigawa' },
  { code: 'HJA', lga: 'Hadejia', state: 'Jigawa' },
  { code: 'JHN', lga: 'Jahun', state: 'Jigawa' },
  { code: 'KHS', lga: 'Kafin Hausa', state: 'Jigawa' },
  { code: 'KGM', lga: 'Kaugama', state: 'Jigawa' },
  { code: 'KZR', lga: 'Kazaure', state: 'Jigawa' },
  { code: 'KKM', lga: 'Kirikasamma', state: 'Jigawa' },
  { code: 'MGR', lga: 'Maigatari', state: 'Jigawa' },
  { code: 'MMR', lga: 'Malam Madori', state: 'Jigawa' },
  { code: 'MGA', lga: 'Miga', state: 'Jigawa' },
  { code: 'RNG', lga: 'Ringim', state: 'Jigawa' },
  { code: 'RRN', lga: 'Roni', state: 'Jigawa' },
  { code: 'STK', lga: 'Sule Tankarkar', state: 'Jigawa' },
  { code: 'TAR', lga: 'Taura', state: 'Jigawa' },
  { code: 'YKS', lga: 'Yankwashi', state: 'Jigawa' },
  { code: 'KYW', lga: 'Kiyawa', state: 'Jigawa' },

  // Borno (27 LGAs)
  { code: 'ADM', lga: 'Abadam', state: 'Borno' },
  { code: 'ASU', lga: 'Askira-Uba', state: 'Borno' },
  { code: 'BAM', lga: 'Bama', state: 'Borno' },
  { code: 'BAY', lga: 'Bayo', state: 'Borno' },
  { code: 'BBU', lga: 'Biu', state: 'Borno' },
  { code: 'CBK', lga: 'Chibok', state: 'Borno' },
  { code: 'DAM', lga: 'Damboa', state: 'Borno' },
  { code: 'DKW', lga: 'Dikwa', state: 'Borno' },
  { code: 'GUB', lga: 'Gubio', state: 'Borno' },
  { code: 'GZM', lga: 'Guzamala', state: 'Borno' },
  { code: 'GZA', lga: 'Gwoza', state: 'Borno' },
  { code: 'HWL', lga: 'Hawul', state: 'Borno' },
  { code: 'JRE', lga: 'Jere', state: 'Borno' },
  { code: 'KGG', lga: 'Kaga', state: 'Borno' },
  { code: 'KBG', lga: 'Kala/Balge', state: 'Borno' },
  { code: 'KDG', lga: 'Konduga', state: 'Borno' },
  { code: 'KWA', lga: 'Kukawa', state: 'Borno' },
  { code: 'KWY', lga: 'Kwaya Kusar', state: 'Borno' },
  { code: 'MAF', lga: 'Mafa', state: 'Borno' },
  { code: 'MGM', lga: 'Magumeri', state: 'Borno' },
  { code: 'MAG', lga: 'Maiduguri', state: 'Borno' },
  { code: 'MAR', lga: 'Marte', state: 'Borno' },
  { code: 'MBR', lga: 'Mobbar', state: 'Borno' },
  { code: 'MNG', lga: 'Monguno', state: 'Borno' },
  { code: 'NGL', lga: 'Ngala', state: 'Borno' },
  { code: 'NGZ', lga: 'Nganzai', state: 'Borno' },
  { code: 'SHN', lga: 'Shani', state: 'Borno' },

  // Kogi (21 LGAs)
  { code: 'DAV', lga: 'Adavi', state: 'Kogi' },
  { code: 'AJA', lga: 'Ajaokuta', state: 'Kogi' },
  { code: 'KPA', lga: 'Ankpa', state: 'Kogi' },
  { code: 'BAS', lga: 'Bassa', state: 'Kogi' },
  { code: 'KNA', lga: 'Dekina', state: 'Kogi' },
  { code: 'NDG', lga: 'Ibaji', state: 'Kogi' },
  { code: 'DAH', lga: 'Idah', state: 'Kogi' },
  { code: 'AJK', lga: 'Igalamela-Odolu', state: 'Kogi' },
  { code: 'JMU', lga: 'Ijumu', state: 'Kogi' },
  { code: 'KAB', lga: 'Kabba/Bunu', state: 'Kogi' },
  { code: 'KKF', lga: 'Kogi', state: 'Kogi' },
  { code: 'LKJ', lga: 'Lokoja', state: 'Kogi' },
  { code: 'MPA', lga: 'Mopa-Muro', state: 'Kogi' },
  { code: 'KFU', lga: 'Ofu', state: 'Kogi' },
  { code: 'KPF', lga: 'Ogori/Magongo', state: 'Kogi' },
  { code: 'KKH', lga: 'Okehi', state: 'Kogi' },
  { code: 'KNE', lga: 'Okene', state: 'Kogi' },
  { code: 'LAM', lga: 'Olamaboro', state: 'Kogi' },
  { code: 'BJK', lga: 'Omala', state: 'Kogi' },
  { code: 'ERE', lga: 'Yagba East', state: 'Kogi' },
  { code: 'SAN', lga: 'Yagba West', state: 'Kogi' },

  // Taraba (16 LGAs)
  { code: 'ARD', lga: 'Ardo-Kola', state: 'Taraba' },
  { code: 'BAL', lga: 'Bali', state: 'Taraba' },
  { code: 'DGA', lga: 'Donga', state: 'Taraba' },
  { code: 'GKA', lga: 'Gashaka', state: 'Taraba' },
  { code: 'GAS', lga: 'Gassol', state: 'Taraba' },
  { code: 'BBB', lga: 'Ibi', state: 'Taraba' },
  { code: 'JAL', lga: 'Jalingo', state: 'Taraba' },
  { code: 'KLD', lga: 'Karim-Lamido', state: 'Taraba' },
  { code: 'KRM', lga: 'Kurmi', state: 'Taraba' },
  { code: 'LAU', lga: 'Lau', state: 'Taraba' },
  { code: 'SDA', lga: 'Sardauna', state: 'Taraba' },
  { code: 'TTM', lga: 'Takum', state: 'Taraba' },
  { code: 'USS', lga: 'Ussa', state: 'Taraba' },
  { code: 'WKR', lga: 'Wukari', state: 'Taraba' },
  { code: 'YRR', lga: 'Yorro', state: 'Taraba' },
  { code: 'TZG', lga: 'Zing', state: 'Taraba' },

  // Ondo (17 of 18 LGAs — "Ijaye"/GBA source entry excluded as confirmed erroneous; Ilaje LGA not yet verified)
  { code: 'KAK', lga: 'Akoko North-East', state: 'Ondo' },
  { code: 'ANG', lga: 'Akoko North-West', state: 'Ondo' },
  { code: 'SUA', lga: 'Akoko South-West', state: 'Ondo' },
  { code: 'KAA', lga: 'Akoko South-East', state: 'Ondo' },
  { code: 'AKR', lga: 'Akure North', state: 'Ondo' },
  { code: 'JTA', lga: 'Akure South', state: 'Ondo' },
  { code: 'GKB', lga: 'Ese-Odo', state: 'Ondo' },
  { code: 'WEN', lga: 'Idanre', state: 'Ondo' },
  { code: 'FGB', lga: 'Ifedore', state: 'Ondo' },
  { code: 'LEL', lga: 'Ile-Oluji/Okeigbo', state: 'Ondo' },
  { code: 'REL', lga: 'Irele', state: 'Ondo' },
  { code: 'REF', lga: 'Odigbo', state: 'Ondo' },
  { code: 'KTP', lga: 'Okitipupa', state: 'Ondo' },
  { code: 'NND', lga: 'Ondo West', state: 'Ondo' },
  { code: 'BDR', lga: 'Ondo East', state: 'Ondo' },
  { code: 'FFN', lga: 'Ose', state: 'Ondo' },
  { code: 'WWW', lga: 'Owo', state: 'Ondo' },

  // Plateau (17 LGAs)
  { code: 'BLD', lga: 'Barkin-Ladi', state: 'Plateau' },
  { code: 'BSA', lga: 'Bassa', state: 'Plateau' },
  { code: 'BKK', lga: 'Bokkos', state: 'Plateau' },
  { code: 'ANW', lga: 'Jos East', state: 'Plateau' },
  { code: 'JJN', lga: 'Jos North', state: 'Plateau' },
  { code: 'BUU', lga: 'Jos South', state: 'Plateau' },
  { code: 'DNG', lga: 'Kanam', state: 'Plateau' },
  { code: 'KWK', lga: 'Kanke', state: 'Plateau' },
  { code: 'LGT', lga: 'Langtang North', state: 'Plateau' },
  { code: 'MBD', lga: 'Langtang South', state: 'Plateau' },
  { code: 'MGU', lga: 'Mangu', state: 'Plateau' },
  { code: 'TNK', lga: 'Mikang', state: 'Plateau' },
  { code: 'PKN', lga: 'Pankshin', state: 'Plateau' },
  { code: 'QAP', lga: 'Quaan Pan', state: 'Plateau' },
  { code: 'RYM', lga: 'Riyom', state: 'Plateau' },
  { code: 'SHD', lga: 'Shendam', state: 'Plateau' },
  { code: 'WAS', lga: 'Wase', state: 'Plateau' },

  // Kwara (16 LGAs)
  { code: 'AFN', lga: 'Asa', state: 'Kwara' },
  { code: 'KSB', lga: 'Baruten', state: 'Kwara' },
  { code: 'LAF', lga: 'Edu', state: 'Kwara' },
  { code: 'ARP', lga: 'Ekiti', state: 'Kwara' },
  { code: 'SHA', lga: 'Ifelodun', state: 'Kwara' },
  { code: 'KEY', lga: 'Ilorin East', state: 'Kwara' },
  { code: 'FUF', lga: 'Ilorin South', state: 'Kwara' },
  { code: 'LRN', lga: 'Ilorin West', state: 'Kwara' },
  { code: 'MUN', lga: 'Irepodun', state: 'Kwara' },
  { code: 'WSN', lga: 'Isin', state: 'Kwara' },
  { code: 'KMA', lga: 'Kaiama', state: 'Kwara' },
  { code: 'BDU', lga: 'Moro', state: 'Kwara' },
  { code: 'FFA', lga: 'Offa', state: 'Kwara' },
  { code: 'LFF', lga: 'Oke-Ero', state: 'Kwara' },
  { code: 'LEM', lga: 'Oyun', state: 'Kwara' },
  { code: 'PTG', lga: 'Pategi', state: 'Kwara' },

  // Ebonyi (13 LGAs)
  { code: 'AKL', lga: 'Abakaliki', state: 'Ebonyi' },
  { code: 'AFK', lga: 'Afikpo North', state: 'Ebonyi' },
  { code: 'EDA', lga: 'Afikpo South', state: 'Ebonyi' },
  { code: 'UGB', lga: 'Ebonyi', state: 'Ebonyi' },
  { code: 'EBJ', lga: 'Ezza North', state: 'Ebonyi' },
  { code: 'NKE', lga: 'Ezza South', state: 'Ebonyi' },
  { code: 'CHR', lga: 'Ikwo', state: 'Ebonyi' },
  { code: 'ZLL', lga: 'Ishielu', state: 'Ebonyi' },
  { code: 'SKA', lga: 'Ivo', state: 'Ebonyi' },
  { code: 'BKL', lga: 'Izzi', state: 'Ebonyi' },
  { code: 'HKW', lga: 'Ohaukwu', state: 'Ebonyi' },
  { code: 'BZR', lga: 'Ohaozara', state: 'Ebonyi' },
  { code: 'NCA', lga: 'Onicha', state: 'Ebonyi' },

  // Abia (16 of 17 LGAs — source missing Umu Nneochi)
  { code: 'EZA', lga: 'Aba North', state: 'Abia' },
  { code: 'ABA', lga: 'Aba South', state: 'Abia' },
  { code: 'ACH', lga: 'Arochukwu', state: 'Abia' },
  { code: 'BND', lga: 'Bende', state: 'Abia' },
  { code: 'KWU', lga: 'Ikwuano', state: 'Abia' },
  { code: 'KPU', lga: 'Isiala Ngwa North', state: 'Abia' },
  { code: 'MBA', lga: 'Isiala Ngwa South', state: 'Abia' },
  { code: 'MBL', lga: 'Isuikwuato', state: 'Abia' },
  { code: 'NGK', lga: 'Obi Ngwa', state: 'Abia' },
  { code: 'HAF', lga: 'Ohafia', state: 'Abia' },
  { code: 'SSM', lga: 'Osisioma', state: 'Abia' },
  { code: 'GWB', lga: 'Ugwunagbo', state: 'Abia' },
  { code: 'KKE', lga: 'Ukwa West', state: 'Abia' },
  { code: 'KEK', lga: 'Ukwa East', state: 'Abia' },
  { code: 'UMA', lga: 'Umuahia North', state: 'Abia' },
  { code: 'APR', lga: 'Umuahia South', state: 'Abia' },

  // Adamawa (21 LGAs)
  { code: 'DSA', lga: 'Demsa', state: 'Adamawa' },
  { code: 'FUR', lga: 'Fufore', state: 'Adamawa' },
  { code: 'GAN', lga: 'Ganye', state: 'Adamawa' },
  { code: 'GRE', lga: 'Girei', state: 'Adamawa' },
  { code: 'GMB', lga: 'Gombi', state: 'Adamawa' },
  { code: 'GUY', lga: 'Guyuk', state: 'Adamawa' },
  { code: 'HNG', lga: 'Hong', state: 'Adamawa' },
  { code: 'JAD', lga: 'Jada', state: 'Adamawa' },
  { code: 'JMT', lga: 'Yola North (Jimeta)', state: 'Adamawa' },
  { code: 'LMR', lga: 'Lamurde', state: 'Adamawa' },
  { code: 'MDG', lga: 'Madagali', state: 'Adamawa' },
  { code: 'MAH', lga: 'Maiha', state: 'Adamawa' },
  { code: 'MWA', lga: 'Mayo-Belwa', state: 'Adamawa' },
  { code: 'MCH', lga: 'Michika', state: 'Adamawa' },
  { code: 'MUB', lga: 'Mubi North', state: 'Adamawa' },
  { code: 'GYL', lga: 'Mubi South', state: 'Adamawa' },
  { code: 'NUM', lga: 'Numan', state: 'Adamawa' },
  { code: 'SHG', lga: 'Shelleng', state: 'Adamawa' },
  { code: 'SNG', lga: 'Song', state: 'Adamawa' },
  { code: 'TNG', lga: 'Toungo', state: 'Adamawa' },
  { code: 'YLA', lga: 'Yola South', state: 'Adamawa' },
];

export function lookupPlateCode(prefix: string): PlateCodeEntry | null {
  const clean = prefix.trim().toUpperCase();
  return PLATE_CODES.find((e) => e.code === clean) ?? null;
}

// Decode the 4th character of a post-2011 plate into a registration year.
// A=2011, B=2012, ... skipping nothing, sequential through the alphabet.
export function decodePlateYear(yearLetter: string): number | null {
  const letter = yearLetter.trim().toUpperCase();
  if (!/^[A-Z]$/.test(letter)) return null;
  const index = letter.charCodeAt(0) - 'A'.charCodeAt(0);
  return 2011 + index;
}
