import {
  Wrench, Calculator, CarFront, GitCompare, Fuel, BookOpen,
  Ship, Shield, FileText, Map, ClipboardCheck, Search, Camera, Newspaper, ArrowRight, Sparkles, Car, Truck, Bike, ScanLine, Droplets, Lightbulb, ArrowLeftRight, Percent, IdCard, History, Mic, Gauge, Globe2, Ruler,
} from 'lucide-react';

// Single source of truth for the full tools list — imported by both the
// /tools index page and the homepage stats strip, so the tool count on
// the homepage is always accurate and never needs manual updating.

export type Tool = {
  href: string;
  icon: React.ElementType;
  label: string;
  description: string;
  badge?: string;
  badgeColor?: string;
  category: string;
};

export const TOOLS: Tool[] = [
  // AI / Smart
  {
    href: '/evaluate-used-car',
    icon: Camera,
    label: 'AI Car Valuation (Photo)',
    description: 'Upload a photo and get an AI-powered estimate of your car\'s current market value in seconds.',
    badge: 'FREE',
    badgeColor: 'bg-amber-400/15 text-amber-400 border border-amber-400/30',
    category: 'AI & Smart',
  },
  {
    href: '/evaluate-car',
    icon: Percent,
    label: 'Car Valuation (Nigeria)',
    description: 'Upload a photo and get an AI-powered valuation calibrated to the Nigerian market — Tokunbo vs Nigerian-used pricing.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'AI & Smart',
  },
  {
    href: '/tools/ai-mechanic',
    icon: Wrench,
    label: 'AI Mechanic',
    description: 'Describe a symptom or upload a photo and get an instant diagnosis with local repair cost estimates.',
    badge: 'FREE',
    badgeColor: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30',
    category: 'AI & Smart',
  },
  {
    href: '/tools/engine-sound-analyzer',
    icon: Mic,
    label: 'Engine Sound Analyzer',
    description: 'Record or upload the sound your car is making and get an instant AI diagnosis of the likely cause.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'AI & Smart',
  },
  {
    href: '/tools/best-car-for',
    icon: CarFront,
    label: 'Best Car For Me',
    description: 'Tell us your budget, use case, and preferences — we\'ll recommend the best cars for you.',
    category: 'AI & Smart',
  },
  {
    href: '/tools/car-comparison',
    icon: GitCompare,
    label: 'Compare Cars',
    description: 'Side-by-side comparison of specs, fuel economy, price, and running costs.',
    category: 'AI & Smart',
  },
  {
    href: '/tools/document-generator',
    icon: FileText,
    label: 'Document Generator',
    description: 'Generate a bill of sale, loan agreement, or other vehicle document — legal requirements researched for your country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'AI & Smart',
  },
  // Finance
  {
    href: '/tools/import-duty-calculator-countries',
    icon: Ship,
    label: 'Import Duty Calculator',
    description: 'Calculate customs duty, clearing fees, and total landed cost for any imported vehicle — by country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Finance',
  },
  {
    href: '/tools/china-car-import-calculator',
    icon: Globe2,
    label: 'China Car Import Calculator',
    description: 'Cost of importing a Chinese car (Chery, Geely, GAC, BYD & more) — customs breakdown and EV exemption.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Finance',
  },
  {
    href: '/tools/auto-loan-calculator-countries',
    icon: Calculator,
    label: 'Auto Loan Calculator',
    description: 'Plan your car financing — monthly payments, total interest, and amortization schedule — by country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Finance',
  },
  {
    href: '/tools/insurance-calculator-countries',
    icon: Shield,
    label: 'Insurance Calculator',
    description: 'Estimate your comprehensive or third-party car insurance premium — by country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Finance',
  },
  {
    href: '/tools/registration-fee-calculator-countries',
    icon: FileText,
    label: 'Registration Fees',
    description: 'Calculate number plate, change of ownership, and vehicle registration costs — by country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Finance',
  },
  {
    href: '/tools/vehicle-license',
    icon: IdCard,
    label: 'Vehicle License Renewal',
    description: 'Requirements, step-by-step process, official portals, and costs for renewing your vehicle license — by country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Finance',
  },
  {
    href: '/tools/import-age-limit',
    icon: History,
    label: 'Import Age Limit Checker',
    description: 'Check if your car qualifies for import — the current age rule, how it\'s calculated, and what happens if it doesn\'t qualify — by country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Finance',
  },
  // Running Costs
  {
    href: '/tools/fuel-cost-calculator',
    icon: Fuel,
    label: 'Fuel Cost Calculator',
    description: 'Estimate your weekly or monthly fuel bill based on your car and driving distance.',
    category: 'Running Costs',
  },
  {
    href: '/tools/fuel-cost-calculator-global',
    icon: Globe2,
    label: 'Gas / Fuel Cost Calculator — Global',
    description: '44 currencies, real routes across 53 countries and 200+ cities — gas or fuel cost for any car, anywhere in the world.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Running Costs',
  },
  {
    href: '/tools/road-trip-calculator',
    icon: Map,
    label: 'Road Trip Calculator',
    description: 'Plan any road trip — total fuel cost, stops, and estimated travel time.',
    category: 'Running Costs',
  },
  {
    href: '/tools/distance-calculator-countries',
    icon: Ruler,
    label: 'Distance Calculator',
    description: 'Road distance and drive time between any two towns — verified state-capital distances plus fuel cost, by country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Running Costs',
  },
  {
    href: '/tools/wiper-blade-size-finder',
    icon: Droplets,
    label: 'Wiper Blade Size Finder',
    description: 'Find the exact wiper blade sizes and connector type for your car by make, model, and year.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Running Costs',
  },
  {
    href: '/tools/headlight-bulb-finder',
    icon: Lightbulb,
    label: 'Headlight Bulb Type Finder',
    description: 'Find the exact low beam, high beam, and fog light bulb codes for your car by make, model, and year.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Running Costs',
  },
  {
    href: '/tools/fuel-economy-converter',
    icon: ArrowLeftRight,
    label: 'Fuel Economy Unit Converter',
    description: 'Convert fuel economy instantly between MPG (US), MPG (UK), L/100km, and km/L.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Running Costs',
  },
  {
    href: '/tools/rideshare-earnings-calculator',
    icon: Percent,
    label: 'Ride-Share Earnings Calculator',
    description: 'See your real Uber, Bolt, or Lyft net profit after commission, fuel, and maintenance — any currency.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Running Costs',
  },
  // Due Diligence
  {
    href: '/tools/vin-checker',
    icon: Search,
    label: 'VIN Checker',
    description: 'Verify a car\'s history, specs, and origin using its Vehicle Identification Number.',
    category: 'Due Diligence',
  },
  {
    href: '/tools/vin-checker-global',
    icon: Search,
    label: 'VIN Checker (Global)',
    description: 'Free VIN decoder for used car buyers anywhere in the world — US, UK, UAE, Gulf, and beyond.',
    category: 'Due Diligence',
  },
  {
    href: '/tools/chassis-number-check',
    icon: Search,
    label: 'Chassis Number Check',
    description: 'Free chassis number check and verification, worldwide — make, model, year, engine specs, and origin.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Due Diligence',
  },
  {
    href: '/tools/engine-number-analyzer',
    icon: ScanLine,
    label: 'Engine Number Analyzer',
    description: 'Free engine number analyzer — enter an engine number or code and get the family, brand, displacement, and common applications.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Due Diligence',
  },
  {
    href: '/tools/plate-number-checker',
    icon: Search,
    label: 'Plate Number Checker',
    description: 'Free Nigeria plate number checker — decode LGA of registration, registration year, and plate format.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Due Diligence',
  },
  {
    href: '/tools/obd-codes',
    icon: ScanLine,
    label: 'OBD-II Code Lookup',
    description: 'What does your check engine light code mean? Causes, symptoms, and what to check first.',
    badge: 'FREE',
    badgeColor: 'bg-emerald-500/15 text-emerald-400 border border-emerald-500/30',
    category: 'Due Diligence',
  },
  {
    href: '/tools/vehicle-papers-checklist',
    icon: ClipboardCheck,
    label: 'Vehicle Papers Checklist',
    description: 'A complete checklist of all documents to verify before buying a used car.',
    category: 'Due Diligence',
  },
  {
    href: '/tools/mileage-explainer',
    icon: Gauge,
    label: 'Mileage Explainer',
    description: 'What does that odometer reading actually mean? See it as real-world distance — by country.',
    badge: 'NEW',
    badgeColor: 'bg-sky-500/15 text-sky-500 border border-sky-500/30',
    category: 'Due Diligence',
  },
  // Resources
  {
    href: '/tools/glossary',
    icon: BookOpen,
    label: 'Car Market Glossary',
    description: 'Every term you need to know — Tokunbo, Grade A, duty paid, Ladipo pricing, and hundreds more.',
    category: 'Resources',
  },
  {
    href: '/blog',
    icon: Newspaper,
    label: 'Blog & Tips',
    description: 'In-depth guides on buying, selling, and maintaining cars.',
    category: 'Resources',
  },
  {
    href: '/vehicles',
    icon: Car,
    label: 'Vehicle Info',
    description: 'Browse by brand and model — common problems, spare parts, and maintenance schedules.',
    category: 'Resources',
  },
];
