// lib/vehicle/engineNumberPatterns.ts
//
// Static database of engine FAMILY codes (not full serial numbers — the
// unique serial that follows a family code cannot be decoded publicly).
// Each entry here should be ONE real, canonical code. Marketing/family
// umbrella names (e.g. "Duratec 2.0", "Smartstream G1.6") and multi-code
// shorthand (e.g. "CA18DE/CA18DET") should be split into individual
// canonical records with the shared name captured via `family` and
// `aliases` instead — that keeps the matcher precise and keeps each
// result page pointing at one real, verifiable code.

export type EngineCodeRecord = {
  /** Canonical code (the one people usually search / stamp) */
  code: string;
  /** Brand / manufacturer */
  brand: string;
  /** Optional parent family for grouping (e.g. "JZ", "K-series", "LS", "EA888") */
  family?: string;
  /** Alternative names / marketing names / common variants */
  aliases?: string[];
  /** Displacement + configuration */
  displacement: string;
  config: string; // e.g. "I4", "V6", "I6 Twin-Turbo", "Flat-4 Turbo"
  /** Short useful notes */
  notes?: string;
  /** 2–6 common applications */
  applications: string[];
  /** Optional rough power range for extra value */
  powerRange?: string;
  /** Confidence weight for matcher (higher = more distinctive) */
  weight?: number;
};

export const engineCodes: EngineCodeRecord[] = [
  // ——— Toyota ———
  {
    code: '2JZ-GTE',
    brand: 'Toyota',
    family: 'JZ',
    aliases: ['2JZGTE'],
    displacement: '3.0L',
    config: 'I6 Twin-Turbo',
    notes: 'Iconic, extremely strong bottom end, massive tuning potential',
    applications: ['Supra (Mk4 A80)', 'Aristo', 'Some Lexus models'],
    powerRange: '276–320+ hp',
    weight: 10,
  },
  {
    code: '2GR-FE',
    brand: 'Toyota',
    family: 'GR',
    displacement: '3.5L',
    config: 'V6 NA',
    notes: 'Very reliable, widespread, dual VVT-i',
    applications: ['Camry', 'RAV4', 'Highlander', 'RX350', 'Sienna', 'Tacoma (some)'],
    weight: 9,
  },
  {
    code: '2AZ-FE',
    brand: 'Toyota',
    family: 'AZ',
    displacement: '2.4L',
    config: 'I4 NA',
    notes: 'Very common, reliable in later years (watch early oil consumption)',
    applications: ['Camry', 'RAV4', 'Highlander', 'Scion tC'],
    weight: 8,
  },
  {
    code: '1ZZ-FE',
    brand: 'Toyota',
    family: 'ZZ',
    displacement: '1.8L',
    config: 'I4 NA',
    notes: 'Widespread economy four',
    applications: ['Corolla', 'Matrix', 'Celica', 'MR2 Spyder'],
    weight: 8,
  },
  {
    code: '2ZR-FE',
    brand: 'Toyota',
    family: 'ZR',
    displacement: '1.8L',
    config: 'I4 NA',
    notes: 'Modern Corolla-family engine',
    applications: ['Corolla', 'Auris', 'Matrix', 'Prius (related variants)'],
    weight: 8,
  },
  {
    code: '1GR-FE',
    brand: 'Toyota',
    family: 'GR',
    displacement: '4.0L',
    config: 'V6 NA',
    notes: 'Truck/SUV workhorse',
    applications: ['Tacoma', '4Runner', 'FJ Cruiser', 'Land Cruiser Prado'],
    weight: 8,
  },
  {
    code: '2AR-FE',
    brand: 'Toyota',
    family: 'AR',
    displacement: '2.5L',
    config: 'I4 NA',
    notes: 'Highly reliable',
    applications: ['Camry', 'RAV4', 'Highlander', 'Scion tC'],
    weight: 9,
  },
  {
    code: '1JZ-GTE',
    brand: 'Toyota',
    family: 'JZ',
    displacement: '2.5L',
    config: 'I6 Twin-Turbo',
    notes: 'Performance JZ sibling',
    applications: ['Chaser', 'Mark II', 'Soarer', 'Supra (some)'],
    weight: 9,
  },
  {
    code: '2JZ-GE',
    brand: 'Toyota',
    family: 'JZ',
    displacement: '3.0L',
    config: 'I6 NA',
    notes: 'Naturally aspirated JZ',
    applications: ['Supra', 'SC300', 'GS300', 'IS300'],
    weight: 8,
  },
  {
    code: '3S-GTE',
    brand: 'Toyota',
    family: 'S',
    displacement: '2.0L',
    config: 'I4 Turbo',
    notes: 'Classic turbo four',
    applications: ['Celica GT-Four', 'MR2 Turbo', 'Caldina'],
    weight: 9,
  },
  {
    code: '4A-GE',
    brand: 'Toyota',
    family: 'A',
    displacement: '1.6L',
    config: 'I4',
    notes: 'High-revving classic',
    applications: ['AE86 Corolla', 'MR2', 'Some Celica'],
    weight: 9,
  },
  {
    code: '1UZ-FE',
    brand: 'Toyota',
    family: 'UZ',
    displacement: '4.0L',
    config: 'V8 NA',
    notes: 'Smooth luxury V8',
    applications: ['LS400', 'SC400', 'GS400', 'Some Crown'],
    weight: 8,
  },
  {
    code: 'A25A-FKS',
    brand: 'Toyota',
    family: 'Dynamic Force',
    aliases: ['A25A'],
    displacement: '2.5L',
    config: 'I4',
    notes: 'Modern Dynamic Force four',
    applications: ['Camry', 'RAV4', 'Highlander', 'Crown'],
    weight: 8,
  },

  // ——— Honda ———
  {
    code: 'K20A',
    brand: 'Honda',
    family: 'K-series',
    displacement: '2.0L',
    config: 'I4 DOHC i-VTEC',
    notes: 'High-revving performance variant',
    applications: ['Integra Type R', 'Civic Type R (EP3)', 'Accord Euro R', 'Some RSX'],
    powerRange: '212–220 hp',
    weight: 10,
  },
  {
    code: 'K24A',
    brand: 'Honda',
    family: 'K-series',
    displacement: '2.4L',
    config: 'I4 DOHC i-VTEC',
    notes: 'Larger K-series, strong torque',
    applications: ['Accord', 'CR-V', 'TSX', 'Element', 'Odyssey (some)'],
    weight: 9,
  },
  {
    code: 'B18C',
    brand: 'Honda',
    family: 'B-series',
    displacement: '1.8L',
    config: 'I4 DOHC VTEC',
    notes: 'Integra Type R / GSR legend',
    applications: ['Integra Type R', 'Integra GSR'],
    weight: 10,
  },
  {
    code: 'B16A',
    brand: 'Honda',
    family: 'B-series',
    displacement: '1.6L',
    config: 'I4 DOHC VTEC',
    notes: 'High-revving VTEC',
    applications: ['Civic SiR', 'Civic Type R (early)', 'Del Sol'],
    weight: 9,
  },
  {
    code: 'F20C',
    brand: 'Honda',
    family: 'F-series',
    displacement: '2.0L',
    config: 'I4 DOHC VTEC',
    notes: 'S2000 engine',
    applications: ['Honda S2000'],
    powerRange: '240 hp',
    weight: 10,
  },
  {
    code: 'K20C1',
    brand: 'Honda',
    family: 'K-series',
    displacement: '2.0L',
    config: 'I4 Turbo',
    notes: 'Modern Type R turbo',
    applications: ['Civic Type R (FK8/FL5)'],
    powerRange: '306–315 hp',
    weight: 9,
  },
  {
    code: 'J35A',
    brand: 'Honda',
    family: 'J-series',
    displacement: '3.5L',
    config: 'V6',
    notes: 'Common V6',
    applications: ['Accord', 'Odyssey', 'Pilot', 'Ridgeline', 'MDX'],
    weight: 8,
  },
  {
    code: 'L15B',
    brand: 'Honda',
    family: 'L-series',
    displacement: '1.5L',
    config: 'I4 Turbo',
    notes: 'Modern turbo four',
    applications: ['Civic', 'CR-V', 'Accord (some)'],
    weight: 8,
  },
  {
    code: 'H22A',
    brand: 'Honda',
    family: 'H-series',
    displacement: '2.2L',
    config: 'I4 DOHC VTEC',
    notes: 'Prelude performance',
    applications: ['Prelude VTEC', 'Some Accords'],
    weight: 8,
  },

  // ——— BMW ———
  {
    code: 'B58',
    brand: 'BMW',
    family: 'B-series',
    aliases: ['B58B30'],
    displacement: '3.0L',
    config: 'I6 Turbo',
    notes: 'Modern modular, strong & tunable',
    applications: ['340i', '440i', '540i', 'X3/X4/X5 M40i', 'Supra (A90)', 'Z4'],
    powerRange: '335–382 hp',
    weight: 10,
  },
  {
    code: 'N54',
    brand: 'BMW',
    family: 'N-series',
    displacement: '3.0L',
    config: 'I6 Twin-Turbo',
    notes: 'Early twin-turbo, high power potential but known issues (HPFP, injectors, wastegates)',
    applications: ['135i', '335i', '535i', '1M', 'Z4 35i (2006–2010s)'],
    powerRange: '300–335 hp',
    weight: 9,
  },
  {
    code: 'N55',
    brand: 'BMW',
    family: 'N-series',
    displacement: '3.0L',
    config: 'I6 Single Turbo',
    notes: 'Successor to N54',
    applications: ['335i', '535i', 'X5 35i', '135i (later)'],
    weight: 8,
  },
  {
    code: 'S55',
    brand: 'BMW',
    family: 'S-series',
    displacement: '3.0L',
    config: 'I6 Twin-Turbo',
    notes: 'M performance',
    applications: ['M3/M4 (F80/F82)'],
    weight: 9,
  },
  {
    code: 'S58',
    brand: 'BMW',
    family: 'S-series',
    displacement: '3.0L',
    config: 'I6 Twin-Turbo',
    notes: 'Current M engine',
    applications: ['M3/M4 (G80/G82)', 'X3M/X4M'],
    weight: 9,
  },
  {
    code: 'B48',
    brand: 'BMW',
    family: 'B-series',
    displacement: '2.0L',
    config: 'I4 Turbo',
    notes: 'Modular four',
    applications: ['320i/330i', '120i', 'X1/X2', 'Mini JCW'],
    weight: 8,
  },
  {
    code: 'N52',
    brand: 'BMW',
    family: 'N-series',
    displacement: '3.0L',
    config: 'I6 NA',
    notes: 'Reliable naturally aspirated',
    applications: ['330i', '530i', 'X3', 'Z4 (2000s–2010s)'],
    weight: 8,
  },

  // ——— GM / Chevrolet ———
  {
    code: 'LS3',
    brand: 'Chevrolet',
    family: 'LS',
    aliases: ['LS3 6.2'],
    displacement: '6.2L',
    config: 'V8',
    notes: 'LS-family performance, aluminum block',
    applications: ['Corvette C6', 'Camaro SS', 'Some CTS-V / trucks (crate)'],
    powerRange: '430–436 hp',
    weight: 10,
  },
  {
    code: 'LS1',
    brand: 'Chevrolet',
    family: 'LS',
    displacement: '5.7L',
    config: 'V8',
    notes: 'Early LS performance',
    applications: ['Corvette C5', 'Camaro', 'Firebird'],
    weight: 9,
  },
  {
    code: 'LS7',
    brand: 'Chevrolet',
    family: 'LS',
    displacement: '7.0L',
    config: 'V8',
    notes: 'High-revving Z06',
    applications: ['Corvette Z06 (C6)'],
    weight: 9,
  },
  {
    code: 'LT1',
    brand: 'Chevrolet',
    family: 'LT',
    displacement: '6.2L',
    config: 'V8',
    notes: 'Modern LT small-block',
    applications: ['Corvette C7', 'Camaro SS'],
    weight: 9,
  },

  // ——— Ford ———
  {
    code: 'Coyote 5.0',
    brand: 'Ford',
    family: 'Coyote',
    aliases: ['5.0 Coyote', '5.0L Coyote'],
    displacement: '5.0L',
    config: 'V8 DOHC',
    notes: 'Modern modular V8, high-revving',
    applications: ['Mustang GT', 'F-150 (some years)'],
    powerRange: '412–480 hp',
    weight: 10,
  },

  // ——— Nissan ———
  {
    code: 'RB26DETT',
    brand: 'Nissan',
    family: 'RB',
    aliases: ['RB26'],
    displacement: '2.6L',
    config: 'I6 Twin-Turbo',
    notes: 'Legendary GT-R engine, cast-iron block',
    applications: ['Skyline GT-R (R32/R33/R34)'],
    powerRange: '276 hp (stock)',
    weight: 10,
  },
  {
    code: 'VR38DETT',
    brand: 'Nissan',
    family: 'VR',
    displacement: '3.8L',
    config: 'V6 Twin-Turbo',
    notes: 'GT-R engine',
    applications: ['Nissan GT-R (R35)'],
    powerRange: '480–600 hp',
    weight: 10,
  },
  {
    code: 'VQ35DE',
    brand: 'Nissan',
    family: 'VQ',
    displacement: '3.5L',
    config: 'V6',
    notes: 'Extremely common V6',
    applications: ['350Z', 'G35', 'Altima', 'Maxima', 'Murano'],
    weight: 9,
  },
  {
    code: 'SR20DET',
    brand: 'Nissan',
    family: 'SR',
    displacement: '2.0L',
    config: 'I4 Turbo',
    notes: 'Classic turbo four',
    applications: ['Silvia', '180SX', 'Pulsar GTI-R'],
    weight: 9,
  },

  // ——— Subaru ———
  {
    code: 'EJ257',
    brand: 'Subaru',
    family: 'EJ',
    displacement: '2.5L',
    config: 'Flat-4 Turbo',
    notes: 'STI engine',
    applications: ['WRX STI'],
    powerRange: '305–310 hp',
    weight: 9,
  },
  {
    code: 'EJ255',
    brand: 'Subaru',
    family: 'EJ',
    displacement: '2.5L',
    config: 'Flat-4 Turbo',
    notes: 'WRX engine',
    applications: ['WRX', 'Forester XT', 'Legacy GT'],
    weight: 8,
  },
  {
    code: 'FA20',
    brand: 'Subaru',
    family: 'FA',
    displacement: '2.0L',
    config: 'Flat-4',
    notes: 'Modern boxer (NA & turbo variants)',
    applications: ['BRZ', '86', 'WRX (FA20DIT)'],
    weight: 8,
  },

  // ——— Mitsubishi ———
  {
    code: '4G63T',
    brand: 'Mitsubishi',
    family: '4G63',
    aliases: ['4G63 Turbo'],
    displacement: '2.0L',
    config: 'I4 Turbo',
    notes: 'Evo legend',
    applications: ['Lancer Evolution', 'Eclipse GST/GSX'],
    powerRange: '195–291 hp',
    weight: 10,
  },
  {
    code: '4B11T',
    brand: 'Mitsubishi',
    family: '4B',
    displacement: '2.0L',
    config: 'I4 Turbo',
    notes: 'Modern Evo X engine',
    applications: ['Lancer Evolution X'],
    weight: 9,
  },

  // ——— Volkswagen / Audi ———
  {
    code: 'EA888',
    brand: 'Volkswagen',
    family: 'EA888',
    aliases: ['EA888 Gen3'],
    displacement: '1.8/2.0L',
    config: 'I4 Turbo TSI',
    notes: 'Widely used modular turbo four',
    applications: ['Golf GTI/R', 'A3/A4/S3', 'Octavia', 'Many MQB cars'],
    powerRange: '220–315 hp',
    weight: 8,
  },
  {
    code: 'ALH',
    brand: 'Volkswagen',
    family: 'TDI',
    displacement: '1.9L',
    config: 'I4 TDI',
    notes: 'Popular older TDI',
    applications: ['Golf', 'Jetta', 'New Beetle (late 90s–2000s)'],
    weight: 8,
  },
];
