-- Seed: 30 of the most commonly searched, well-documented generic OBD-II
-- codes (SAE J2012 standard). Deliberately no repair-cost fields — this
-- tool is purely diagnostic (meaning, causes, symptoms, severity), which
-- keeps it identically accurate and useful in every country with zero
-- currency/localization work needed.
-- Run this in the Supabase SQL editor after obd_codes_migration.sql.

INSERT INTO obd_codes (
  code, slug, title,
  system, category, is_generic,
  severity, diy_difficulty,
  description,
  common_causes, symptoms, diagnostic_steps, related_codes, faqs,
  meta_title, meta_description,
  is_published
) VALUES
(
  'P0300', 'p0300', 'Random/Multiple Cylinder Misfire Detected',
  'Powertrain', 'Misfire', true,
  'High', 'Moderate',
  'The engine control module has detected misfires across multiple cylinders that don''t follow a single-cylinder pattern. This means combustion isn''t happening properly in more than one cylinder, at different times.',
  '["Worn or fouled spark plugs", "Failing ignition coils", "Vacuum leak (unmetered air entering the engine)", "Low fuel pressure or a clogged fuel filter", "Dirty or failing fuel injectors", "Low compression from worn rings or valves", "Contaminated or old fuel"]'::jsonb,
  '["Rough idle or engine shaking", "Noticeable loss of power under acceleration", "Check engine light flashing (flashing means stop driving soon)", "Poor fuel economy", "Engine hesitation or stumbling"]'::jsonb,
  '["Check for a flashing check engine light \u2014 if flashing, reduce speed and get it checked immediately, a sustained misfire can damage the catalytic converter", "Inspect and test spark plugs and ignition coils first, they''re the most common cause", "Check for vacuum leaks around intake hoses and gaskets using a smoke test or spray test", "Test fuel pressure at the rail", "If those check out, a compression or leak-down test will reveal mechanical issues"]'::jsonb,
  '["P0301", "P0302", "P0303", "P0304", "P0171", "P0174"]'::jsonb,
  '[{"question": "Is P0300 dangerous to keep driving with?", "answer": "If the check engine light is flashing, yes \u2014 stop driving soon and get it checked. A steady (non-flashing) light means it''s safer to drive but should still be diagnosed promptly, since unburned fuel from a misfire can damage the catalytic converter over time."}, {"question": "Can bad fuel cause a P0300 code?", "answer": "Yes. Contaminated, watered-down, or very old fuel can cause poor combustion across multiple cylinders and trigger this code, especially after filling up at an unreliable station."}]'::jsonb,
  'P0300 Code: Random/Multiple Cylinder Misfire Detected | Naira Autos',
  'The engine control module has detected misfires across multiple cylinders that don''t follow a single-cylinder pattern. This means combustion isn''t hap',
  true
),
(
  'P0301', 'p0301', 'Cylinder 1 Misfire Detected',
  'Powertrain', 'Misfire', true,
  'High', 'Moderate',
  'The engine control module has detected a misfire specifically in cylinder 1 — this cylinder isn''t burning fuel properly on every cycle.',
  '["Worn or fouled spark plug in that cylinder", "Failing ignition coil for that cylinder", "Faulty or clogged fuel injector for that cylinder", "Low compression in that cylinder (worn rings, valve, or head gasket)", "Damaged or disconnected spark plug wire (on older coil types)"]'::jsonb,
  '["Rough idle, often with a noticeable single-cylinder shake", "Engine hesitation or stumble under load", "Check engine light, flashing if the misfire is severe", "Popping or ticking sound from the exhaust"]'::jsonb,
  '["Swap the spark plug and ignition coil from cylinder 1 with another cylinder to see if the misfire follows the part", "Inspect the fuel injector for that cylinder for clogging or electrical faults", "Run a compression test on that cylinder specifically to rule out a mechanical issue", "Check for oil in the spark plug well, which can indicate a valve cover gasket leak causing plug fouling"]'::jsonb,
  '["P0300", "P0302", "P0303", "P0304"]'::jsonb,
  '[{"question": "Do I need to replace all spark plugs or just cylinder 1''s?", "answer": "Start with just the affected cylinder''s plug and coil. If the misfire clears, you likely found the cause. If plugs are old and due for replacement anyway, doing all of them at once is common practice."}]'::jsonb,
  'P0301 Code: Cylinder 1 Misfire Detected | Naira Autos',
  'The engine control module has detected a misfire specifically in cylinder 1 — this cylinder isn''t burning fuel properly on every cycle.',
  true
),
(
  'P0302', 'p0302', 'Cylinder 2 Misfire Detected',
  'Powertrain', 'Misfire', true,
  'High', 'Moderate',
  'The engine control module has detected a misfire specifically in cylinder 2.',
  '["Worn or fouled spark plug in that cylinder", "Failing ignition coil for that cylinder", "Faulty or clogged fuel injector for that cylinder", "Low compression in that cylinder"]'::jsonb,
  '["Rough idle", "Engine hesitation under load", "Check engine light, flashing if severe", "Reduced power"]'::jsonb,
  '["Swap the spark plug and coil from cylinder 2 with a known-good cylinder to isolate the fault", "Check the fuel injector for that cylinder", "Run a cylinder-specific compression test if electrical parts test fine"]'::jsonb,
  '["P0300", "P0301", "P0303"]'::jsonb,
  '[]'::jsonb,
  'P0302 Code: Cylinder 2 Misfire Detected | Naira Autos',
  'The engine control module has detected a misfire specifically in cylinder 2.',
  true
),
(
  'P0303', 'p0303', 'Cylinder 3 Misfire Detected',
  'Powertrain', 'Misfire', true,
  'High', 'Moderate',
  'The engine control module has detected a misfire specifically in cylinder 3.',
  '["Worn or fouled spark plug in that cylinder", "Failing ignition coil for that cylinder", "Faulty or clogged fuel injector for that cylinder", "Low compression in that cylinder"]'::jsonb,
  '["Rough idle", "Engine hesitation under load", "Check engine light, flashing if severe", "Reduced power"]'::jsonb,
  '["Swap the spark plug and coil from cylinder 3 with a known-good cylinder to isolate the fault", "Check the fuel injector for that cylinder", "Run a cylinder-specific compression test if electrical parts test fine"]'::jsonb,
  '["P0300", "P0301", "P0304"]'::jsonb,
  '[]'::jsonb,
  'P0303 Code: Cylinder 3 Misfire Detected | Naira Autos',
  'The engine control module has detected a misfire specifically in cylinder 3.',
  true
),
(
  'P0304', 'p0304', 'Cylinder 4 Misfire Detected',
  'Powertrain', 'Misfire', true,
  'High', 'Moderate',
  'The engine control module has detected a misfire specifically in cylinder 4.',
  '["Worn or fouled spark plug in that cylinder", "Failing ignition coil for that cylinder", "Faulty or clogged fuel injector for that cylinder", "Low compression in that cylinder"]'::jsonb,
  '["Rough idle", "Engine hesitation under load", "Check engine light, flashing if severe", "Reduced power"]'::jsonb,
  '["Swap the spark plug and coil from cylinder 4 with a known-good cylinder to isolate the fault", "Check the fuel injector for that cylinder", "Run a cylinder-specific compression test if electrical parts test fine"]'::jsonb,
  '["P0300", "P0302", "P0303"]'::jsonb,
  '[]'::jsonb,
  'P0304 Code: Cylinder 4 Misfire Detected | Naira Autos',
  'The engine control module has detected a misfire specifically in cylinder 4.',
  true
),
(
  'P0420', 'p0420', 'Catalyst System Efficiency Below Threshold (Bank 1)',
  'Powertrain', 'Emissions', true,
  'Medium', 'Hard',
  'The engine control module is comparing oxygen sensor readings before and after the catalytic converter, and the difference isn''t big enough — meaning the converter isn''t cleaning up exhaust gases as effectively as it should.',
  '["Aging or failing catalytic converter", "Engine misfire allowing unburned fuel to damage the converter", "Oxygen sensor failure giving a false reading", "Exhaust leak upstream of the converter", "Running rich or lean for an extended period, which contaminates the converter"]'::jsonb,
  '["Usually no noticeable drivability symptoms", "Check engine light on", "May fail an emissions/roadworthiness test", "Slight sulfur or rotten-egg smell in severe cases"]'::jsonb,
  '["Rule out a misfire or fuel trim problem first \u2014 fix any P03xx or P017x codes before replacing the converter", "Inspect the exhaust for leaks between the engine and the converter", "Check both upstream and downstream oxygen sensor readings with a scan tool", "If sensors and fuel trims are healthy, the converter itself is likely worn and due for replacement"]'::jsonb,
  '["P0430", "P0171", "P0174", "P0300"]'::jsonb,
  '[{"question": "Can I drive with a P0420 code?", "answer": "Yes, in most cases it won''t affect how the car drives. But it typically means the car will fail an emissions or roadworthiness test, and ignoring the underlying cause (like a misfire) can lead to bigger repairs."}, {"question": "Will a cheap aftermarket catalytic converter fix this?", "answer": "It can, but a low-quality converter can trigger the same code again quickly. Address any misfire or fuel trim issue first, since a healthy engine won''t damage a new converter the way a misfiring one would."}]'::jsonb,
  'P0420 Code: Catalyst System Efficiency Below Threshold (Bank 1) | Naira Autos',
  'The engine control module is comparing oxygen sensor readings before and after the catalytic converter, and the difference isn''t big enough — meaning ',
  true
),
(
  'P0430', 'p0430', 'Catalyst System Efficiency Below Threshold (Bank 2)',
  'Powertrain', 'Emissions', true,
  'Medium', 'Hard',
  'Same issue as P0420, but on the engine''s second bank of cylinders (Bank 2) — common on V6 and V8 engines with two exhaust banks.',
  '["Aging or failing catalytic converter on Bank 2", "Engine misfire on Bank 2 cylinders", "Oxygen sensor failure on Bank 2", "Exhaust leak on the Bank 2 side"]'::jsonb,
  '["Usually no noticeable drivability symptoms", "Check engine light on", "May fail an emissions test"]'::jsonb,
  '["Rule out any Bank 2 misfire codes first", "Check for exhaust leaks on that side", "Test Bank 2 oxygen sensors", "Replace the Bank 2 converter if sensors and engine performance are otherwise healthy"]'::jsonb,
  '["P0420", "P0174", "P0174"]'::jsonb,
  '[]'::jsonb,
  'P0430 Code: Catalyst System Efficiency Below Threshold (Bank 2) | Naira Autos',
  'Same issue as P0420, but on the engine''s second bank of cylinders (Bank 2) — common on V6 and V8 engines with two exhaust banks.',
  true
),
(
  'P0171', 'p0171', 'System Too Lean (Bank 1)',
  'Powertrain', 'Fuel & Air Metering', true,
  'Medium', 'Moderate',
  'The engine control module is adding more fuel than normal to compensate for a mixture that''s running leaner (too much air, not enough fuel) than it should — and it''s had to add more correction than it''s allowed to.',
  '["Vacuum leak (cracked hose, bad intake gasket)", "Failing mass airflow (MAF) sensor", "Weak fuel pump or low fuel pressure", "Clogged or dirty fuel injectors", "Faulty oxygen sensor giving an inaccurate reading", "Exhaust leak before the oxygen sensor"]'::jsonb,
  '["Rough or high idle", "Hesitation or stumbling on acceleration", "Check engine light on", "Reduced fuel economy", "Occasional stalling"]'::jsonb,
  '["Inspect all vacuum hoses and intake gaskets for cracks or leaks \u2014 this is the most common cause", "Check the MAF sensor for dirt or contamination, and clean or replace as needed", "Test fuel pressure against the manufacturer''s specification", "Check for exhaust leaks upstream of the oxygen sensor"]'::jsonb,
  '["P0174", "P0420", "P0101"]'::jsonb,
  '[{"question": "What''s the difference between P0171 and P0174?", "answer": "P0171 is Bank 1, P0174 is Bank 2 \u2014 the same lean-mixture issue, just detected on a different bank of cylinders. On 4-cylinder engines with only one bank, you''ll only ever see P0171."}]'::jsonb,
  'P0171 Code: System Too Lean (Bank 1) | Naira Autos',
  'The engine control module is adding more fuel than normal to compensate for a mixture that''s running leaner (too much air, not enough fuel) than it sh',
  true
),
(
  'P0174', 'p0174', 'System Too Lean (Bank 2)',
  'Powertrain', 'Fuel & Air Metering', true,
  'Medium', 'Moderate',
  'Same lean-mixture issue as P0171, but detected on Bank 2 — the engine control module has run out of correction it''s allowed to apply to compensate for excess air on that bank.',
  '["Vacuum leak on the Bank 2 side", "Failing mass airflow (MAF) sensor", "Weak fuel pump or low fuel pressure", "Clogged fuel injectors on Bank 2", "Exhaust leak upstream of the Bank 2 oxygen sensor"]'::jsonb,
  '["Rough or high idle", "Hesitation on acceleration", "Check engine light on", "Reduced fuel economy"]'::jsonb,
  '["Inspect vacuum hoses and intake gaskets on the Bank 2 side", "Check the MAF sensor", "Test fuel pressure", "Check for exhaust leaks upstream of the Bank 2 oxygen sensor"]'::jsonb,
  '["P0171", "P0430", "P0101"]'::jsonb,
  '[]'::jsonb,
  'P0174 Code: System Too Lean (Bank 2) | Naira Autos',
  'Same lean-mixture issue as P0171, but detected on Bank 2 — the engine control module has run out of correction it''s allowed to apply to compensate for',
  true
),
(
  'P0128', 'p0128', 'Coolant Thermostat (Coolant Temperature Below Regulating Temperature)',
  'Powertrain', 'Cooling System', true,
  'Low', 'Easy',
  'The engine is taking too long to reach normal operating temperature, or isn''t reaching it at all — usually because the thermostat is stuck open.',
  '["Thermostat stuck open", "Faulty coolant temperature sensor", "Low coolant level", "Cooling system fault (rare)"]'::jsonb,
  '["Heater takes longer than normal to blow warm air", "Temperature gauge stays lower than usual", "Check engine light on", "Slightly reduced fuel economy in cold weather"]'::jsonb,
  '["Check coolant level first \u2014 top up if low and see if the code clears after a drive cycle", "Test the coolant temperature sensor''s readings against actual engine temperature", "If coolant and sensor are fine, the thermostat is stuck open and needs replacing \u2014 it''s an inexpensive, common part"]'::jsonb,
  '["P0125", "P0117", "P0118"]'::jsonb,
  '[{"question": "Is P0128 urgent?", "answer": "No, it''s low severity \u2014 the car will still run fine, but a stuck-open thermostat hurts fuel economy and cabin heating, especially in cold weather. It''s worth fixing but not an emergency."}]'::jsonb,
  'P0128 Code: Coolant Thermostat (Coolant Temperature Below Regulating Temperature) | Naira Autos',
  'The engine is taking too long to reach normal operating temperature, or isn''t reaching it at all — usually because the thermostat is stuck open.',
  true
),
(
  'P0442', 'p0442', 'Evaporative Emission Control System Leak Detected (Small Leak)',
  'Powertrain', 'Emissions', true,
  'Low', 'Easy',
  'The EVAP system, which captures fuel vapor from the tank instead of letting it escape into the air, has detected a small leak somewhere in the sealed system.',
  '["Loose or damaged fuel cap (the single most common cause)", "Cracked EVAP hose", "Faulty purge valve or vent valve", "Small crack in the charcoal canister"]'::jsonb,
  '["Usually no drivability symptoms at all", "Check engine light on", "Possible faint fuel smell in rare cases"]'::jsonb,
  '["Check the fuel cap first \u2014 make sure it''s tightened properly and the seal isn''t cracked, this fixes the majority of P0442 cases", "Inspect visible EVAP hoses for cracks or disconnection", "If the cap and hoses look fine, a smoke test at a repair shop will pinpoint the leak location"]'::jsonb,
  '["P0455", "P0456", "P0441"]'::jsonb,
  '[{"question": "My check engine light for P0442 came on right after I filled up my tank \u2014 why?", "answer": "You likely didn''t tighten the fuel cap fully after refueling. Tighten it until it clicks, then the code should clear itself after a few drive cycles."}]'::jsonb,
  'P0442 Code: Evaporative Emission Control System Leak Detected (Small Leak) | Naira Autos',
  'The EVAP system, which captures fuel vapor from the tank instead of letting it escape into the air, has detected a small leak somewhere in the sealed ',
  true
),
(
  'P0455', 'p0455', 'Evaporative Emission Control System Leak Detected (Large Leak)',
  'Powertrain', 'Emissions', true,
  'Low', 'Easy',
  'Same EVAP system as P0442, but the leak detected is large enough that it''s easier to find — often a completely missing or open component rather than a small crack.',
  '["Missing, loose, or damaged fuel cap", "Disconnected or badly cracked EVAP hose", "Faulty purge or vent valve stuck open"]'::jsonb,
  '["Usually no drivability symptoms", "Check engine light on", "Possible fuel smell near the tank or engine bay"]'::jsonb,
  '["Check that the fuel cap is present, undamaged, and properly tightened", "Visually trace EVAP hoses from the tank to the engine for anything disconnected or badly cracked", "A smoke test will quickly show a large leak, since it''s more obvious than for P0442"]'::jsonb,
  '["P0442", "P0456"]'::jsonb,
  '[]'::jsonb,
  'P0455 Code: Evaporative Emission Control System Leak Detected (Large Leak) | Naira Autos',
  'Same EVAP system as P0442, but the leak detected is large enough that it''s easier to find — often a completely missing or open component rather than a',
  true
),
(
  'P0401', 'p0401', 'Exhaust Gas Recirculation Flow Insufficient Detected',
  'Powertrain', 'Emissions', true,
  'Medium', 'Moderate',
  'The EGR system, which recirculates a small amount of exhaust gas back into the engine to reduce emissions and combustion temperature, isn''t flowing enough gas.',
  '["Clogged EGR passages or valve from carbon buildup (very common on older/high-mileage engines)", "Faulty EGR valve or its solenoid", "Failed EGR position sensor", "Vacuum leak affecting EGR valve operation"]'::jsonb,
  '["Engine may hesitate or ping/knock under load", "Rough idle in some cases", "Check engine light on", "Slightly higher emissions"]'::jsonb,
  '["Remove and inspect the EGR valve and passages for carbon buildup \u2014 cleaning often resolves this", "Test the EGR valve''s operation with a scan tool if cleaning doesn''t help", "Check the EGR position sensor and related wiring"]'::jsonb,
  '["P0402", "P0405"]'::jsonb,
  '[]'::jsonb,
  'P0401 Code: Exhaust Gas Recirculation Flow Insufficient Detected | Naira Autos',
  'The EGR system, which recirculates a small amount of exhaust gas back into the engine to reduce emissions and combustion temperature, isn''t flowing en',
  true
),
(
  'P0106', 'p0106', 'Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem',
  'Powertrain', 'Sensors', true,
  'Medium', 'Moderate',
  'The MAP sensor, which measures intake manifold pressure to help calculate how much fuel to inject, is sending a reading that doesn''t match what the engine control module expects.',
  '["Vacuum leak near the MAP sensor or its hose", "Faulty MAP sensor", "Damaged or corroded wiring/connector to the sensor", "Dirty or clogged sensor port"]'::jsonb,
  '["Rough idle", "Poor acceleration", "Check engine light on", "Reduced fuel economy"]'::jsonb,
  '["Inspect the vacuum hose connected to the MAP sensor for cracks or a loose fit", "Check the sensor''s wiring and connector for corrosion or damage", "Test the sensor''s output against a known-good reading; replace if out of range"]'::jsonb,
  '["P0107", "P0108"]'::jsonb,
  '[]'::jsonb,
  'P0106 Code: Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem | Naira Autos',
  'The MAP sensor, which measures intake manifold pressure to help calculate how much fuel to inject, is sending a reading that doesn''t match what the en',
  true
),
(
  'P0113', 'p0113', 'Intake Air Temperature Circuit High Input',
  'Powertrain', 'Sensors', true,
  'Low', 'Easy',
  'The intake air temperature (IAT) sensor is reporting an unusually high (or open-circuit) reading, which throws off the engine''s fuel and timing calculations.',
  '["Faulty or damaged IAT sensor", "Corroded or disconnected wiring/connector", "Sensor contaminated with dirt or oil"]'::jsonb,
  '["Usually minimal drivability impact", "Slightly rough cold starts in some cases", "Check engine light on", "Possible small fuel economy drop"]'::jsonb,
  '["Inspect the IAT sensor connector for corrosion or a loose fit", "Check the sensor''s resistance against the manufacturer''s specification at a known temperature", "Replace the sensor if it''s out of range \u2014 it''s an inexpensive, easy part to swap"]'::jsonb,
  '["P0112", "P0114"]'::jsonb,
  '[]'::jsonb,
  'P0113 Code: Intake Air Temperature Circuit High Input | Naira Autos',
  'The intake air temperature (IAT) sensor is reporting an unusually high (or open-circuit) reading, which throws off the engine''s fuel and timing calcul',
  true
),
(
  'P0135', 'p0135', 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)',
  'Powertrain', 'Sensors', true,
  'Medium', 'Moderate',
  'The heater built into the oxygen sensor (which helps it reach operating temperature quickly) has an electrical fault.',
  '["Failed oxygen sensor heater element", "Damaged or corroded sensor wiring/connector", "Blown fuse for the O2 sensor heater circuit"]'::jsonb,
  '["Usually no immediate drivability symptoms", "Check engine light on", "Slightly worse fuel economy and emissions until the sensor fully warms up during driving"]'::jsonb,
  '["Check the fuse for the O2 sensor heater circuit first \u2014 it''s the cheapest thing to rule out", "Inspect the sensor''s wiring and connector for damage or corrosion", "Test the heater circuit''s resistance; replace the sensor if the heater element itself has failed"]'::jsonb,
  '["P0141", "P0155"]'::jsonb,
  '[]'::jsonb,
  'P0135 Code: O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1) | Naira Autos',
  'The heater built into the oxygen sensor (which helps it reach operating temperature quickly) has an electrical fault.',
  true
),
(
  'P0121', 'p0121', 'Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance Problem',
  'Powertrain', 'Sensors', true,
  'Medium', 'Moderate',
  'The throttle position sensor is sending a signal that''s outside the range the engine control module expects for normal operation.',
  '["Faulty throttle position sensor", "Dirty or worn throttle body", "Damaged wiring or connector to the sensor"]'::jsonb,
  '["Hesitation or jerky acceleration", "Idle may surge or fluctuate", "Check engine light on", "In some cases the car may enter a reduced-power ''limp'' mode"]'::jsonb,
  '["Clean the throttle body, since dirt buildup is a common cause of erratic sensor readings", "Inspect the sensor''s wiring and connector for damage", "Test the sensor''s voltage output through its full range of motion; replace if it doesn''t track smoothly"]'::jsonb,
  '["P0122", "P0123"]'::jsonb,
  '[]'::jsonb,
  'P0121 Code: Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance Problem | Naira Autos',
  'The throttle position sensor is sending a signal that''s outside the range the engine control module expects for normal operation.',
  true
),
(
  'P0505', 'p0505', 'Idle Control System Malfunction',
  'Powertrain', 'Idle Control', true,
  'Medium', 'Moderate',
  'The engine control module can''t keep the idle speed within its expected range, either too high, too low, or fluctuating.',
  '["Dirty or carbon-fouled throttle body/idle air control valve", "Vacuum leak", "Failing idle air control (IAC) valve", "Carbon buildup on intake valves"]'::jsonb,
  '["Idle that hunts up and down or is unusually high/low", "Stalling at stops in severe cases", "Check engine light on"]'::jsonb,
  '["Clean the throttle body and idle air control valve \u2014 this resolves the majority of cases", "Check for vacuum leaks around the intake", "Test the IAC valve''s operation and replace if faulty"]'::jsonb,
  '["P0506", "P0507"]'::jsonb,
  '[]'::jsonb,
  'P0505 Code: Idle Control System Malfunction | Naira Autos',
  'The engine control module can''t keep the idle speed within its expected range, either too high, too low, or fluctuating.',
  true
),
(
  'P0700', 'p0700', 'Transmission Control System Malfunction',
  'Powertrain', 'Transmission', true,
  'High', 'Professional Only',
  'This is a general code meaning the transmission control module has detected a fault and stored a more specific code internally. It''s a signal to check the transmission control module for detailed codes, not a diagnosis on its own.',
  '["A more specific transmission fault (solenoid, sensor, or internal issue) \u2014 the general P0700 is just a flag", "Low or degraded transmission fluid", "Wiring or connector issue to the transmission control module"]'::jsonb,
  '["Harsh, delayed, or erratic gear shifts", "Transmission may enter a ''limp'' mode with limited gears", "Check engine or transmission warning light on"]'::jsonb,
  '["Scan the transmission control module specifically (not just the engine) for the detailed fault code behind P0700", "Check transmission fluid level and condition \u2014 low or burnt fluid is a common contributing factor", "Address the specific underlying code found before considering this resolved"]'::jsonb,
  '["P0740", "P0742", "P0716"]'::jsonb,
  '[{"question": "Why does my scan tool only show P0700 with no other details?", "answer": "P0700 is a generic ''flag'' code from the engine control module telling you the transmission module has its own stored codes. A basic scan tool may not read transmission-specific codes \u2014 you may need a scan tool capable of reading the transmission control module, or a shop visit."}]'::jsonb,
  'P0700 Code: Transmission Control System Malfunction | Naira Autos',
  'This is a general code meaning the transmission control module has detected a fault and stored a more specific code internally. It''s a signal to check',
  true
),
(
  'P0740', 'p0740', 'Torque Converter Clutch Circuit Malfunction',
  'Powertrain', 'Transmission', true,
  'High', 'Professional Only',
  'The torque converter clutch, which locks the engine and transmission together at cruising speed for better fuel economy, isn''t engaging or disengaging correctly.',
  '["Faulty torque converter clutch solenoid", "Low or contaminated transmission fluid", "Wiring fault to the solenoid", "Worn torque converter"]'::jsonb,
  '["Shuddering or vibration at cruising speed", "Higher than normal RPM at highway speed", "Reduced fuel economy", "Check engine light on"]'::jsonb,
  '["Check transmission fluid level and condition first", "Test the torque converter clutch solenoid", "If fluid and solenoid check out, the torque converter itself may need inspection by a transmission specialist"]'::jsonb,
  '["P0700", "P0742"]'::jsonb,
  '[]'::jsonb,
  'P0740 Code: Torque Converter Clutch Circuit Malfunction | Naira Autos',
  'The torque converter clutch, which locks the engine and transmission together at cruising speed for better fuel economy, isn''t engaging or disengaging',
  true
),
(
  'U0100', 'u0100', 'Lost Communication with ECM/PCM',
  'Network', 'Communication', true,
  'Critical', 'Professional Only',
  'Another control module in the vehicle has lost contact with the main engine control module over the internal communication network (CAN bus).',
  '["Blown fuse powering the engine control module", "Corroded, damaged, or loose wiring on the CAN bus network", "Failing engine control module", "Aftermarket electronics interfering with the network"]'::jsonb,
  '["Multiple warning lights on at once", "Car may not start or may stall unexpectedly", "Dashboard gauges may behave erratically", "Loss of power steering or other assist systems in severe cases"]'::jsonb,
  '["Check the fuse for the engine control module first \u2014 this is the cheapest and most common cause", "Inspect battery and ground connections, since a weak connection can disrupt the whole network", "Have the CAN bus wiring tested for a short or open circuit if fuses and grounds are fine", "This code often needs a professional scan tool capable of network diagnostics \u2014 not a basic code reader"]'::jsonb,
  '["U0101", "U0121"]'::jsonb,
  '[{"question": "My car won''t start and shows this code \u2014 what should I check first?", "answer": "Check the battery terminals and the main fuse box for a blown fuse related to the engine control module. A weak or corroded connection is one of the most common causes and the easiest to fix yourself."}]'::jsonb,
  'U0100 Code: Lost Communication with ECM/PCM | Naira Autos',
  'Another control module in the vehicle has lost contact with the main engine control module over the internal communication network (CAN bus).',
  true
),
(
  'P0016', 'p0016', 'Crankshaft Position — Camshaft Position Correlation (Bank 1, Sensor A)',
  'Powertrain', 'Timing', true,
  'High', 'Hard',
  'The engine control module has detected that the crankshaft and camshaft are out of their expected timing relationship — meaning the engine''s valve timing doesn''t match where the crankshaft actually is.',
  '["Worn or stretched timing chain", "Faulty camshaft or crankshaft position sensor", "Timing chain tensioner failure", "Incorrect installation after recent timing work"]'::jsonb,
  '["Rough running or difficulty starting", "Rattling noise from the timing chain area, especially at startup", "Loss of power", "Check engine light, often flashing"]'::jsonb,
  '["This is a serious mechanical concern \u2014 avoid extended driving until checked", "A mechanic will typically check timing chain stretch and sensor readings with a scan tool that can show live timing correlation", "If the timing chain has stretched, it usually needs replacement along with the tensioner and guides"]'::jsonb,
  '["P0017", "P0008"]'::jsonb,
  '[{"question": "Can I keep driving with this code?", "answer": "It''s not recommended. A timing correlation fault can mean a stretched timing chain, and if it skips further, it can cause serious engine damage (bent valves on many engines). Get it checked as soon as possible."}]'::jsonb,
  'P0016 Code: Crankshaft Position — Camshaft Position Correlation (Bank 1, Sensor A) | Naira Autos',
  'The engine control module has detected that the crankshaft and camshaft are out of their expected timing relationship — meaning the engine''s valve tim',
  true
),
(
  'P0011', 'p0011', 'A Camshaft Position Timing Over-Advanced (Bank 1)',
  'Powertrain', 'Timing', true,
  'Medium', 'Hard',
  'The variable valve timing (VVT) system has advanced the camshaft timing further than the engine control module commanded, and it''s outside the acceptable range.',
  '["Low or dirty engine oil affecting VVT solenoid operation (most common cause)", "Faulty VVT solenoid", "Clogged VVT oil control valve screen", "Worn timing chain/guides"]'::jsonb,
  '["Rough idle", "Reduced power, especially at low RPM", "Check engine light on", "Ticking noise from the VVT solenoid area"]'::jsonb,
  '["Check oil level and condition first \u2014 an overdue oil change is a very common cause of VVT codes", "Clean or replace the VVT solenoid and its screen if oil is fine", "Inspect timing components if the issue persists after solenoid service"]'::jsonb,
  '["P0014", "P0021"]'::jsonb,
  '[{"question": "Will an oil change fix this code?", "answer": "It''s worth trying first if your oil is old, low, or the wrong viscosity \u2014 VVT systems rely on clean oil pressure to work properly, and this is genuinely one of the most common fixes for this code."}]'::jsonb,
  'P0011 Code: A Camshaft Position Timing Over-Advanced (Bank 1) | Naira Autos',
  'The variable valve timing (VVT) system has advanced the camshaft timing further than the engine control module commanded, and it''s outside the accepta',
  true
),
(
  'P0325', 'p0325', 'Knock Sensor Circuit Malfunction (Bank 1)',
  'Powertrain', 'Sensors', true,
  'Medium', 'Moderate',
  'The knock sensor, which listens for abnormal engine vibrations that indicate detonation (''knocking''), has an electrical fault or isn''t sending a usable signal.',
  '["Faulty knock sensor", "Damaged or corroded sensor wiring", "Loose sensor mounting"]'::jsonb,
  '["Usually minimal drivability impact on its own", "Engine may run in a more conservative, less powerful timing mode", "Check engine light on", "Reduced fuel economy in some cases"]'::jsonb,
  '["Check the sensor''s mounting torque and wiring connection for damage", "Test the sensor''s signal output with a scan tool while lightly tapping near it (with the engine off) to confirm it''s detecting vibration", "Replace the sensor if it''s not producing a signal"]'::jsonb,
  '["P0330", "P0326"]'::jsonb,
  '[]'::jsonb,
  'P0325 Code: Knock Sensor Circuit Malfunction (Bank 1) | Naira Autos',
  'The knock sensor, which listens for abnormal engine vibrations that indicate detonation (''knocking''), has an electrical fault or isn''t sending a usabl',
  true
),
(
  'P0087', 'p0087', 'Fuel Rail/System Pressure — Too Low',
  'Powertrain', 'Fuel & Air Metering', true,
  'High', 'Hard',
  'The fuel pressure in the fuel rail is lower than the engine control module expects for current operating conditions, which can starve the engine of fuel.',
  '["Weak or failing fuel pump", "Clogged fuel filter", "Clogged fuel injector(s)", "Faulty fuel pressure regulator", "Fuel pump wiring or relay fault"]'::jsonb,
  '["Loss of power, especially under load or acceleration", "Engine hesitation or stalling", "Difficulty starting", "Check engine light on"]'::jsonb,
  '["Check the fuel filter first if it''s due for replacement", "Test fuel pressure at the rail against specification", "Test the fuel pump''s output and the pressure regulator if pressure is low", "Check fuel pump wiring, relay, and fuse for a supply issue"]'::jsonb,
  '["P0088", "P0191"]'::jsonb,
  '[]'::jsonb,
  'P0087 Code: Fuel Rail/System Pressure — Too Low | Naira Autos',
  'The fuel pressure in the fuel rail is lower than the engine control module expects for current operating conditions, which can starve the engine of fu',
  true
),
(
  'P0102', 'p0102', 'Mass or Volume Air Flow Circuit Low Input',
  'Powertrain', 'Sensors', true,
  'Medium', 'Moderate',
  'The mass airflow (MAF) sensor, which measures how much air enters the engine so the correct amount of fuel can be added, is sending a signal lower than expected.',
  '["Dirty or contaminated MAF sensor (very common, especially with aftermarket air filters/oil)", "Vacuum or intake leak between the sensor and the engine", "Damaged or corroded sensor wiring", "Failed MAF sensor"]'::jsonb,
  '["Hesitation or stumbling on acceleration", "Rough idle", "Check engine light on", "Poor fuel economy"]'::jsonb,
  '["Clean the MAF sensor with a proper MAF-safe cleaner \u2014 this resolves a large share of these codes, especially if you use an oiled air filter", "Inspect the intake tubing between the sensor and throttle body for cracks or loose clamps", "Check wiring and connector for corrosion", "Replace the sensor if cleaning doesn''t restore a normal reading"]'::jsonb,
  '["P0101", "P0103"]'::jsonb,
  '[{"question": "Does cleaning the MAF sensor really work?", "answer": "Often, yes. If you use an aftermarket high-flow air filter that''s oiled, oil residue commonly coats the MAF sensor''s wires and throws off its reading. A MAF-specific cleaner spray (not general electrical cleaner) frequently restores normal operation."}]'::jsonb,
  'P0102 Code: Mass or Volume Air Flow Circuit Low Input | Naira Autos',
  'The mass airflow (MAF) sensor, which measures how much air enters the engine so the correct amount of fuel can be added, is sending a signal lower tha',
  true
),
(
  'P0141', 'p0141', 'O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)',
  'Powertrain', 'Sensors', true,
  'Medium', 'Moderate',
  'Same fault as P0135, but on the downstream oxygen sensor (Sensor 2, located after the catalytic converter) instead of the upstream one.',
  '["Failed heater element in the downstream oxygen sensor", "Damaged or corroded wiring/connector", "Blown fuse for that sensor''s heater circuit"]'::jsonb,
  '["Usually no immediate drivability symptoms", "Check engine light on"]'::jsonb,
  '["Check the relevant fuse first", "Inspect the sensor''s wiring and connector", "Test heater circuit resistance and replace the sensor if the heater element has failed"]'::jsonb,
  '["P0135", "P0161"]'::jsonb,
  '[]'::jsonb,
  'P0141 Code: O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2) | Naira Autos',
  'Same fault as P0135, but on the downstream oxygen sensor (Sensor 2, located after the catalytic converter) instead of the upstream one.',
  true
),
(
  'P0335', 'p0335', 'Crankshaft Position Sensor A Circuit Malfunction',
  'Powertrain', 'Sensors', true,
  'High', 'Moderate',
  'The crankshaft position sensor, which tells the engine control module exactly where the crankshaft is so it can time fuel injection and ignition, isn''t sending a usable signal.',
  '["Faulty crankshaft position sensor", "Damaged or corroded wiring/connector", "Debris or metal shavings on the sensor tip", "Damaged sensor reluctor ring/tone wheel"]'::jsonb,
  '["Engine may crank but not start", "Stalling while driving, sometimes intermittently", "Rough running or misfire-like symptoms", "Check engine light on"]'::jsonb,
  '["Inspect the sensor''s wiring and connector for damage or corrosion", "Check the sensor tip for metal debris and clean if needed", "Test the sensor''s signal output with an oscilloscope or scan tool if available", "Replace the sensor if it''s not producing a consistent signal \u2014 this is a common cause of intermittent no-start or stalling issues"]'::jsonb,
  '["P0336", "P0016"]'::jsonb,
  '[{"question": "My car sometimes won''t start, then works fine later \u2014 could this be the cause?", "answer": "Yes, an intermittent crankshaft position sensor fault is one of the classic causes of unpredictable no-start or random stalling issues, since the engine can''t time ignition without a reliable signal."}]'::jsonb,
  'P0335 Code: Crankshaft Position Sensor A Circuit Malfunction | Naira Autos',
  'The crankshaft position sensor, which tells the engine control module exactly where the crankshaft is so it can time fuel injection and ignition, isn''',
  true
),
(
  'P0716', 'p0716', 'Input/Turbine Speed Sensor Circuit Range/Performance',
  'Powertrain', 'Transmission', true,
  'High', 'Professional Only',
  'The transmission''s input (turbine) speed sensor, which tracks how fast the input shaft is spinning, is sending a signal outside the expected range.',
  '["Faulty input speed sensor", "Damaged or corroded wiring/connector", "Low or contaminated transmission fluid affecting internal sensor performance", "Internal transmission wear (less common, more serious)"]'::jsonb,
  '["Harsh, delayed, or erratic shifting", "Transmission may enter a protective ''limp'' mode", "Check engine or transmission warning light on"]'::jsonb,
  '["Check transmission fluid level and condition first", "Inspect the sensor''s wiring and connector for external damage", "A transmission specialist will typically need to test the sensor with dedicated equipment, since it''s usually mounted inside the transmission housing"]'::jsonb,
  '["P0717", "P0700"]'::jsonb,
  '[]'::jsonb,
  'P0716 Code: Input/Turbine Speed Sensor Circuit Range/Performance | Naira Autos',
  'The transmission''s input (turbine) speed sensor, which tracks how fast the input shaft is spinning, is sending a signal outside the expected range.',
  true
),
(
  'P0122', 'p0122', 'Throttle/Pedal Position Sensor/Switch A Circuit Low Input',
  'Powertrain', 'Sensors', true,
  'Medium', 'Moderate',
  'The throttle position sensor is sending a signal lower than the engine control module expects at any point in its range of motion.',
  '["Faulty throttle position sensor", "Damaged or corroded wiring/connector", "Dirty or worn throttle body affecting sensor contact"]'::jsonb,
  '["Hesitation or jerky acceleration", "Idle may be unstable", "Check engine light on", "Possible reduced-power mode in severe cases"]'::jsonb,
  '["Inspect the sensor''s wiring and connector for damage", "Clean the throttle body, since carbon buildup can affect sensor contact on some designs", "Test the sensor''s voltage output through its full range and replace if it drops out or reads incorrectly"]'::jsonb,
  '["P0121", "P0123"]'::jsonb,
  '[]'::jsonb,
  'P0122 Code: Throttle/Pedal Position Sensor/Switch A Circuit Low Input | Naira Autos',
  'The throttle position sensor is sending a signal lower than the engine control module expects at any point in its range of motion.',
  true
)
ON CONFLICT (code) DO NOTHING;
